### ISSUE TITLE
Not able to send message to slack private channel 

### ISSUE THREAD

**Issue by shashwat-appdirect** [argoproj/argo-events#1028]
**Describe the bug**
Messages to slack private channel not working due to the below issue in line 111:
https://github.com/argoproj/argo-events/blob/f9d2cc04120d1ad842681ce02ecf8c596bad26fc/sensors/triggers/slack/slack.go#L111

For the method conversations.list, "types" is to be set as public_channel or/and private_channel. in the above line this argument is not set and hence by default it takes only "public_channel".

**To Reproduce**
Use argo events for triggering slack notification by hitting a curl request with a private channel name and a message.
followed this page - https://argoproj.github.io/argo-events/triggers/slack-trigger/

**Expected behavior**
Message should be successfully delivered to private slack channel

**Screenshots**
NA

**Environment (please complete the following information):**
 - Kubernetes: v1.19.4
 - Argo: v2.12.2
 - Argo Events: v1.1.0

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@shashwat-appdirect, thanks for reporting, would you like to raise a PR for it?

**Comment by shashwat-appdirect** [comment]
> @shashwat-appdirect, thanks for reporting, would you like to raise a PR for it?

Yes. I'll raise a PR and reply.

**Comment by shashwat-appdirect** [comment]
Hi @whynowy,
I have raised a PR for this - https://github.com/argoproj/argo-events/pull/1036. Could you please review. 
All checks are passed.

Thanks.

**Comment by shashwat-appdirect** [comment]
Hi @whynowy,
I tested it using curl with the latest v1.2.1, but seems that the issue is still there. And this time I am getting a different error. For public channel it is working whereas for private it is failing with below error:

`2021/01/27 09:35:01 protocol error: received *http.http2GoAwayFrame before a SETTINGS frame
{"level":"error","ts":1611740101.401435,"logger":"argo-events.sensor","caller":"slack/slack.go:118","msg":"unable to list channels","sensorName":"webhook","error":"Post \"https://slack.com/api/conversations.list\": connection error: PROTOCOL_ERROR","stacktrace":"github.com/argoproj/argo-events/sensors/triggers/slack.(*SlackTrigger).Execute\n\t/home/runner/work/argo-events/argo-events/sensors/triggers/slack/slack.go:118\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:267\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:158"}
{"level":"error","ts":1611740101.403081,"logger":"argo-events.sensor","caller":"sensors/listener.go:160","msg":"failed to trigger actions","sensorName":"webhook","error":"failed to list channels: Post \"https://slack.com/api/conversations.list\": connection error: PROTOCOL_ERROR","errorVerbose":"Post \"https://slack.com/api/conversations.list\": connection error: PROTOCOL_ERROR\nfailed to list channels\ngithub.com/argoproj/argo-events/sensors/triggers/slack.(*SlackTrigger).Execute\n\t/home/runner/work/argo-events/argo-events/sensors/triggers/slack/slack.go:119\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:267\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:158\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.13/x64/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:160"}`

Now it is not able to list the channels itself. I debugged and found that the fix which we merge might have something wrong:
We merged the below:
`Types: []string{"public_channel,private_channel"},`
whereas I think it should be as :
`Types: []string{"public_channel","private_channel"},`

**Note the 2 words are the two different strings. Please suggest if my understanding is correct and we need a change. I have raised a PR for your review in case my understanding is correct - https://github.com/argoproj/argo-events/pull/1038**

Thanks a lot!
