### ISSUE TITLE
Update status subresource in controller reconciliation

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1029]
**Is your feature request related to a problem? Please describe.**
Currently during controller reconciliation, we use CRD object update to update status field, this leads to another UPDATE notification to the controller. And there's a bug that the controller checks if the old object status is deep equal the reconciled object status to determine if needs another update, however because the condition lastTransitionTime always changes, so it keeps updating the object status.

**Describe the solution you'd like**
1. Enable `status` subresource, use status update api to the object status;
2. Always update status field when there's reconciliation loop;
3. Add filters to controller watcher to only watch `generation` changes (which is caused by a spec change).

**Describe alternatives you've considered**

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by lingxiankong** [comment]
Hi I am still facing the same issue. I am running argo event 1.7, in EventSource, we defined the events of ADD and UPDATE on a K8S resource, then in the workflow we updated the status field of the same type of resource, and we noticed that has triggered an infinite loop, any hint of solving this?

**Comment by whynowy** [comment]
> Hi I am still facing the same issue. I am running argo event 1.7, in EventSource, we defined the events of ADD and UPDATE on a K8S resource, then in the workflow we updated the status field of the same type of resource, and we noticed that has triggered an infinite loop, any hint of solving this?

Your issue is different from the original one.

It's actually expected for your use case - eventsource watches an object, and then triggers a workflow, the workflow updates the object status, which is also an UPDATE event, and then it becomes an infinite loop. I would suggest you take a close look at. the UPDATE event, and add some accurate filters to the eventsource config to avoid the status update being watched.

You could you a `log` trigger to print out the UPDATE event, and find right fields for filtering.

**Comment by lingxiankong** [comment]
> It's actually expected for your use case - eventsource watches an object, and then triggers a workflow, the workflow updates the object status, which is also an UPDATE event, and then it becomes an infinite loop. I would suggest you take a close look at. the UPDATE event, and add some accurate filters to the eventsource config to avoid the status update being watched.
> 
> You could you a `log` trigger to print out the UPDATE event, and find right fields for filtering.

Thanks for your reply, @whynowy 

Yeah, updating to status subresources still do cause watchers to see an update event for the resource, normally in Kubernetes operators, we use `GenerationChangedPredicate` to discard update events that do not increase the ResourceGeneration, but this is not supported in EventSource at the moment.

After testing I came up with a solution, which is using Script filter in Sensor to skip the UPDATE events caused by status update, like this:
```
if event.type == "UPDATE" and event.body.metadata.generation == event.oldBody.metadata.generation then return false else return true end
```

**Comment by whynowy** [comment]
> 

Nice! BTW - you also can use the filter feature in EventSource, see https://github.com/argoproj/argo-events/blob/master/docs/eventsources/filtering.md

**Comment by lingxiankong** [comment]
> > 
> 
> Nice! BTW - you also can use the filter feature in EventSource, see https://github.com/argoproj/argo-events/blob/master/docs/eventsources/filtering.md

Hmm...according to the function implementation [here](https://github.com/argoproj/argo-events/blob/master/eventsources/sources/resource/start.go#L274), I don't think the EventSource filter of resource type is able to access the fields of the old version object.

**Comment by whynowy** [comment]
> > > 
> > 
> > 
> > Nice! BTW - you also can use the filter feature in EventSource, see https://github.com/argoproj/argo-events/blob/master/docs/eventsources/filtering.md
> 
> Hmm...according to the function implementation [here](https://github.com/argoproj/argo-events/blob/master/eventsources/sources/resource/start.go#L274), I don't think the EventSource filter of resource type is able to access the fields of the old version object.

The filter I mentioned is the one for all the eventsource, not the particular one for `Resource` event source.

**Comment by lingxiankong** [comment]
> The filter I mentioned is the one for all the eventsource, not the particular one for `Resource` event source.

Yeah, but I'm using `resource` EventSource, and EventSourceFilter is not supported.

**Comment by whynowy** [comment]
> > The filter I mentioned is the one for all the eventsource, not the particular one for `Resource` event source.
> 
> Yeah, but I'm using `resource` EventSource, and EventSourceFilter is not supported.

I see.... the original `filter` in `Resource` should be replaced with the generic one...
