### ISSUE TITLE
failed to connect to eventbus","eventSourceName":"gcp-pubsub","error":"read tcp xx.yy->xx.yy: i/o timeout

### ISSUE THREAD

**Issue by jrinvictus** [argoproj/argo-events#1049]
When i deploy the event source I am receiving this error message.  We are using istio sidecars.

{"level":"info","ts":1612285251.4413135,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:251","msg":"Starting event source server...","eventSourceName":"gcp-pubsub"}

{"level":"info","ts":1612285251.4417896,"logger":"argo-events.eventsource","caller":"driver/nats.go:92","msg":"NATS auth strategy: Token","eventSourceName":"gcp-pubsub","clientID":"gcp-pubsub-eventsource-bkqwh-c78cd8b56-zr2tt"}

{"level":"error","ts":1612285253.4451041,"logger":"argo-events.eventsource","caller":"driver/nats.go:101","msg":"Failed to connect to NATS server","eventSourceName":"gcp-pubsub","clientID":"gcp-pubsub-eventsource-bkqwh-c78cd8b56-zr2tt","error":"read tcp 10.77.70.34:60982->10.77.70.33:4222: i/o timeout","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect\n\t/argo-events/eventbus/driver/nats.go:101\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start\n\t/argo-events/eventsources/eventing.go:258\nmain.main\n\t/argo-events/eventsources/cmd/main.go:60\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

{"level":"error","ts":1612285253.4452696,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:260","msg":"failed to connect to eventbus","eventSourceName":"gcp-pubsub","error":"read tcp 10.77.70.34:60982->10.77.70.33:4222: i/o timeout","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start\n\t/argo-events/eventsources/eventing.go:260\nmain.main\n\t/argo-events/eventsources/cmd/main.go:60\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

{"level":"fatal","ts":1612285253.4452994,"logger":"argo-events.eventsource","caller":"cmd/main.go:61","msg":"failed to start eventsource server","eventSourceName":"gcp-pubsub","error":"read tcp 10.77.70.34:60982->10.77.70.33:4222: i/o timeout","stacktrace":"main.main\n\t/argo-events/eventsources/cmd/main.go:61\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

**Environment (please complete the following information):**
 - Kubernetes: v1.18.6
 - Argo Events: v1.0.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Do you see the EventBus StatefulSet PODs running well?
