### ISSUE TITLE
NATS Event Source - Support NKEY Credentials

### ISSUE THREAD

**Issue by nfrush** [argoproj/argo-events#1050]
**Is your feature request related to a problem? Please describe.**
Currently, the NATS Event Source cannot connect to clusters that integrate with nats-account-server (to provision accounts that have particular permissions). I'd like to see the NATS Event Source Spec (and implementation) pick up the ability to pass a reference to a secret that contains a valid NATS .creds file

**Describe the solution you'd like**
I'd like to see the NATS Event Source expanded in order to accommodate clusters that accept NKEYs in the form of .creds to authenticate. 

**Describe alternatives you've considered**
If this doesn't get fulfilled, I'll likely write a bridge from a auth enabled NATS cluster to send the message over HTTP POST to the Argo Events Webhook Event Source

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@nfrush - Would you like to do a testing? You need to use the latest installation manifests: https://raw.githubusercontent.com/argoproj/argo-events/master/manifests/install.yaml, and change the images to:

gcr.io/whynowy/sensor:2.096
gcr.io/whynowy/sensor-controller:2.096
gcr.io/whynowy/eventsource:2.096
gcr.io/whynowy/eventsource-controller:2.096
gcr.io/whynowy/eventbus-controller:2.096
