### ISSUE TITLE
Can't delete sensors from Kubernetes

### ISSUE THREAD

**Issue by tomgoren** [argoproj/argo-events#1056]
**Describe the bug**
Created sensors cannot be removed from Kubernetes.

**To Reproduce**
```
# List our sensors
❯ kubectl -n argo-events get sensors
NAME       AGE
aws-sqs    12d
aws-sqs0   2d21h
aws-sqs1   2d21h
aws-sqs2   6d20h
aws-sqs3   2d22h
webhook    19d

# Try to delete old one
❯ kubectl -n argo-events delete sensor aws-sqs --now=true --wait=false
sensor.argoproj.io "aws-sqs" deleted

# Still there, darn
❯ kubectl -n argo-events get sensors
NAME       AGE
aws-sqs    12d
aws-sqs0   2d21h
aws-sqs1   2d21h
aws-sqs2   6d20h
aws-sqs3   2d22h
webhook    19d

# Try again to delete, this time in a slow and safe way
❯ kubectl -n argo-events delete sensor aws-sqs
sensor.argoproj.io "aws-sqs" deleted
...HANGS FOREVER...
```

**Expected behavior**
The sensor should be deleted.

**Environment (please complete the following information):**
 - Kubernetes: v1.17.12-eks-7684af
 - Argo: `latest`
 - Argo Events: v1.2.2

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
If you can reproduce it, could you check what was going on in `sensor-controller` POD logs?

**Comment by tomgoren** [comment]
The only things in the `sensor-controller` logs were spec errors related to the sensors we were trying to delete.

**Comment by tomgoren** [comment]
This looks like it is related to https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-369099998.


Running:

```
kubectl -n argo-events patch sensor/aws-sqs -p '{"metadata":{"finalizers":[]}}' --type=merge
```

Unblocked the deletion.

**Comment by whynowy** [comment]
I understand it was the finalizer issue, but actually our Sensor finalizer does not do anything as you can see in https://github.com/argoproj/argo-events/blob/master/controllers/sensor/controller.go#L87-L89.

Do you see this issue every time you delete a Sensor?

**Comment by tomgoren** [comment]
Yes, the system was stuck and was unable to delete on several of the CRDs as well.

**Comment by whynowy** [comment]
Unfortunately I can not reproduce it from my side, are you getting any problem to delete other CRD objects other than the ones from argo-events?

**Comment by tomgoren** [comment]
The issue seems to have gone away after we blasted away everything and started fresh. Thank you!

**Comment by christophercutajar** [comment]
We're experiencing the same issue and the only way to resolve this is to delete everything and re-deploy everything from scratch!

**Comment by christophercutajar** [comment]
@sairamkrish The only way we avoided deleting everything is to halt the finalisers as per mentioned in https://github.com/argoproj/argo-events/issues/1056#issuecomment-775349646

**Comment by sairamkrish** [comment]
I believe it is an issue with dangling old controller references in latest kubernetes resource definitions.
Tried to answer in detail in [this stackoverflow question](https://stackoverflow.com/a/75458670/1294667)
