### ISSUE TITLE
Document HA/DR recommendations

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-events#1071]
For HA/DR:

EventBus should be:

* DR: Backed by volume.
* HA: Use multi-az, pod anti-affinity to schedule SS pods on different nodes.

Document recommendations.

See #899, #1072, #1073

**Comment by alexec** [comment]
Document how we prevent eviction:

* Senor/Event Source - can we set pod priority?

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/pull/1095
