### ISSUE TITLE
JoinConversation for private channel fails with error "method_not_supported_for_channel_type"

### ISSUE THREAD

**Issue by shashwat-appdirect** [argoproj/argo-events#1077]
**Describe the bug**
Failed to post message to private channels using argo-events slack trigger. Gets below error in sensor logs:
```
{"level":"error","ts":1613722091.5494733,"logger":"argo-events.sensor","caller":"slack/slack.go:139","msg":"unable to join channel...","sensorName":"webhook","channelName":"wfprivatetest","channelID":"G01K0USUPT7","error":"method_not_supported_for_channel_type","stacktrace":"github.com/argoproj/argo-events/sensors/triggers/slack.(*SlackTrigger).Execute\n\t/home/runner/work/argo-events/argo-events/sensors/triggers/slack/slack.go:139\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:267\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:158"}
{"level":"error","ts":1613722091.5495732,"logger":"argo-events.sensor","caller":"sensors/listener.go:160","msg":"failed to trigger actions","sensorName":"webhook","error":"failed to join channel wfprivatetest: method_not_supported_for_channel_type","errorVerbose":"method_not_supported_for_channel_type\nfailed to join channel wfprivatetest\ngithub.com/argoproj/argo-events/sensors/triggers/slack.(*SlackTrigger).Execute\n\t/home/runner/work/argo-events/argo-events/sensors/triggers/slack/slack.go:140\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:267\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:158\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.14.15/x64/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.3\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:160"}
```
On further debugging found that the code is trying to join a private channel and this is not supported from a bot. Also, tried to test POST message slack API after manually adding slack bot app to the private channel and it works. Hence, JoinConversation is not required in case of a private channel.

**To Reproduce**
Install argo-events and slack trigger sensor and try to post a message to any private channel using curl request.

**Expected behavior**
Message should be successfully posted to the provide channel.

**Screenshots**
NA

**Environment (please complete the following information):**
 - Kubernetes: v1.19.4
 - Argo: v2.12.2
 - Argo Events: 1.2.3

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by shashwat-appdirect** [comment]
Hi @whynowy,
I tested argo-events v1.2.3 for slack notification trigger and found this error particularly for private channels. After debugging raised a PR - https://github.com/argoproj/argo-events/pull/1078 to fix it.
Could you please review.

Thank you.

**Comment by whynowy** [comment]
#1078
