### ISSUE TITLE
Installation docs point to a file that doesn't exist

### ISSUE THREAD

**Issue by tico24** [argoproj/argo-events#1105]
**Describe the bug**
Line 20 of /docs/installation.md points the reader to `https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml`. This file does not exist on the stable branch.

I would do a PR but I'm unsure what the intended solution should be. Should the reader be pointed at the master branch? (eg `https://raw.githubusercontent.com/argoproj/argo-events/master/manifests/install-validating-webhook.yaml`, or should the file be added to the stable branch?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml
2. 404

**Expected behaviour**
The docs should show the user how to correctly install the product

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
This is because the `gh-pages` is generated with `master` branch docs, however there are some new features are not in `stable` until new version is released.

**Comment by whynowy** [comment]
`stable` tag updated, it's working now.
