### ISSUE TITLE
Get version, kind and resource from the spec when creating k8s/workflows

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1143]
**Is your feature request related to a problem? Please describe.**
When creating `k8s` or `argoWorkflow` resources in the Sensor, `version`, `kind` and `resource` are required, which seem to be redundant. 

**Describe the solution you'd like**
The sensor should be able to figure out those properties automatically from the provided k8s object or workflow spec.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by daniel-codefresh** [comment]
Hey @whynowy, heres the PR :) #1333
