### ISSUE TITLE
eventbus-default-stan-svc Authentication Timeout issue

### ISSUE THREAD

**Issue by linuslukia** [argoproj/argo-events#1144]
**Describe the bug**
I have a bug on event source and sensor:
{"level":"error","ts":1617094839.3151531,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:298","msg":"failed to reconnect to eventbus","eventSourceName":"eventsource","error":"stan: connect request timeout (possibly wrong cluster ID?)","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func2\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:298"}
and
{"level":"error","ts":1617093790.679391,"logger":"argo-events.sensor","caller":"driver/nats.go:115","msg":"Failed to connect to NATS streaming server","sensorName":"sensor","clientID":"client-1166768877-80","error":"stan: connect request timeout (possibly wrong cluster ID?)","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:115\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:199"}
{"level":"error","ts":1617093790.679465,"logger":"argo-events.sensor","caller":"sensors/listener.go:201","msg":"failed to reconnect to eventbus","sensorName":"sensor","clientID":"client-1166768877-80","error":"stan: connect request timeout (possibly wrong cluster ID?)","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:201"}

so from above error, i think it is event bus connection issue, then i try to create a pod to connect to `eventbus-default-stan-svc`:
$ kubectl -n argo-events run testing --image=whynowy/swing
pod/testing created
$ kubectl exec -it testing -n $ns -- /bin/bash
root@testing:/# telnet eventbus-default-stan-svc 4222
Trying 172.16.22.86...
Connected to eventbus-default-stan-svc.argo-events.svc.cluster.local.
Escape character is '^]'.
INFO {"server_id":"NDDUSFV4ZFIXD5N6QP4U242N27OWIYPKLKNYDLNDJMVX2JBNDGC335ZT","server_name":"NDDUSFV4ZFIXD5N6QP4U242N27OWIYPKLKNYDLNDJMVX2JBNDGC335ZT","version":"2.1.4","proto":1,"git_commit":"fb009af","go":"go1.13.7","host":"0.0.0.0","port":4222,"auth_required":true,"max_payload":1048576,"client_id":1593,"connect_urls":["172.16.22.86:4222"]} 
-ERR 'Authentication Timeout'
Connection closed by foreign host.

**Environment (please complete the following information):**
 - Kubernetes: 
 - $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5",  Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", , Platform:"linux/amd64"}
 - argoproj/argoexec:v2.10.0
 - argoproj/argocli:v2.10.0
 - argoproj/eventbus-controller:v1.2.2
 - eventsource-controller:v1.2.2
 - argoproj/sensor-controller:v1.2.2

Can someone help me ?

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@linuslukia - Does killing the EventSource/Sensor Pods help?

**Comment by linuslukia** [comment]
It runs well for more than 1 month on prod, it is the first time to have such issue since we update to v1.2.2 one month ago, and i tried to only kill the sensor pod, it still shows above error, and it failed the event that we sent to kafka(we use kafka as eventsource trigger), but after serveral minutes, i can see from logs sensor and event source comeback to normal, and new event can pass successfully @whynowy

**Comment by whynowy** [comment]
Do you see any EventBus Pods got refreshed by checking the pod ages?

**Comment by linuslukia** [comment]
Sorry for late reponse, we are using aws eks
yes, EventBus Pods are refreshed by us, basically each time when we see issue like `failed to connect to eventbus` from event source, we will refresh event bus

**Comment by whynowy** [comment]
@linuslukia - do you still have the problem? Seeing a similar issue at https://github.com/nats-io/nats-streaming-server/issues/629, that was caused by unexpected big message. Do you have similar cases?
