### ISSUE TITLE
install-validating-webhook.yaml missing in stable release

### ISSUE THREAD

**Issue by lautou** [argoproj/argo-events#1155]
**Describe the bug**
install-validating-webhook.yaml is missing in stable release

**To Reproduce**
Following the documentation https://argoproj.github.io/argo-events/installation:
1. Run kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml

Get an error message:
error: unable to read URL "https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml", server reported 404 Not Found, status code=404

**Expected behavior**
Resources are installed

**Screenshots**

**Environment (please complete the following information):**
 - OpenShift 4.7.2

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
It's a new stuff introduced in v1.3, which is going to be released soon, rc versions current available, https://github.com/argoproj/argo-events/releases/tag/v1.3.0-rc2. Once it's released, we will tag stable version.

**Comment by whynowy** [comment]
`stable` tag updated.
