### ISSUE TITLE
Add Additional Documentation on K8s Trigger for API Groups

### ISSUE THREAD

**Issue by joshuajorel** [argoproj/argo-events#1164]
**Is your feature request related to a problem? Please describe.**
When creating K8s object for custom CRDs, it does not specify the "plurality" of the object that you need to pass to the [K8s Trigger](https://argoproj.github.io/argo-events/sensors/triggers/k8s-object-trigger/#trigger-a-k8s-pod). Specifically, you need to pass the "plural" name of API Group of the object you are trying to add. 

**Describe the solution you'd like**
Additional documentation on the K8s trigger that tells you that you need the "plural" form of the API Group.

**Describe alternatives you've considered**
Simple document change.

**Additional context**
Took some time for me to get Argo Events to work with CRDs only to find out I just needed to specify the API group in its plural form. i.e. pods not pod. 

https://github.com/kubernetes/client-go/issues/737 <- specifies you need to use the plural name of the resource

https://github.com/argoproj/argo-events/blob/b97a84d836c6c5d5948780664b403cb6b506e688/sensors/triggers/standard-k8s/standar-k8s.go#L181

I can easily add a PR to the documentation for this. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
group/version/kind are not needed any more.
