### ISSUE TITLE
Workflows remain stuck in pending state, fail to complete

### ISSUE THREAD

**Issue by msbecker** [argoproj/argo-events#1195]
**Describe the bug**
Workflows created using sensor triggers remain in a pending state and never complete.

**To Reproduce**
Deploy Argo Events as outlined in the documentation. https://argoproj.github.io/argo-events/quick_start/
Use curl to generate new workflow.
View the pod created, use argo CLI to get status of workflow..
Workflow remains in a "Pending" state and never completes. No logs are generated by the workflow

**Expected behavior**
Workflow should complete and logs should be available.

**Environment (please complete the following information):**
 - Kubernetes: 1.19.1
 - Argo: 3.0.2
 - Argo Events: 1.3

**Additional context**
Kubernetes running on AKS with kubenet network. Using k8sapi container runtime as Docker is no longer used by AKS.

---

**Comment by whynowy** [comment]
Is your workflow-controller installed cluster scope?

**Comment by msbecker** [comment]
I'm running the default config from the quick-start-postgres deployment YAML, so the workflow-controller is running with --namespaced. 
I have the same behavior if I deploy Argo Events in a separate namespace, or if I deploy events to the same namespace Argo workflows are running in.

**Comment by whynowy** [comment]
Workflow in Pending state means the workflow-controller is not taking care of it at all, the possible reason is the workflow-controller is only watching one namespace, and the workflow object was not created in that namespace.

**Comment by msbecker** [comment]
Hmm. I get the same behavior when the workflow-controller and the workflow object are in the same namespace, and when they are not in the same namespace.

**Comment by whynowy** [comment]
Submit a workflow directly to see if it works.

**Comment by msbecker** [comment]
I am able to submit a workflow using the argo CLI. I am able to submit a workflow from a workflowtemplate using the UI. I am able to submit a workflow from a workflowtemplate using the workflows/argo/submit endpoint. I am able to create a workflow using the workflows/argo endpoint by submitting the JSON as part of the curl command.
Not clear why using the sensor trigger can create the workflow, but the status remains "Pending". I can view the workflow pod, see the base64 encoded message in the pod, decode it and see the message.

**Comment by whynowy** [comment]
> I am able to submit a workflow using the argo CLI. I am able to submit a workflow from a workflowtemplate using the UI. I am able to submit a workflow from a workflowtemplate using the workflows/argo/submit endpoint. I am able to create a workflow using the workflows/argo endpoint by submitting the JSON as part of the curl command.
> Not clear why using the sensor trigger can create the workflow, but the status remains "Pending". I can view the workflow pod, see the base64 encoded message in the pod, decode it and see the message.

I understand how frustrated you are, technically there's no difference between a sensor created workflow and a cli submitted workflow. I guess there's some mystery in the workflow spec, could you use cli to submit exact same workflow, and then compare it with the one created by sensor? Also, you could you look into workflow-controller log, to see if there's any clue.

**Comment by msbecker** [comment]
No worries. I'm really just testing it out right now.
I am now able to trigger a workflow with the sensor and it complete. I redeployed everything, as before, but now it works. May have been something didn't deploy right before.
I'll close this now. Thanks for the help.
