### ISSUE TITLE
Cannot delete the `argo-events` namespace due to a stuck eventbus and kafka sensor

### ISSUE THREAD

**Issue by justinmchase** [argoproj/argo-events#1199]
**Describe the bug**
I cannot delete the argo-events namespace because two resources are stuck and are undeletable.
```sh
kubectl -n argo-events delete eventbus default
kubectl -n argo-events delete sensor kafka
kubectl delete namesapce argo-events
```

All three of these commands hang indefinitely (using `--force` doesn't fix it) and I am unable to remove or re-create these resources.

**To Reproduce**
1. I ran these scripts:
```sh
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-postgres.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/namespace-install.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/kafka.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/kafka.yaml
```
2. Then attempt to delete:
```sh
kubectl delete namesapce argo-events
kubectl delete namesapce argo
```

**Expected behavior**
Both argo namespaces are deleted and all resources are removed

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Kubernetes: v1.19.7
 - Argo: latest
 - Argo Events: latest

**Additional context**
Its hard for me to reproduce exactly due to being in a stuck state but I did have an issue I was trying to recover from... which is that I created a kafka sensor that I had copy pasted from one of the examples which contained a reference to a service account which did not exist:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: kafka
  namespace: argo
spec:
  template:
    serviceAccountName: operate-workflow-sa
  # ...
```

This appeared to cause an issue which was breaking some things. I was attempting to delete the whole namespace so I could start over and first create the service account, role and bindings which I found in a different example elsewhere... But I am stuck at the deletion point.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by justinmchase** [comment]
Here I am looking at how to finalize the resource and so I am doing this to get more info:
```sh
 kubectl -n argo-events get sensor kafka -o json > tmp.json
 ```
 
 And I see that the sensor has this finalizer:
 ```json
{
    "apiVersion": "argoproj.io/v1alpha1",
    "kind": "Sensor",
    "metadata": {
        "finalizers": [
            "sensor-controller"
        ]
    }
}
```

But I don't see a `sensor-controller` resource at all. Similarly the event bus is waiting on ` eventbus-controller`, which I am pretty sure also does not exist...

How is that possible?

I found that I am able to release these resources like this:
```sh
kubectl -n argo-events get sensor kafka -o json | jq '.metadata.finalizers = null' | kubectl apply -f -
kubectl -n argo-events get eventbus default -o json | jq '.metadata.finalizers = null' | kubectl apply -f -
```

That in turn releases the namespace... Though I'm not worried that I have some hidden controller resources lurking somewhere.

**Comment by whynowy** [comment]
The controller deployments(eventsource-controller, sensor-controller and eventbus-controller) should not be deleted before deleting the eventsource, sensor and eventbus objects, otherwise nobody takes care of those finalizers, thus they will be stuck.

**Comment by justinmchase** [comment]
The kafka eventsource is now also hanging as I try to reproduce it.

Re-installing then uninstalling reproduces the same issue, to delete the namespace consistently I have to do this:
```sh
kubectl delete namespace argo-events &
kubectl -n argo-events get sensor kafka -o json | jq '.metadata.finalizers = null' | kubectl apply -f -
kubectl -n argo-events get eventbus default -o json | jq '.metadata.finalizers = null' | kubectl apply -f -
kubectl -n argo-events get eventsource kafka -o json | jq '.metadata.finalizers = null' | kubectl apply -f -
wait
```

**Comment by justinmchase** [comment]
@whynowy 

How can I find these resources and delete them? Are they in a different namespace? Why are they stuck?

**Comment by whynowy** [comment]
Those controllers are installed in `argo-events` namespace. I guess what you have done first was probably running `kubectl delete ns argo-events`, which had no deleting order guarantee, and the controller deployments were deleted before those crd objects.

The right clean up order would be:
1. delete crd objects in all namespaces (eventsource, sensor, eventbus).
2. delete the controller plane deployments in argo-events namespace.
3. delete other stuffs (rolebinding/clusterrolebinding, role/clusterrole, etc)

For 2 and 3, you can run `kubectl delete -f {installation-file}`.

If it's already in the stuck status, beside remove the finalizers manually as you did, you can install the controllers back, and then clean up with the right order.

**Comment by justinmchase** [comment]
I see yes, I thought that kubernetes was resolving the dependency order for deletion but it appears it does not and since they were installed from seperate files they should be deleted in reverse order. Therefore if I just take the script block from above and swap `apply`->`delete` and then reverse the order it works correctly.

```sh
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/kafka.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/kafka.yaml
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/namespace-install.yaml
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/quick-start-postgres.yaml
kubectl delete namespace argo-events
kubectl delete namespace argo
```
