### ISSUE TITLE
Support secrets for HTTP Trigger headers. 

### ISSUE THREAD

**Issue by maganaluis** [argoproj/argo-events#1227]
**Is your feature request related to a problem? Please describe.**

It will be great to support secrets as part for HTTP Trigger headers, since not all the time users will have basic authentication, in our case we are trying to integrate with an application which uses service tokens. 

**Describe the solution you'd like**

To ensure backwards compatibility we create a new field in the HTTP Trigger e.g. SecureHeaders, where value for this hash map is retrieved from a secret such as in the BasicAuth field.

**Describe alternatives you've considered**

Current alternatives is to use the headers, and template the YAML so we do not store the credentials in GitHub.

**Additional context**

We can provide this PR if this is an acceptable solutoin. 

N/A

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
I like the idea, looking forward to seeing this, thanks!

**Comment by marcjimz** [comment]
Would love to see this feature as well!
