### ISSUE TITLE
Communication between Transformer and Sensor through Service Name

### ISSUE THREAD

**Issue by twiechert** [argoproj/argo-events#130]
**Is your feature request related to a problem? Please describe.**
Currently, the transformer communicates with the sensor through an ip address (load balancer, cluster ip oder external ip). Since the sensors have services attached, I wonder why it is not possible to call them directly by their service name and let the DNS resolve it. This is especially of importance, when DNS resolution is externalized and handled in sidecars (for example with istio).

**Describe the solution you'd like**
Either go by the service name by default or allow using the service name.

**Comment by VaibhavPage** [comment]
I forgot to address this issue due to other features, but you are definitely right, communication should be done using service name.
