### ISSUE TITLE
GitHub EventSource should be able to create webhooks at GitHub organization level.

### ISSUE THREAD

**Issue by YesemKebede** [argoproj/argo-events#1308]
For use cases that involve listening in for organizational events such as repository creation and deletion, there is no good way to create webhooks from GitHub EventSource. It looks like GitHub EventSource definition expects repository name to be defined in order to create a webhook. It would be awesome if Github EventSource also supports creating webhooks at organization level.

As a workaround I tried setting up a generic webhook and it works but starts failing when I add authSectret. See  [#1289 ](https://github.com/argoproj/argo-events/issues/1289)for detail

**Comment by daniel-codefresh** [comment]
I can take a look at this one, @whynowy can you assign it to me please?

**Comment by whynowy** [comment]
Of course! @daniel-codefresh

**Comment by daniel-codefresh** [comment]
@whynowy Heres the related PR: #1412
