### ISSUE TITLE
Unable to use eventbus with istio.

### ISSUE THREAD

**Issue by antoniomo** [argoproj/argo-events#1311]
**Describe the bug**

When using the eventbus as created by the eventbus controller, with "native" strategy, the sensors can't connect to the eventbus if they have an istio-proxy sidecar. In organizations using istio, it's common to have the istio sidecar at the very least on the webhook event sources.

**To Reproduce**

Install a default eventbus, try to connect from an eventsource with istio-proxy sidecar.

---
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by oursland** [comment]
This issue has prevented me from using Argo Events in my deployments.

The error noted on issue #855 by @lironrisk and observed by @ajoskowski and @wajdi-datalvo matches the one exhibited when deploying Argo Events in an Istio-enabled namespace.

The relevant line, pretty-printed:

```
[
   {
      "caller" : "driver/nats.go:102",
      "clientID" : "client-webhook-eventsource-4p9tf-5df7969b6b-nvqhm-629",
      "error" : "read tcp 10.42.0.40:42834->10.42.2.28:4222: i/o timeout",
      "eventSourceName" : "webhook",
      "level" : "error",
      "logger" : "argo-events.eventsource",
      "msg" : "Failed to connect to NATS server",
      "stacktrace" : "github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:102\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:317\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:107\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.7-rc.0/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.7-rc.0/pkg/util/wait/wait.go:399\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:316\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:284\ngithub.com/argoproj/argo-events/eventsources/cmd.Start\n\t/home/runner/work/argo-events/argo-events/eventsources/cmd/start.go:65\ngithub.com/argoproj/argo-events/cmd/commands.NewEventSourceCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/eventsource.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.15.13/x64/src/runtime/proc.go:204",
      "ts" : 1629611654.29257
   }
]
```

**Comment by nicon89** [comment]
Was it included in latest release? I'm having same error in version 1.4.1.
@antoniomo : have you had to add any configuration to istio to get it working?

**Comment by oursland** [comment]
The fix is in commit [d8cf6e0249edbd6d88e161f9ebab05520c28465e](https://github.com/argoproj/argo-events/commit/d8cf6e0249edbd6d88e161f9ebab05520c28465e) which is not yet in any tagged release.

The `latest` tag for the argo-events container does include these changes and can be installed via the `master` manifests (not `stable`).

**Comment by nicon89** [comment]
@oursland good to know, thank you.
Is there a release planned in a near future?

**Comment by antoniomo** [comment]
@nicon89 if you don't want to build your own from master, etc, one workaround is to edit the eventbus service (for example: `kubectl edit svc eventbus-default-stan-svc` and then add the change to the client port (rename the port name:

```yaml
...
spec:
  ...
  ports:
  - name: client
```
And rename that `- name: client` to `- name: tcp-client`.

Not saying this is a good practice, but just as a temporary workaround.

**Comment by nicon89** [comment]
Right, I changed that, but unfortunately I'm getting error:
`{"level":"fatal","ts":1632154220.1866817,"logger":"argo-events.eventsource","caller":"cmd/start.go:66","msg":"failed to start eventsource server","eventSourceName":"github","error":"timed out waiting for the condition: read tcp 10.99.1.185:35006->10.99.1.133:4222: i/o timeout","stacktrace":"github.com/argoproj/argo-events/eventsources/cmd.Start\n\t/home/runner/work/argo-events/argo-events/eventsources/cmd/start.go:66\ngithub.com/argoproj/argo-events/cmd/commands.NewEventSourceCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/eventsource.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.15.15/x64/src/runtime/proc.go:204"}`
