### ISSUE TITLE
Sprig dateInZone function not behaving as expected

### ISSUE THREAD

**Issue by paulmaksimovich** [argoproj/argo-events#1314]
With the expression:
`"{{=sprig.dateInZone('Mon Jan 2 15:04:05 MST 2006', sprig.now(), 'EDT')}}"`

The date does not convert timezones.

Given the statement "To invoke a Sprig function, change the name into a function call. The last parameter is usually your variable.", It is my speculation that perhaps argo is parsing "sprig.date" and executing "date" with arguments 1 and 2 instead of execution "dateInZone" with all 3 arguments.

**Comment by bowenisdum** [comment]
@paulmaksimovich did you end up figuring out a work around or solution to this?

**Comment by paulmaksimovich** [comment]
@bowenisdum Yes, turns out ‘EDT’ is not a real timezone, that was my mistake but unknown at the time.
