### ISSUE TITLE
imagePullPolicy support for Eventbus

### ISSUE THREAD

**Issue by Manny2014** [argoproj/argo-events#1316]
Is your feature request related to a problem? Please describe.
Our company security policies require that all deployment/containers have 'Always' for imagePullPolicy.

Describe the solution you'd like
I would like to be able to set the imagePullPolicy for the Statefult that is created for the nats instance. Ideally, on the Eventbus spec.

Describe alternatives you've considered
This is a bit of a blocker for our adoption and short of requesting the namespace in which argo-events will run to be whitelisted from our policy engine or creating a mutation hook for this specific case, there's not much else I can do.

Additional context
I believe above covers it.

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/pull/1325
