### ISSUE TITLE
make the namespace field support multi-namespace resource watching  in K8s resource argo-events 

### ISSUE THREAD

**Issue by berlinsaint** [argoproj/argo-events#1320]
**Is your feature request related to a problem? Please describe.**
Now  i must create k8s resource senosor for per namespace 

**Describe the solution you'd like**
here my some suggestions.
1、make the namespace field  optional in  [https://github.com/argoproj/argo-events/blob/master/api/event-source.md#argoproj.io/v1alpha1.ResourceEventSource](url) . if user not specify namespace, default listen all namespaces'
resource
2、make the namespace support multivalues
3、make the namespace support regex 

**Describe alternatives you've considered**
the easyiest way this suggestion 1 while i'm prefering choosing suggenstion 3

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by jackivanov** [comment]
@berlinsaint has it even been implemented? I can't find associated PRs

**Comment by jackivanov** [comment]
Looks like it's not. Can you reopen the issue, please? cc'd some contributors @daniel-codefresh @whynowy @alexec

**Comment by bukowa** [comment]
You can use `""` for all namespaces for example:
````yaml
namespace: ""
resource: "namespaces"
group: ""
version: "v1"
````
