### ISSUE TITLE
Missing steps in the getting started guide

### ISSUE THREAD

**Issue by natalefalco** [argoproj/argo-events#1322]
**Describe the bug**
On the main getting started guide there is a missing service account creation prequirement/step.
I would add either a requiement warning or extend the existing yaml to create the service acocunt, roles and rolebindings too

**To Reproduce**
1. Go to https://argoproj.github.io/argo-events/quick_start/
2. Follow the instructions

**Expected behavior**
The verification succeed in the end, leaving a better first impression

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: v1.21.3+k3s1
 - Argo: v3.1.8
 - Argo Events: 1.4.0

**Additional context**
In the introduction there is a mention to the service users that are missing 
https://argoproj.github.io/argo-events/tutorials/01-introduction/

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by daniel-codefresh** [comment]
Here's the PR: #1324
