### ISSUE TITLE
Unable to kubectl delete the event-bus

### ISSUE THREAD

**Issue by ado120** [argoproj/argo-events#1348]
**Describe the bug**
Installing the event bus through the docs works fine, but when deleting it using:

```
kubectl delete -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
eventbus.argoproj.io "default" deleted
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml
Warning: Detected changes to resource default which is currently being deleted.
eventbus.argoproj.io/default unchanged
```

it hangs on the deleted portion and seems to be stuck there, is there anyway that I can force delete this and reapply?

**Comment by whynowy** [comment]
Do you have any event source or sensor still alive in that namespace? event bus will hang on deletion if so.

**Comment by athensofamerica** [comment]
Same issue here

**Comment by bmaguilar** [comment]
Same problem here too

```kubectl get all -n argo-events

NAME                          READY   STATUS    RESTARTS   AGE
pod/eventbus-default-stan-0   2/2     Running   0          42s
pod/eventbus-default-stan-1   2/2     Running   0          19d
pod/eventbus-default-stan-2   2/2     Running   0          46m

NAME                                     READY   AGE
statefulset.apps/eventbus-default-stan   3/3     23d ```

**Comment by bmaguilar** [comment]
Had to delete EventBus thru patching finalisation:

`kubectl edit eventbus -n argo-events`

Find the stuck finalizer:

```
    finalizers:
    - eventbus-controller
```

And replace by

```
    finalizers: null
```

**Comment by melihme** [comment]
It is a big nuisance for automated installations. Most CI/CD tools are not clever enough to remove objects in a specified order.

**Comment by rwong2888** [comment]
I've run into this issue aplenty. I wish argocd was intelligent enough to remove these properly... but here are my notes on the issue.


## Stuck Terminating

### argo-events

#### event bus
```
kubectl -n argo-events delete eb default

kubectl -n argo-events get eb default -o json > eb.json

# remove finalizer from eb.json

kubectl -n argo-events replace -f ./eb.json
```

#### eventsource
```
kubectl -n argo-events delete eventsource github

kubectl -n argo-events get eventsource github -o json > gh-eventsource.json

# remove finalizer from gh-eventsource.json

kubectl -n argo-events replace -f gh-eventsource.json
```

#### sensor
```
kubectl -n argo-events delete sensor github

kubectl -n argo-events get sensor github -o json > gh-sensor.json

# remove finalizer from gh-sensor.json

kubectl -n argo-events replace -f gh-sensor.json
```

#### namespace

```
kubectl delete ns argo-events

kubectl get ns argo-events -o json > argo-events.json

# remove finalizer from argo-events.json

kubectl replace -f ./argo-events.json
```

**Comment by xi2817-aajgaonkar** [comment]
i think we can fix this bug by editing the YAML, by `yq` package & then deleting the event bus

**Comment by whynowy** [comment]
EventBus, EventSource and Sensor pods have finalizers protected, they can not be removed without having corresponding controllers running.

No matter you use a cluster scoped installation or namespace scoped installation, control plan applications (those controllers) and user workloads (EventBus, EventSource and Sensor Pods) should be installed/uninstalled separately. In case you want to clean up everything, the proper order should be: 1. deleting user workloads (EventSource, Sensor, EventBus); 2. deleting controller deployments.

**Comment by jmeridth** [comment]
@whynowy we have the corresponding controllers running.  having to manually manipulate the finalizers to get an automated cleanup is unfortunate.  Can you please describe why having the controllers running wouldn't signal the finalizers deletion is permitted?

If the workloads are left but the controllers get deleted, something is out of order IMO.

Locally running `skaffold delete` everything gets deleted but the event bus.  That seems like a valid bug.

I'm fully aware "PRs are welcome" but as a core contributor could you confirm the bug first?  Thank you

**Comment by whynowy** [comment]
> @whynowy we have the corresponding controllers running. having to manually manipulate the finalizers to get an automated cleanup is unfortunate. Can you please describe why having the controllers running wouldn't signal the finalizers deletion is permitted?
> 
> If the workloads are left but the controllers get deleted, something is out of order IMO.
> 
> Locally running `skaffold delete` (in our local environment) everything gets deleted but the event bus. That seems like a valid bug.
> 
> I'm fully aware "PRs are welcome" but as a core contributor could you confirm the bug first? Thank you

Did you see any errors in eventbus-controller? @jmeridth

**Comment by jmeridth** [comment]
:smile: Not yet, but looking.  Was hoping a contributor would find it faster and maybe mention where it might be.  Not asking that contributor to actually do the fix but maybe highlight the error.

The error is the finalizers are not being removed before the controller is deleted IMO.

**Comment by jmeridth** [comment]
@whynowy specifically I don't think [this line](https://github.com/argoproj/argo-events/blob/master/controllers/eventsource/controller.go#L73) can be called for the workloads because the controller gets terminated before it can.  I am not saying this is not a local environment situation or possibly skaffold but since others are experiencing it (this issue), I'd say it's a valid context.  wdyt?

**Comment by whynowy** [comment]
> @whynowy specifically I don't think [this line](https://github.com/argoproj/argo-events/blob/master/controllers/eventsource/controller.go#L73) can be called for the workloads because the controller gets terminated before it can. I am not saying this is not a local environment situation or possibly skaffold but since others are experiencing it (this issue), I'd say it's a valid context. wdyt?

This is what I said that deleting those EventSource/Sensor/EventBus needs the controllers in place. 

So if you want to clean up everything related to argo events, do it in 2 steps: 1. clean up all the user workloads such as event sources, sensors and eventbus, 2. delete the controllers. Don't do them in one shot, they are basically belong to 2 different categories - user workloads and control plane deployments.

**Comment by jmeridth** [comment]
@whynowy Then what is the point of the finalizers if the controllers can be deleted and leave workloads around?  I am trying to understand the approach that has been taken.  This does cause issues for automated clean-up/termination IMO.

Thank you for clarifying my misunderstanding.

I imagine this is a longer conversation that could happen in the CNCF slack argo-events channel.

**Comment by jmeridth** [comment]
@whynowy I got clarification on this from others.  This is a common approach. TIL :smile:

For those interested, we have this in a make file to actually remove the finalizers (1 event bus, 1 sensor, 1 github event source):

```
.PHONY : clean
clean : ## delete all the things
	@skaffold delete
	@kubectl get eventsource github-event-source -o yaml | yq e 'del(.metadata.finalizers)' - | k replace -f -
	@kubectl get sensor x-pr-updated -o yaml | yq e 'del(.metadata.finalizers)' - | k replace -f -
	@kubectl get eb x-event-bus -o yaml | yq e 'del(.metadata.finalizers)' - | k replace -f -
```

Dependent on `yq` tool.

**Comment by ArturZurawski** [comment]
In argocd you can use `sync-wave` to make event bus created/removed in certain order
```
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
```
