### ISSUE TITLE
TOB-ARGO-028 Argo Events NATS streaming service does not use TLS by default - low severity

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-events#1357]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/1142830/134550565-a933c43d-3776-4083-a0a1-f3a7e683de11.png">

**Comment by alexec** [comment]
The authentication does not provide the security, as a user within the namespace could observe the plain text network packets between components and find the authentication token in them. They could then send events to the event bus, triggering workflows (etc.).

The attacker would have already needed to breach security and have access to the cluster to do this. 

@whynowy has stated that implementing a fix is costly.

We don't plan to fix it right now, given we will need to move to a new event bus technology (e.g. JetStream) as NATS Streaming is end of life.

**Comment by vnzongzna** [comment]
@alexec can we reopen this again? since jetStream is implemented now.

**Comment by whynowy** [comment]
TLS for JetStream is done. @vnzongzna @alexec 

https://github.com/argoproj/argo-events/pull/1815

**Comment by alexec** [comment]
We are going to remove NATS. So this issue will be obviated.
