### ISSUE TITLE
Image argoproj/argo-events:v1.4.3 is not available in quay repo.

### ISSUE THREAD

**Issue by fredcoq** [argoproj/argo-events#1365]
**Describe the bug**
CD pipeline broken due to the unavailability of argoproj/argo-events:v1.4.3 in quay.io registry.

**Expected behavior**
The kustomize manifest in argo-events repository (branch 1.4) are pinned to v1.4.3 which have not been pushed to the quay.io registry. The registry should be in sync with the image tag in the branch (1.4).

**Screenshots**

**Environment (please complete the following information):**
-  Argo CD
 - Argo Events: v1.4

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Github actions was not able to resolve `quay.io` at the release time, it's now good.

**Comment by fredcoq** [comment]
Thank you.
