### ISSUE TITLE
support for redis streams

### ISSUE THREAD

**Issue by anuar45** [argoproj/argo-events#1369]
**Is your feature request related to a problem? Please describe.**
It would be nice to have redis streams support as event source

**Describe the solution you'd like**
Able to subscribe to events in redis streams

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by BulkBeing** [comment]
@whynowy / @anuar45 Can you assign this to me? I can implement this.

**Comment by anuar45** [comment]
@BulkBeing I was going to do this, but if you wish please go ahead.
