### ISSUE TITLE
Support GitHub app authentication for GitHub EventSource

### ISSUE THREAD

**Issue by joakimhew** [argoproj/argo-events#1372]
**Is your feature request related to a problem? Please describe.**
A common issue when setting up any sort of connection to GitHub organisations is having to use personal access tokens which might not make sense to the organisation. A workaround for this is to create an GitHub app for the organisation and instead use that to authenticate. This is something argocd already [supports](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#github-app-repositories)

Would it make sense to add support for this in the GitHub `EventSource`?

**Describe the solution you'd like**
I would imagine the `EventSource`, besides using `apiToken`, would allow for something like:

```yaml
githubApp:
  privateKey: 
     name: k8s-app-private-key
     key: secret
  installationId: <>
  appId: <>
```

**Describe alternatives you've considered**
Another alternative could be to support using ssh keys instead of API tokens which would allow us to use non personal ([deploy keys](https://docs.github.com/en/developers/overview/managing-deploy-keys)). This is also supported by [argocd](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#ssh-repositories)

**Additional context**
More on [GitHub apps](https://docs.github.com/en/developers/apps)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by daniel-codefresh** [comment]
@whynowy Heres the related PR: #1438
