### ISSUE TITLE
Replace NATS Streaming

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1389]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
NATS Streaming is EOF, replace with something like JetStream?

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by cawfeecoder** [comment]
@whynowy Any hard dates on when this is expected since it seems to have slipped from Q4 2021? I'm most interested in being able to use the Jetstream Consumer semantics (for durable subscriptions, not unlike something like Kafka).

**Comment by alexec** [comment]
@whynowy this is in 2022-Q1 milestone, but I'm not sure you're resourced to do this work?

**Comment by whynowy** [comment]
TLS and Encryption at rest need to be supported as well.

https://docs.nats.io/running-a-nats-service/nats_admin/jetstream_admin/encryption_at_rest
