### ISSUE TITLE
Pub/Sub event source sometimes hangs when startup fails

### ISSUE THREAD

**Issue by lacarvalho91** [argoproj/argo-events#1401]
**Describe the bug**
The event source will just hang indefinitely on a particular error during startup. I believe the error occurs when trying to connect to the event bus (I think that is what `stan` is). Please see below logs for the particular error:
```json
{"level":"error","ts":1635527217.7099214,"logger":"argo-events.eventsource","caller":"driver/nats.go:115","msg":"Failed to connect to NATS streaming server","eventSourceName":"deployment-notifications-source","clientID":"client-deployment-notifications-source-eventsource-7k658-65d6888bjdxfl-304","error":"stan: connect request timeout (possibly wrong cluster ID?)","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).Connect\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:115\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:325\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:107\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4-rc.0/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4-rc.0/pkg/util/wait/wait.go:399\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:324\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:303"}
{"level":"error","ts":1635527217.7100012,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:328","msg":"failed to connect to eventbus","eventSourceName":"deployment-notifications-source","error":"timed out waiting for the condition: stan: connect request timeout (possibly wrong cluster ID?)","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:328\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:303"}
{"level":"error","ts":1635527217.7100437,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:304","msg":"failed to start","eventSourceName":"deployment-notifications-source","error":"timed out waiting for the condition: stan: connect request timeout (possibly wrong cluster ID?)","stacktrace":"github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).Start.func1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:304"}
{"level":"info","ts":1635527314.1715555,"logger":"argo-events.eventsource","caller":"leaderelection/leaderelection.go:151","msg":"exiting...","eventSourceName":"deployment-notifications-source"}
```

I'm not sure if this problem is specific to the Pub/Sub event source or if its a general event source problem.

The first error in those logs: `Failed to connect to NATS streaming server` sometimes happens when this problem doesn't occur so I think that one can probably be ignored although I have left it in there just in case. But every time I see the `imed out waiting for the condition: stan: connect request timeout (possibly wrong cluster ID?)` error, it is guaranteed to get stuck.

**To Reproduce**
I am seeing this when installing a Helm chart that contains both an event bus and a Pub/Sub event source. I haven't been able to consistently reproduce it yet. I am spawning a minikube instance and then installing some Helm charts. These charts are Argo Events itself, Pub/Sub emulator and an application chart that contains the event source and an event bus. I will keep trying to consistently reproduce the problem and will populate the below if I can.

**Expected behavior**
I expect the event source to be able to recover. Either the pod should die and a new one is spawned, or the event source keeps trying to connect until it is able to.

**Environment (please complete the following information):**
 - Kubernetes: v1.21.2 (via minikube 1.22.0)
 - Argo: v3.1.8
 - Argo Events: v1.5.0

**Additional context**
I'm pretty sure this is to do with timing, as I mentioned I am applying an event bus and the event source as part of the same Helm chart so I believe this happens when the event source tries to connect to the event bus when the event bus is in a particular state whilst booting up. Could be wrong of course.

If I kill the event source pod, it starts back up fine and works.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Same issue as https://github.com/argoproj/argo-events/issues/1396.
