### ISSUE TITLE
Latency metrics are incomplete

### ISSUE THREAD

**Issue by bygui86** [argoproj/argo-events#1410]
**Describe the bug**
[In the documentation](https://argoproj.github.io/argo-events/metrics/#golden-signals) "Golden signals" metrics are describe and it seems they are really useful, but latency metrics histograms are incomplete as they provide `count`, `sum` but `NO BUCKETS`. Additionally `sum` is always zero. Here an example extracted directly by metrics:
```
argo_events_event_processing_duration_milliseconds_sum{event_name="gitlab-go-event",eventsource_name="sbt",namespace="argo-events"} 0
argo_events_event_processing_duration_milliseconds_count{event_name="gitlab-go-event",eventsource_name="sbt",namespace="argo-events"} 11
argo_events_event_processing_duration_milliseconds_sum{event_name="http-tool-event",eventsource_name="sbt",namespace="argo-events"} 0
argo_events_event_processing_duration_milliseconds_count{event_name="http-tool-event",eventsource_name="sbt",namespace="argo-events"} 2
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy ArgoEvents
2. Deploy Prometheus using the operator
3. Expose metrics to Prometheus using `ServiceMonitor`
4. Open Prometheus UI
5. Look for `argo_events_event_processing_duration_milliseconds` or `argo_events_action_duration_milliseconds`
6. See that no `bucket` is presented in the autocompiling and `sum` is always zero.

Looking for metrics directly from controllers on port 7777 provides the very same result.

**Expected behavior**
I expect to have following exposed metrics:
- argo_events_event_processing_duration_milliseconds_bucket{le=...}
- argo_events_event_processing_duration_milliseconds_sum
- argo_events_event_processing_duration_milliseconds_count
- argo_events_action_duration_milliseconds_bucket{le=...}
- argo_events_action_duration_milliseconds_sum
- argo_events_action_duration_milliseconds_count

I expect also that `argo_events_event_processing_duration_milliseconds_sum` and `argo_events_action_duration_milliseconds_sum` are different than zero.

**Screenshots**
Missing `bucket` and `sum` equals to zero directly from controller
<img width="1644" alt="Screenshot 2021-11-04 at 21 42 35" src="https://user-images.githubusercontent.com/22518997/140417207-441f59d6-1f87-46f1-bddf-d49c238e50b1.png">

Missing `bucket` in Prometheus
<img width="1669" alt="Screenshot 2021-11-04 at 21 43 26" src="https://user-images.githubusercontent.com/22518997/140417304-83986524-9552-46e3-9347-c9388ee94de6.png">

`sum` equals to zero in Prometheus
<img width="1669" alt="Screenshot 2021-11-04 at 21 43 15" src="https://user-images.githubusercontent.com/22518997/140417177-973ac9a1-a58e-49ce-ad24-7fcb800c189f.png">

**Environment (please complete the following information):**
 - Kubernetes:   v1.19.12-gke.2100
 - Argo:   v3.1.3
 - Argo Events:   v1.4.0

**Additional context**
- Running in a GKE private cluster with internet connection through Cloud NAT.
- NetworkPolicies enabled but well configured

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by bygui86** [comment]
Together with @whynowy I tried another time to reproduce this and I was successful :)
Actually latency metrics are not histograms, but plain counters that combines could give an idea of punctual latency.
Closing issue.

**Comment by cloudw** [comment]
I'm running into the same issue where `argo_events_event_processing_duration_milliseconds_sum` is always zero. Was there a resolution?
