### ISSUE TITLE
Support HDFS Gateway

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-events#142]
**Is your feature request related to a problem? Please describe.**

My company uses HDFS w/ Kerberos auth as a storage for artifacts and want to use it easily in argo-events.

**Describe the solution you'd like**

Create the HDFS gateway.

**Describe alternatives you've considered**

Create a custom gateway image by ourselves and specify it in `deploySpec`.

**Additional context**

I'm creating it for my company by myself, but I don't know if I should create a PR to the upstream or just create another repository for the gateway to share it publicly. HDFS is a quite common storage, but adding every common gateway implementation in the upstream may increase the effort of maintenance. So may I have your opinion?

**Comment by VaibhavPage** [comment]
HDFS custom gateway would be great have. I think, for now, we can add HDFS gateway to upstream and if we feel managing custom gateways is getting out of hand, we can move them a separate repo.

**Comment by VaibhavPage** [comment]
I wrote this document to help get started with custom gateways - https://github.com/argoproj/argo-events/blob/docs-on-custom-gateways/docs/write-core-gateway.md

**Comment by dtaniwaki** [comment]
I was going to implement it with cheap events like file appeared or disappeared by polling file paths, however, I found there's [a better and appropriate solution](https://issues.apache.org/jira/browse/HDFS-6634) to achieve this although it needs root privilege to subscribe events. I will find a way to make it available with Kerberos authorization.

**Comment by VaibhavPage** [comment]
with v0.7 release, refactored gateway architecture is in place.

**Comment by dtaniwaki** [comment]
I started to work on this.
