### ISSUE TITLE
Support for bitbucket cloud as an eventsource

### ISSUE THREAD

**Issue by RixTmobilender** [argoproj/argo-events#1426]
**Is your feature request related to a problem? Please describe.**
There is currently no first-class support for bitbucket **cloud** as an event source. Only for the [soon to be deprecated](https://www.atlassian.com/migration/assess/journey-to-cloud) **server** version.

**Describe the solution you'd like**
First-class support of bitbucket cloud as an eventsource.

**Describe alternatives you've considered**
Implementing the generic "webhook" event source but I'd like to avoid this as I'd require to use an external tool (probably terraform) to be able to automatically manage webhooks as opposed to from within argo events, which would be ideal.

**Additional context**
[Bitbucket cloud's REST API](https://developer.atlassian.com/cloud/bitbucket/rest/intro/)
There is a stale PR on this subject that never got merged https://github.com/argoproj/argo-events/pull/917

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
We already have bitbucket server eventsource but missing documents for it, just created an issue for [tracking](https://github.com/argoproj/argo-events/issues/1443).

Would you like to contribute on the bitbucket cloud eventsource? @RixTmobilender

**Comment by daniel-codefresh** [comment]
@whynowy I'll do it  👍  I'm assigning this one to myself

**Comment by daniel-codefresh** [comment]
Related PR: #1493
