### ISSUE TITLE
Add annotations to Webhook Gateway

### ISSUE THREAD

**Issue by janvdvegt** [argoproj/argo-events#143]
We are using Ambassador as API gateway and we are now using Argo events to trigger workflows via the webhook. Ambassador uses annotations on services to configure them, allowing developers to determine their endpoints themselves. To be able to use this in the Gateway definition we would have to be able to pass Annotations specifically for the Service created by the Gateway. This is similar to https://github.com/argoproj/argo-events/issues/125 I think but I'm not sure if applying this solution to this issue is the best option. An alternative would be to just add a field that allows you to define annotations to things other than the Gateway itself. The only alternatives at the moment are either creating an additional service linking to the Webhook Gateway or manually adding the Annotations after it is live, both of them seem hacky.

**Comment by VaibhavPage** [comment]
this is added in v0.7
