### ISSUE TITLE
quickstart.html installation instructions outdated

### ISSUE THREAD

**Issue by chriszs** [argoproj/argo-events#144]
**Describe the bug**
`https://argoproj.github.io/docs/argo-events/docs/quickstart.html` instructions no longer reflect the project organization.

**To reproduce**
1. Open [quickstart.html](https://argoproj.github.io/docs/argo-events/docs/quickstart.html)
2. Try running `kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/guides/hack/k8s/manifests/argo-events-sa.yaml` or any of the other apply commands, as per the instructions
3. Then try running `kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml` to install argo in the argo-events namespace

**Expected behavior**
Both complete without errors. Argo Events is installed.

**Observed behavior**
Step 2 results in `error: unable to read URL "https://raw.githubusercontent.com/argoproj/argo-events/guides/hack/k8s/manifests/sensor-controller-deployment.yaml", server reported 404 Not Found, status code=404` and step 3 results in error `the namespace from the provided object "argo" does not match the namespace "argo-events". You must pass '--namespace=argo' to perform this operation.`

**Comment by magaldima** [comment]
@VaibhavPage can this be closed?

**Comment by VaibhavPage** [comment]
yup.
