### ISSUE TITLE
Filter issues

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1449]
1. the [Filter documentation](https://github.com/argoproj/argo-events/blob/master/docs/tutorials/07-filters.md#multiple-paths):
    - is really incomplete
    - examples are too simple (it would be good to have a real example based for example on GitHub and GitLab events)
    - should have a dedicated section and not be placed only under "tutorials", as imo it's a really important feature of Argo Events
2. I suggest to add an option to change the evaluation process of the list of filters and conditions under each filter, offering possibility to specify if evaluated in `AND` or in `OR`, because:
    - there is no option to have multiple conditions under a filter evaluated in `OR`. I'm forced to create multiple sensors, increasing complexity (more yaml manifests) and costs of maintainability and resources in the cluster (more sensors = more resource consumption)
    - `Multiple paths` could fast become really complex and it's completely not flexible as `Expr` (see examples of differences below)
    - declaring or-conditions in `Multiple paths` is complex and limited, because based on regex

The Filter doc is really incomplete because:
- Nowhere is documented that "the list of filters is evaluated in AND condition"
- Nowhere is documented that "the list of conditions under a filter is evaluated in AND condition"
- There are **4** types of filter, not 3. `Expr filter` is completely missing and it's one of the most important and flexible
- Data filter Multiple path example is not really clear and probably wrong
- There is no clear example for Context filter (like for Data filter)
- There is no clear example for Time filter (like for Data filter)
- There is no real examples or use case, for example filtering an event coming from GitHub or GitLab webhook

"Data filter Multiple paths" is not comparable to "Expr filter", for example:
- declaring multiple conditions within a regex becomes fast really complex and error prone
- declaring something like `b != ""` is not so easy together with other conditions
- it's not possible to declare conditions in `||` (OR)
- it's not possible to declare a condition like `b > 2.5` as number or `b == true` as bool
- no "Parenthesis to control order of evaluation" available (based on https://github.com/Knetic/govaluate)
- no "Arrays" available (based on https://github.com/Knetic/govaluate)
For these reasons (and others I didn't list), I don't consider "Data filter Multiple paths" a valid alternative to "Expr filter". And for sure also not a valid, easy, fast alternative to have conditions under a filter evaluated in `OR`.

@bygui86

**Comment by bygui86** [comment]
@whynowy great issue. This is mainly to improve the documentation of one of the most important feature of ArgoEvents in my opinion :)

**Comment by bygui86** [comment]
@whynowy I will work very soon to improve doc and improve "filter" feature :)
