### ISSUE TITLE
Sensor error state recovery not working

### ISSUE THREAD

**Issue by janvdvegt** [argoproj/argo-events#145]
After the webhook sensor goes into error state due to a faulty payload, it claims to have updated the sensor succesfully but it's not starting anymore workflows on the endpoint. I was using a JSON payload but passing it wrongly from my script. Before running the script, via Postman everything was working. After running the faulty script, the sensor is not working via Postman anymore either.

To reproduce:

Set up a gateway with webhook sensor, pass the wrong JSON payload (in this case I sent it as plain text), let it go to error state and then proper requests also will not work anymore.

After making a faulty call, I expect the sensor to still process proper requests.

Here is the relevant parts:

Endpoint for /build-model:

port: "12000"
endpoint: "/build-model"
method: "POST"

Signal in sensor spec:

    "signals": [
      {
        "name": params.gatewayName + '/build-model'
      }
    ],

Triggers:

          "parameters": [
            {
              "src": {
                "signal": params.gatewayName + '/build-model',
                "path": "new-docker-image"
              },
              "dest": "spec.arguments.parameters.0.value"
            },
            {
              "src": {
                "signal": params.gatewayName + '/build-model',
                "path": "git-url"
              },
              "dest": "spec.arguments.parameters.1.value"
            },

Arguments in source:

    arguments:
      parameters:
      - name: new-docker-image
        value: ShouldBeOverwritten
      - name: git-url
        value: ShouldBeOverwritten

Envs in container:

      - name: NEW_DOCKER_IMAGE
        value: \"{{inputs.parameters.new-docker-image}}\"
      - name: GIT_URL
        value: \"{{inputs.parameters.git-url}}\"

**Comment by VaibhavPage** [comment]
closing this issue for now, let me know if you are still facing the issue.
