### ISSUE TITLE
Multiple repository support for Bitbucketserver Event Sources

### ISSUE THREAD

**Issue by serainville** [argoproj/argo-events#1452]
**Is your feature request related to a problem? Please describe.**
Environments with a large number of Bitibucket repositories require an equal number of bitbucketserver event sources. There should not be a  1:1 relationship with Bitbucket repositories and an event source.

**Describe the solution you'd like**
The Bitbucketserver event source should be modelled after the Gitlab and Github event sources, which permit events from any number of projects or repos. Also, management of a Bitbucket repository's webhook should be optional.  Not all environments permit Bitbucket webhooks to be managed by Argo Events.

Simplify the event source to accept events from a Bitbucket server for any project or repository, with optional authorization support using webhook secrets

**Describe alternatives you've considered**
There are no alternatives for Bitbucket Webhooks where HMAC is required for workflow authorization.

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by daniel-codefresh** [comment]
@serainville @whynowy Related PR: #1540
