### ISSUE TITLE
Sensor trigger type http is not recognized (Workflow)

### ISSUE THREAD

**Issue by jackivanov** [argoproj/argo-events#1464]
**Describe the bug**
I'm trying to invoke an http workflow template, but Sensor fails
- https://argoproj.github.io/argo-workflows/http-template/

**To Reproduce**
1. Create a sensor with template trigger http
2. Send an event
3. Watch sensor fails

**Expected behavior**
Sensor invokes http

**Environment (please complete the following information):**
 - Argo Workflows: 3.2.4
 - Argo Events: 1.5.4

**Additional context**
```
time="2021-12-10T16:56:53.845Z" level=fatal msg="Failed to parse workflow: json: unknown field \"http\""
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
> 

The `argo` cli embedded in argo-events binary needs to be upgraded as that is a new feature from workflows. You can switch to use `k8s` trigger to do it, and change the operation to `create`.
