### ISSUE TITLE
Refactor gateways

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#147]
**Is your feature request related to a problem? **
Currently the framework offers different flavors of gateway like `core`, `http` and `grpc` that an user can implement. But this has lead to bloated implementation and in case of `http` and `grpc` gateways, framework needs to add `middleware` components that can talk over different communication protocols.  

**Describe the solution you'd like**
Communication between framework and user's gateway code should happen only over gRPC.
This will standardize how gateways are implemented and it will make code easy to maintain.
Also it will be easier to manage state of the event sources.

**Comment by VaibhavPage** [comment]
@magaldima @spk83 @dtaniwaki thoughts?

**Comment by dtaniwaki** [comment]
@VaibhavPage I agree with you. That reduces lots of redundant code and simplifies gateways. 👍
