### ISSUE TITLE
Bug: Pod logs does not appear if namespace is not selected 

### ISSUE THREAD

**Issue by xi2817-aajgaonkar** [argoproj/argo-events#1488]
**Describe the bug**

**BUG**
Logs of the sensor, event source pod does not appear if the namespace is not selected

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.18.6]
 - Argo: [e.g. v2.9.4]
 - Argo Events: [e.g. v1.0.0]

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Could you give more detail?
