### ISSUE TITLE
Missing `all` target in the `Makefile`

### ISSUE THREAD

**Issue by bygui86** [argoproj/argo-events#1489]
**Describe the bug**
I tried to follow the "Developer Guide" in [this link](https://argoproj.github.io/argo-events/developer_guide/) but in the `Makefile` there is no `all` target :(

**Expected behaviour**
Have a target named `all` in the `Makefile` or change the "Developer Guide" to have clear instructions.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Updated the doc
