### ISSUE TITLE
amqp start.go method StartConfig never calls listenEvents

### ISSUE THREAD

**Issue by Jmast** [argoproj/argo-events#149]
**Describe the bug**
amqp gateway does not listen for events as it seems to be missing the line:

	go ce.listenEvents(t, config)

in StartConfig method of start.go

**To Reproduce**
deploy the amqp example in version 0.6

**Expected behavior**
submitting a message to the amqp exchange should trigger sensor

**Comment by VaibhavPage** [comment]
#148

**Comment by VaibhavPage** [comment]
can you try v0.7?

**Comment by Jmast** [comment]
Tried v0.7 and amqp gateway triggers events now. thx.
