### ISSUE TITLE
Introduce event transform functionality

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#1491]
**Is your feature request related to a problem? Please describe.**
Before an event from a dep could be passed to filters, add the ability for users to apply transformations to that event using a Lua script & JQ.

**Describe the solution you'd like**
Add `Transform` field to EventDependency

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by hamza3202** [comment]
When is this feature planned to be released?
