### ISSUE TITLE
Kafka source - make partition optional

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1502]
https://github.com/argoproj/argo-events/blob/master/api/event-source.md#kafkaeventsource shows partition as mandatory, it should be optional

**Comment by whynowy** [comment]
@tooptoop4 - could you make the change?

**Comment by tooptoop4** [comment]
although https://github.com/argoproj/argo-events/blob/master/examples/event-sources/kafka.yaml#L28 seems to say its optional
