### ISSUE TITLE
Support container security context for event bus

### ISSUE THREAD

**Issue by hamza3202** [argoproj/argo-events#1509]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to set container security context for event bus deployments. This prevents users from specifying settings like `allowPrivilegeEscalation: false`. 
Our corporate kubernetes cluster does not allow to deploy pods without specifying this field.

**Describe the solution you'd like**
[Container Template](https://github.com/argoproj/argo-events/blob/master/api/event-bus.md#containertemplate) should allow specifying security context as well

**Describe alternatives you've considered**
The alternative is to run argo events without container security context which is less secure.

**Additional context**
None

---
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
It's supported to set it in pod level, do you really need to set it in container level?

**Comment by hamza3202** [comment]
@whynowy the PR is up #1519
