### ISSUE TITLE
Documentation for usage of Argo Rollouts trigger source is lacking

### ISSUE THREAD

**Issue by mrobinson-wavehq** [argoproj/argo-events#1510]
**Describe the bug**
Documentation for usage of Argo Rollouts trigger source is lacking

**To Reproduce**
N/A

**Expected behavior**
It appears that support for Argo Rollouts as a trigger source was added [here](https://github.com/argoproj/argo-events/commit/d0d11e4e85e94efe2d2c6946c1939e660b3ab45d#diff-9a62b4a044185786fb1bf1c5a2ea3d0d94c2e168d1ed580db8994c06a4f0f41aR45). There is very brief mention of it in the documentation as a [trigger type](https://argoproj.github.io/argo-events/concepts/trigger/#trigger-types), however that's the last time it's mentioned. If such support does exist, would it be possible to update the documentation to include a usage example?

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by aweis89** [comment]
Seems like this is no longer on the master branch?
