### ISSUE TITLE
Event Structure from NATS event source does not contain subject and body

### ISSUE THREAD

**Issue by aleksey005** [argoproj/argo-events#1517]
**Describe the bug**
Event Structure from NATS event source does not contain subject and body.

**To Reproduce**
1. Follow the steps in the instruction https://argoproj.github.io/argo-events/eventsources/setup/nats/
2. nats cli:
`nats pub foo '{"message": "hello"}'`
3. See error Event Structure does not contain:
`         "subject": "name_of_the_nats_subject",
          "body": "message_payload"`
logs:
` _________________________________________
/ {"context":{"id":"39636232316635652d613 \
| 931392d346234622d623234652d326335643235 |
| 343737326230","source":"nats","specvers |
| ion":"1.0","type":"nats","datacontentty |
| pe":"application/json","subject":"event |
| -create","time":"2022-01-12T20:18:28Z"} |
| ,"data":"eyJzdWJqZWN0IjoicHJlZ2FwIiwiYm |
\ 9keSI6eyJtZXNzYWdlIjoiaGVsbG8ifX0="}    /
 -----------------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
`

**Expected behavior**
Having a decoded json messages from NATS

**Screenshots**
![image](https://user-images.githubusercontent.com/6145279/149218735-8f483a3e-068d-4f21-8487-26bbe01bdb2d.png)
![image](https://user-images.githubusercontent.com/6145279/149218826-42ca936e-74a2-4e5e-9d7d-03172e99e90c.png)



**Environment (please complete the following information):**
 - Kubernetes: v1.22.7
 - Argo: v3.2.6
 - Argo Events: v1.5.0

**Additional context**
helm installation
---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
You are looking at the raw message, which has a base64 encoded `data` field.

When you use `parameters` feature, if you specify `dataKey`, they will be decoded.

**Comment by aleksey005** [comment]
It would be nice if the documentation had an example of this usage.

**Comment by whynowy** [comment]
Check if this helps https://github.com/argoproj/argo-events/blob/master/docs/tutorials/02-parameterization.md

**Comment by aleksey005** [comment]
> Check if this helps https://github.com/argoproj/argo-events/blob/master/docs/tutorials/02-parameterization.md

Thanks!

**Comment by aleksey005** [comment]
Everything worked out
 ____________
< Thank You! >
 ------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
