### ISSUE TITLE
github's webhook does not send messages properly 

### ISSUE THREAD

**Issue by wenchajun** [argoproj/argo-events#1526]
**Describe the bug**
Hello, everyone. I'm having a problem configuring argo-events, can anyone help me? I configured argo-events on k3s, but the results were not so satisfactory.Every pod is working fine without any error messages, so I don't know which part is wrong. I configured the gitHub webhook and also tried pushing the code. But the troubling thing is that it has not been possible to send a message.The error message is `We couldn’t deliver this payload: EOF`.

```
root@i-k5d6x5d6:~# kubectl get deploy -n argo-events
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
sensor-controller          1/1     1            1           16d
events-webhook             1/1     1            1           16d
eventsource-controller     1/1     1            1           16d
eventbus-controller        1/1     1            1           16d
github-sensor-lbvdp        0/1     0            0           20h
github-eventsource-tnpmv   1/1     1            1           3h43m

```
**To Reproduce**
I have read the document carefully, but I'm still not sure what I've missed, so I'd be grateful if you could help me point it out.
1.  kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/v1.5.4/manifests/install.yaml
2.  kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/v1.5.4/manifests/install-validating-webhook.yaml
3.  kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/v1.5.4/examples/eventbus/native.yaml
4. create secret
```
apiVersion: v1
kind: Secret
metadata:
  name: github-access
type: Opaque
data:
  token: <base64-encoded-api-token-from-previous-step>
```

**Expected behavior**
Github sends messages normally

**Environment (please complete the following information):**
 - Kubernetes: v1.20.11+k3s2

 - Argo Events: 1.5.4

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
You need to get it running in a cluster which could set up an ingress or LB, so that github can access the eventsource to push events.

**Comment by wenchajun** [comment]
Thanks very much。
