### ISSUE TITLE
Rewrite Amazon SNS, SQS and GCP Pub Sub gateway

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#154]
**Is your feature request related to a problem? Please describe.**
The implementation of these gateways are stale and need to refactor some code due to #147  

Existing implementation https://github.com/argoproj/argo-events/tree/amazon-sns-gateway

**Comment by creatorrr** [comment]
Is PR #100 still active?

https://github.com/argoproj/argo-events/pull/100#issuecomment-459986502

**Comment by VaibhavPage** [comment]
No. that PR isn't active. Its just there for reference. The gateway architecture and couple other things got refactored which rendered the work on PR stale. If you want to contribute, have a stab at it.

**Comment by magaldima** [comment]
#169 was merged to master and includes the AWS SNS gateway. I wanna try and tackle the GCP pub sub gateway..

**Comment by VaibhavPage** [comment]
I will implement SQS gateway.

**Comment by VaibhavPage** [comment]
#192
