### ISSUE TITLE
Workflow image run by sensor changes on the hour

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1541]
I'm using latest version. I create sqs event source and sensor. i have 3 replicas of all argo things like controllers, eventbus.etc. it is 7.30pm, my sensor is triggering a workflow with image 0.0.2, then around 7.40pm i re-deploy my sensor but this time triggering a workflow with image 0.0.3, everything is fine (ie image 0.0.3) between 7.42pm-7.59pm but then from 8pm onwards the sensor starts triggering image 0.0.2 again!

**Comment by whynowy** [comment]
I don't quite understand, could you give more detail? If you can tell us how to reproduce it, that would be better.

**Comment by tooptoop4** [comment]
could this be related to running multiple replicas of argo workflow controller?

**Comment by tooptoop4** [comment]
@whynowy I changed my sensor yaml 13h ago but it seems not all the 3 pods were updated, as you can see there is older sensor from 47h ago. looking at each of the 3 sensor pods, i see the SENSOR_OBJECT env variable is the same on the 2 13hago pods but different on the 47h ago one. Then when i look at some workflows that run, some show different manifest contents (my sensor definition before vs after 47h ago). do u think revisionHistoryLimit=0 should be set?

old:
"uid":"cd285e3e-35a6-46df-b6e6-56e76ffe60ed","resourceVersion":"18006277","generation":6,"creationTimestamp":"2022-02-20T10:13:31Z"
new:
"uid":"262e3dfb-0dd5-4851-9abb-ff2267275ed0","resourceVersion":"18049951","generation":5,"creationTimestamp":"2022-02-20T12:04:35Z"
 

```
k get po -A | grep -E 'sqs|workf'
auth                   argo-workflows-server-596f6b76f-f6ns2                 1/1     Running     1          3d9h
auth                   argo-workflows-server-596f6b76f-ftngf                 1/1     Running     0          3d6h
auth                   argo-workflows-server-596f6b76f-tbptr                 1/1     Running     5          3d6h
auth                   argo-workflows-workflow-controller-6584b56f87-4skbc   1/1     Running     0          33h
auth                   aws-sqs-eventsource-2nxbt-56d57688fb-npv92            1/1     Running     0          3d9h
auth                   aws-sqs-eventsource-bxkxg-56d57688fb-9xjmh            1/1     Running     3          3d6h
auth                   aws-sqs-eventsource-xwqtd-56d57688fb-n26bb            1/1     Running     2          3d6h
auth                   aws-sqs-sensor-fbs82-d69b84745-zz4kq                  1/1     Running     6          13h
auth                   aws-sqs-sensor-kzfp9-7c87f5574d-bpxvs                 1/1     Running     24         47h
auth                   aws-sqs-sensor-x9c99-d69b84745-m8nnr                  1/1     Running     7          13h
```

**Comment by whynowy** [comment]
Can you check your sensor object status field to see if there's any error?
