### ISSUE TITLE
conditions reset does not work if the service is down at the triggering time.

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1543]
[Conditions Reset](https://github.com/argoproj/argo-events/blob/master/docs/sensors/trigger-conditions.md#conditions-reset) is a feature for multi dependency triggers to reset the conditions with a cron like schedule. It runs a timer to send a reset signal when the time comes, which will not work if the sensor service is down at the time.

A possible solution to address the issue would be, utilize the message timestamp to compare with the last reset timestamp to see if it is good.

**Comment by juliev0** [comment]
I can look at this.

**Comment by juliev0** [comment]
PR here: https://github.com/argoproj/argo-events/pull/1585
