### ISSUE TITLE
Controllers HA

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1565]
Make the controller(s) HA.

"k8s.io/client-go/tools/leaderelection"

**Comment by gavinmead** [comment]
I'm looking to contribute to the project and I'd be happy to help out on this issue.  Looking at https://github.com/argoproj/argo-events/blob/4cbce31101739d9c5e33a25ee62bae9dd4655e76/controllers/eventsource/cmd/start.go#L43 were you going add the LeaderElection options that are supported by the controller-runtime Manager to the controller Options on https://github.com/argoproj/argo-events/blob/4cbce31101739d9c5e33a25ee62bae9dd4655e76/controllers/eventsource/cmd/start.go#L36

**Comment by whynowy** [comment]
> I'm looking to contribute to the project and I'd be happy to help out on this issue. Looking at
> 
> https://github.com/argoproj/argo-events/blob/4cbce31101739d9c5e33a25ee62bae9dd4655e76/controllers/eventsource/cmd/start.go#L43
> 
> were you going add the LeaderElection options that are supported by the controller-runtime Manager to the controller Options on
> https://github.com/argoproj/argo-events/blob/4cbce31101739d9c5e33a25ee62bae9dd4655e76/controllers/eventsource/cmd/start.go#L36

@gavinmead - Welcome! leader election option provided by controller-runtime works, looking forward to seeing your PR!
