### ISSUE TITLE
Update `github.com/slack-go/slack` to latest

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-events#1612]
dependabot needs some help from a human to update slack-go as there are some break changes in the recent release.

See https://github.com/argoproj/argo-events/pull/1587 for which tests failed. 

--

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by mintbomb27** [comment]
Hey! Can I take this up?

**Comment by whynowy** [comment]
@mintbomb27 - sure, thanks!
