### ISSUE TITLE
Eventsource filtering modifies the filter expression at runtime -> doesn't work as expected

### ISSUE THREAD

**Issue by signaleleven** [argoproj/argo-events#1667]
**Describe the bug**
The new EventSource filtering feature modifies the filters at runtime (replacing `-` with `_` in values), making it impossible (at least to my knowledge) to apply filters for values containing `-`.

**To Reproduce**
1. Create an Event Source with a filter like this
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kafka-eventsource-test
spec:
  kafka:  
    my-test-event:
[...]
       expression: "(body.someUUIDfield == '7e577e57-7e57-7e57-7e57-7e577e577e57')"
```
2. Write a message on the kafka topic (but I suppose this is the same for other eventsources) like this one
```json
{ "_id": "whatever",
  "someUUIDfield": "7e577e57-7e57-7e57-7e57-7e577e577e57"
 }
```
3. Check the Eventsource logs: the event is received but NOT published on the eventbus (filtered)
4. Write a message on the kafka topic like this one (note the `_` instead of `-`)
```json
{ "_id": "whatever",
  "someUUIDfield": "7e577e57_7e57_7e57_7e57_7e577e577e57"
 }
```
5. Check the Eventsource logs: the event is received AND published on the eventbus (not filtered) despite clearly NOT matching the filter.

**Expected behavior**
The filter expression is applied as written, instead of being modified.

**Environment (please complete the following information):**
 - Kubernetes: v1.22
 - Argo Events: v1.6.0

**Additional context**
The reason for this (and for my very specific procedure to reproduce above) is most likely this line:
https://github.com/argoproj/argo-events/blob/df18152bb54cd55573990f69c1dfad60a645dedf/eventsources/eventing.go#L568

I see that the filters are processed to turn `-`s into `_`s. I assume that was done for a reason*, but I can imagine filtering for string values containing - can be important. It is important to me at least 😄  And I cannot figure out how to do it. 

*: @dpadhiar can you comment on this? Maybe you only meant to do this for the keys, not for the values, in order to fit the pairs into a map? I'm neither a go nor an expr expert, so I'm just thinking out loud... btw, **thank you** for this feature, it got merged pretty much on the day I realized I needed it (Sensor filters is ok functionally, but my metrics sampled on the eventsources are wrong, as they count events that then get filtered by the sensor. Your feature solves my problem, minus this bug)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
We should not do string replacement on expressions for this reason . Users should just do `parameter["foo"]` if they need to do it.

@whynowy @dpadhiar can we fix this please?

**Comment by dpadhiar** [comment]
> 

Yes, will go ahead and remove `strings.ReplaceAll(filter.Expression, "-", "_")` from line 568.
