### ISSUE TITLE
Getting Started failed

### ISSUE THREAD

**Issue by better629** [argoproj/argo-events#1676]
**Describe the bug**
Run the commands under the <Getting Started>，but can't create workflow

[root@k8s-master argo-events-test]# kubectl -n argo-events logs workflow/webhook-2hrtr
error: no kind "Workflow" is registered for version "argoproj.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
[root@k8s-master argo-events-test]# kubectl -n argo-events logs Sensor/webhook
error: no kind "Sensor" is registered for version "argoproj.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

[root@k8s-master argo-events-test]# kubectl -n argo-events get workflow
NAME            STATUS   AGE
webhook-2hrtr
webhook-dctkc

**To Reproduce**
1. Run the commands under the <Getting Started>
4. See error before

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: v1.20.4
 - Argo: [quay.io/argoproj/argocli:latest]
 - Argo Events: [1.5.5]

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Need to install workflows. https://github.com/argoproj/argo-workflows/blob/master/docs/quick-start.md#install-argo-workflows

**Comment by better629** [comment]
If I install argo-events in namespace argo( with argo-workflows), `Getting Started` can run success and creates event-flow.
Is there a namespace problem ?

**Comment by whynowy** [comment]
@better629 - do you still have a problem?

**Comment by better629** [comment]
@whynowy I will have a check with your suggestion. Maybe the argo-workflows installed by others not in the namespaces way.
