### ISSUE TITLE
Make EventBus AckWait configurable

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1680]
In debugging https://github.com/argoproj/argo-events/issues/1547 ("stan: publish ack timeout") i came across https://github.com/nats-io/nats-streaming-server/issues/958#issuecomment-546408655, one of the suggestions is "the server was not able to respond within the publisher's ack wait"

Below shows that its 1 second -->
https://github.com/argoproj/argo-events/blob/v1.6.0/eventbus/driver/nats.go#L155
```		stan.AckWait(1*time.Second), ```

**Comment by juliev0** [comment]
So, I believe the comment you linked to and your #1547 refer to the NATS server acking the publisher (EventSource) within its wait time, while the code [line](https://github.com/argoproj/argo-events/blob/v1.6.0/eventbus/driver/nats.go#L155 ) you found refers to the timeout for the consumer (Sensor) to ack the NATS server. 

It doesn't appear to me that we're explicitly setting the AckWait for the publisher. If I'm reading it correctly, I think the default [value](https://github.com/nats-io/stan.go/blob/main/stan.go#L215) in their code is 30 seconds.
