### ISSUE TITLE
Release 1.6.0 breaks AMQP event source and loses messages

### ISSUE THREAD

**Issue by pdaBlueVoyant** [argoproj/argo-events#1694]
**Describe the bug**
We recently upgraded from 1.5.6 to 1.6.0 and found that several messages are getting lost in the event bus.  We have confirmed via logs that all the queued messages appear in the event source, but 4 out of 5 never make it to the event sensor.

We use a RabbitMQ (amqp) event source.  The loss happens when we queue 5 messages at about the same time.  I noticed some changes to EventBus and EventSource (forget which) involved timestamps and the NATS event bus and wonder if there is a problem when events come in that have more-or-less identical time stamps.  Our setup uses several event source bindings to different queues.  Not sure that is important as problem happens using just 1 of the queues.  Things work fine if we send messages 1 at time (human speed).

**To Reproduce**
Steps to reproduce the behavior (rough outline):
1. Set up an event source using AMQP and and event sensor to process things.
2. Queue a bunch of messages into RabbitMQ quickly (we could repro this w/ 5 messages at once)
3. Notice only 1 message is processed; the others are lost (bad, very bad)

**Expected behavior**
Every message that is sent to a Rabbit MQ queue that is bound to an event source should be processed.

**Environment (please complete the following information):**
 - Kubernetes: 1.21.5
 - Argo: 3.3.0 rc6
 - Argo Events: 1.6.0

**Additional context**
We backed out EventSensor and EventBus components to use 1.5.6 and everything worked fine.  We kept EventSource at 1.6.0 as we require the newly released feature for quorum queues (made by one of my teammates and I).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by tooptoop4** [comment]
@pdaBlueVoyant do you have logs like https://github.com/argoproj/argo-events/issues/1547 ?

**Comment by pdaBlueVoyant** [comment]
No, the EventSource logs were clean.  There were no errors, if I recall.  There were 5 log messages in Event source, one for each queued message.  Looking for the corresponding logs in Event sensor, there were no errors, just 1 message instead of 5.  I will try to dig up the logs and post them...will most likely take until tomorrow.

**Comment by juliev0** [comment]
@pdaBlueVoyant Additional logging was added to the Sensor recently, so if at all possible getting DEBUG level logs for the Sensor would be really helpful. 

`
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
          `

**Comment by pdaBlueVoyant** [comment]
Here is a sample of the logs messages (filtered as we put all the data into Splunk and then use queries to find things). 

Things I observed:

1. all the messages were processed by the event source in a 100ms period ("ts" field is xxx.417 - xxx.324)
2. only the first message put on the event bus by the event source is processed (corresponding eventID)

our event source filtered by "succeeded to publish an event" (sorted newest at top, oldest at bottom):

`{"level":"info","ts":1646144705.4172847,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:512","msg":"succeeded to publish an event","eventSourceName":"alert-connector-amqp","eventName":"splunk","eventSourceType":"amqp","eventID":"64653930643766302d346436652d346430352d623931392d636139633763323361306466"}
{"level":"info","ts":1646144705.4122727,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:512","msg":"succeeded to publish an event","eventSourceName":"alert-connector-amqp","eventName":"splunk","eventSourceType":"amqp","eventID":"39306330613338382d353738362d343936342d386662612d346361653132613635363438"}
{"level":"info","ts":1646144705.3658261,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:512","msg":"succeeded to publish an event","eventSourceName":"alert-connector-amqp","eventName":"splunk","eventSourceType":"amqp","eventID":"66386132663938372d623534662d343531642d396236322d333565353432343131636138"}
{"level":"info","ts":1646144705.3519535,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:512","msg":"succeeded to publish an event","eventSourceName":"alert-connector-amqp","eventName":"splunk","eventSourceType":"amqp","eventID":"31313766326264642d323635372d343365322d616539632d646163323234323931383534"}
{"level":"info","ts":1646144705.324787,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:512","msg":"succeeded to publish an event","eventSourceName":"alert-connector-amqp","eventName":"splunk","eventSourceType":"amqp","eventID":"64643063313161662d303832352d346439622d616235302d663163653234316236633838"}
`

The corresponding event sensor for the same time range.  Note, there is only 1 eventID processed:
`
{"level":"info","ts":1646144705.3423674,"logger":"argo-events.sensor","caller":"sensors/listener.go:416","msg":"successfully processed the trigger","sensorName":"amqp-sensor-splunk","triggerName":"alert-workflow-trigger","triggerType":"Kubernetes","triggeredBy":["splunk-dep"],"triggeredByEvents":["64643063313161662d303832352d346439622d616235302d663163653234316236633838"]}
{"level":"info","ts":1646144705.326676,"logger":"argo-events.sensor","caller":"standard-k8s/standard-k8s.go:159","msg":"creating the object...","sensorName":"amqp-sensor-splunk","triggerName":"alert-workflow-trigger","triggerType":"Kubernetes"}
`

**Comment by pdaBlueVoyant** [comment]
I had tried to add the DEBUG_LOG: "true" to our deployment.  It may not have worked.  My syntax looks like this for a helm deployment:

sensorController:
  image: argo-events
  tag: {{ .Values.argoEventsSensorTag }}
  replicaCount: 1
  sensorImage: argo-events
  extraEnv:
    - name: DEBUG_LOG
      value: "true"

**Comment by tooptoop4** [comment]
could this be the cause? https://github.com/argoproj/argo-events/pull/1523

**Comment by juliev0** [comment]
@pdaBlueVoyant Thanks for doing this. Is your _value: "true_" aligned underneath _name_?

For reference, my Sensor which uses debug logs is defined like this:

> piVersion: argoproj.io/v1alpha1
> kind: Sensor
> 
> metadata:
>   name: webhook-f
> spec:
>   template:
>     serviceAccountName: operate-workflow-sa
>     container:
>       env:
>         - name: DEBUG_LOG
>            value: "true"  <-- ugh, trying to get this to align underneath name here but it isn't
>   
>   dependencies:
>   ...

**Comment by pdaBlueVoyant** [comment]
I wondered about #1523. It was one of the changes I had looked at when we first noticed this problem.  I don't know enough about the NATS system or what that code is trying to do to really say that is the problem.  I looked at some changes from mid-Jan and found several that used "time" in some way.  Certainly if the messages are lost from the NATS event bus, there will be trouble.  I don't recall the other changes you mention, but can look deeper tomorrow.

**Comment by pdaBlueVoyant** [comment]
yeah, posting here lost all my formatting from the YAML.  the alignment is fine.  That env variable did not make it into our alert sensor code for the pod generated from the "event sensor" YAML.  I may need to add something to that code.  The DEBUG_LOG is set for the controllers.

**Comment by pdaBlueVoyant** [comment]
I'm going to add the DEBUG_LOG to our sensor code.  I see where it should go now.  Thanks.  I'll post more logs tomorrow as I backed out the revisions so we could continue our development.

**Comment by juliev0** [comment]
Also, if you have a spec for EventSource, EventBus, and Sensor, I can try testing with those specifically.

**Comment by pdaBlueVoyant** [comment]
our specs are all looped via helm/helmfile variables.  I might be able to extract a simplified version in the morning if the logs do not show the problem.

**Comment by juliev0** [comment]
I believe I may have reproduced this and found root cause. I'm curious if your debug log will show this line: "reset and acked dependency=test-dep-a due to message time occurred before reset". 

This is the line: https://github.com/argoproj/argo-events/blob/master/eventbus/driver/nats.go#L263

The issue is that the comparison being done is comparing the new message time to the previous message time, and the comparison is on the seconds level and not the microseconds level. I will work on the fix.

**Comment by pdaBlueVoyant** [comment]
Sweet!  I'll grab logs and confirm in the AM.  Thanks!

**Comment by pdaBlueVoyant** [comment]
OK, I'm impatient.  I confirmed the log message you mentioned.  2 out of 5 messages were processed and I have 3 occurrences of this:

`2022-03-02T00:18:24.672Z	DEBUG	argo-events.sensor	driver/nats.go:269	reset and acked dependency=splunk-dep due to message time occurred before reset, m.Timestamp=1646180304664277028, msgHolder.getLastResetTime()=1646180304	{"sensorName": "amqp-sensor-splunk", "triggerName": "alert-workflow-trigger", "clientID": "client-3933758907-34"}`

**Comment by juliev0** [comment]
haha, thank you @pdaBlueVoyant !

**Comment by whynowy** [comment]
@pdaBlueVoyant - just released v1.6.2 with the fix, can you verify if you still see the issue? Thanks @juliev0 for the quick fix!

**Comment by pdaBlueVoyant** [comment]
Better, but I still get message loss.  This time I sent 10 and 6 were processed and 4 generated that message "due to message time occurred before reset".  Is there another way to handle these message bus acks?  Timestamps are problematic with concurrent events as 2 distinct events can appear at, what appears to be, the exact same time.

**Comment by juliev0** [comment]
That's odd that that would occur with the time comparison now being on the nanosecond level. Can you please provide all of your logs including eventsource and sensor?

**Comment by pdaBlueVoyant** [comment]
Coming soon...Wed is my heavy meeting day.

**Comment by pdaBlueVoyant** [comment]
I have not enabled DEBUG logs on the event source; I can do that and rerun if you like.  The source log shows 10 messages received and sent to event bus.  Sensor logs have Debug on
[EventSource.03.02.txt](https://github.com/argoproj/argo-events/files/8171321/EventSource.03.02.txt)
[EventSensor.03.02.txt](https://github.com/argoproj/argo-events/files/8171322/EventSensor.03.02.txt)
.

**Comment by juliev0** [comment]
Thank you!

**Comment by juliev0** [comment]
Okay, there are two fixes I'm thinking of:
1. This would be a quick fix and should take care of any cases in which the messages are received in-order by the sensor, which I would think would be the majority of the time. I noticed that the if statement is not actually comparing a publish time to a publish time (lastResetTime is a receive time), so changing that to be a publish time to compare apples to apples. The PR is [here](https://github.com/argoproj/argo-events/pull/1701/files).
2. This would be more involved and not be a time comparison.

**Comment by juliev0** [comment]
Regarding my quick fix, it might be sufficient after all, since NATS apparently does guarantee that messages are received in order for a given publisher. We are going to build an image consisting of this PR for you to try out if you don't mind.

**Comment by juliev0** [comment]
@pdaBlueVoyant Could I bother you when you have time to try using this image: [gcr.io/whynowy/argo-events:v1.6.3-rc1](http://gcr.io/whynowy/argo-events:v1.6.3-rc1) ? This contains that pull request. 

Really appreciate your time!

**Comment by whynowy** [comment]
> @pdaBlueVoyant Could I bother you when you have time to try using this image: [gcr.io/whynowy/argo-events:v1.6.3-rc1](http://gcr.io/whynowy/argo-events:v1.6.3-rc1) ? This contains that pull request.
> 
> Really appreciate your time!

@pdaBlueVoyant - in case you are not familiar, the say to update the sensor image is updating the ENV `SENSOR_IMAGE` in `sensor-controller`


```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-controller
  namespace: argo-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-controller
  template:
    metadata:
      labels:
        app: sensor-controller
    spec:
      containers:
      - args:
        - sensor-controller
        env:
        - name: SENSOR_IMAGE
          value: gcr.io/whynowy/argo-events:v1.6.3-rc1
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

**Comment by pdaBlueVoyant** [comment]
We use a different mechanism for deployments (helm + helmfile).  I can translate the image path and version to what you have here.  Worst case I can attempt to deploy what you sent directly.  Not sure it will happen tonight (I'm at the end of my day), but I'll put it together for tomorrow.  At some point, I may ask you for hints on how to do local builds and deployments as there are some features I'm thinking about relating to RabbitMQ that we might want (and others too).

I appreciate the fast turnaround and am more than happy to help get this fixed.  We have about a week before we want to move to production and I would like to use version 1.6.x of all 3 components (we require the Event Source to be at 1.6+).  Things appear to work using lower versions of the Bus and Sensor, but I would not want to run that way for very long.

**Comment by pdaBlueVoyant** [comment]
@juliev0 That image worked great.  I was able to edit the deployment using k9s (easiest path).  Thanks again for the quick attention on this.  I tested with a 10 and a 30 message burst.  all messages were processed.

**Comment by whynowy** [comment]
@pdaBlueVoyant - Thank you very much for the help! 

@juliev0 - Great work!

**Comment by juliev0** [comment]
Excellent. Thanks for helping to test it. I am going to do some additional testing today for other cases - if those all work, we'll merge it in.

**Comment by pdaBlueVoyant** [comment]
In the next week (or so) we should start testing with some higher peak loads to simulate our production system.   Historically, we've seen 60K messages come in very fast.  We have other mechanisms (queues, k8 limits) to absorb that load, but we do want to handle about 10 messages/sec.

**Comment by whynowy** [comment]
@pdaBlueVoyant - nice, please keep us updated, thanks.

**Comment by daniel-codefresh** [comment]
@whynowy @juliev0 Guys I suggest to update our `stable` tag to v1.6.3 asap because it is still pointing to v1.6.1 before the fix and people are using it and still having this issue.

**Comment by whynowy** [comment]
> @whynowy @juliev0 Guys I suggest to update our `stable` tag to v1.6.3 asap because it is still pointing to v1.6.1 before the fix and people are using it and still having this issue.

thanks! updated.

**Comment by whynowy** [comment]
> @daniel-codefresh they also face #1748

We will do a new patch release in this week.

**Comment by tooptoop4** [comment]
gentle ping ^

**Comment by eriadam** [comment]
Hello! Any chance this would also make to the helm chart? It is still the version 1.6.0 in there.
https://artifacthub.io/packages/helm/argo/argo-events

**Comment by wsams** [comment]
> Hello! Any chance this would also make to the helm chart? It is still the version 1.6.0 in there. https://artifacthub.io/packages/helm/argo/argo-events

You can override the image tag @eriadam .
```
sensorController:
  tag: v1.6.3
eventsourceController:
  tag: v1.6.3
eventbusController:
  tag: v1.6.3
  ```

**Comment by eriadam** [comment]
@wsams Yes, thank you, I did that.
