### ISSUE TITLE
Bitbucketserver webhook's webhookSecret not enforced

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1710]
BitbucketServer webhook has configuration for webhook secret https://github.com/argoproj/argo-events/blob/master/examples/event-sources/bitbucketserver.yaml#L80 that should check that calls to the webhook have that secret value passed in (ie which should align to the secret that bitbucket itself sends, image below)

![image](https://user-images.githubusercontent.com/33283496/156887105-40ea5949-4bbf-41b7-b2fa-3904f76c928e.png)

But the issue is the webhook is still accepting the request when no  webhook secret is sent (ie via an unauthenticated curl request)
cc @daniel-codefresh 
https://github.com/argoproj/argo-events/issues/891#issuecomment-1059769853

**Comment by tooptoop4** [comment]
@svmaris any idea? one thing i notice is that the webhookSecret block from the yaml does not get persisted:

![image](https://user-images.githubusercontent.com/33283496/165430784-25efa610-9722-4a06-9acc-4d4e90bd8a34.png)

**Comment by daniel-codefresh** [comment]
Related PRs: #1917 #1902
