### ISSUE TITLE
Argo-events cannot run using official instances

### ISSUE THREAD

**Issue by LingClassmate** [argoproj/argo-events#1713]
Argo-workflow is installed, events are installed, and can be triggered when a Webhook is executed, but Workflow is not running.

**Argo-workflow and events Install the normal**
[root@k8s-master01 ~]# kubectl get pod -n argo 
NAME                                  READY   STATUS    RESTARTS   AGE
argo-server-6fc6f65bf5-zwzcn          1/1     Running   14         20d
minio-fb98dbfdd-vjtmb                 1/1     Running   7          20d
postgres-6b5c55f477-s54dz             1/1     Running   7          20d
workflow-controller-64444886d-b2h2s   1/1     Running   30         20d

[root@k8s-master01 ~]# kubectl get pod -n argo-events
NAME                                         READY   STATUS    RESTARTS   AGE
eventbus-controller-5bdbdb9f6c-ddmzp         1/1     Running   0          4d
eventbus-default-stan-0                      2/2     Running   0          3d23h
eventbus-default-stan-1                      2/2     Running   0          3d23h
eventbus-default-stan-2                      2/2     Running   0          3d23h
eventsource-controller-75676d88d-t6hqz       1/1     Running   0          4d
sensor-controller-755f794f68-h9zhz           1/1     Running   0          4d
webhook-eventsource-h668q-659db857d4-c9j6p   1/1     Running   0          6h16m
webhook-sensor-qbrpr-6d78d867db-n87vs        1/1     Running   0          5h31m

**webhook Out of order**
[root@k8s-master01 ~]# argo list -n argo-events
NAME            STATUS    AGE   DURATION   PRIORITY
webhook-mvhhz   Pending   5h    0s         0

[root@k8s-master01 ~]# argo -n argo-events watch webhook-mvhhz
Name:                webhook-mvhhz
Namespace:           argo-events
ServiceAccount:      default
Status:              Pending
Created:             Mon Mar 07 15:37:22 +0800 (5 hours ago)
Progress:            
Parameters:          
  message:           {"message":"this is my first webhook"}

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/

**Comment by shuker85** [comment]
can you do `kubectl describe pod webhook-mvhhz` ?

**Comment by juliev0** [comment]
Seeing the Workflow in "Pending" state: Possibly the Workflow isn't visible to the Workflow controller, which could happen if the Workflow is installed in namespace scope rather than cluster scope.  See [this](https://github.com/argoproj/argo-workflows/blob/master/docs/managed-namespace.md) link.

**Comment by juliev0** [comment]
Can you please attach your yaml files? There's a suspicion that the Controller may not see the Workflow if it's in a different namespace, and maybe that's why it's stuck in "Pending". Is the Workflow installed in cluster scope? See here: https://github.com/argoproj/argo-workflows/blob/master/docs/managed-namespace.md

**Comment by LingClassmate** [comment]
> Can you please attach your yaml files? There's a suspicion that the Controller may not see the Workflow if it's in a different namespace, and maybe that's why it's stuck in "Pending". Is the Workflow Controller installed in cluster scope? See here: https://github.com/argoproj/argo-workflows/blob/master/docs/managed-namespace.md

Argo Workflow and events is a workmanlike workmanlike workmanlike workmanlike workmanlike workflow.
You didn't change anything, you just installed it.

`[root@k8s-master01 workflow]# kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml`

Argo events installation：
https://argoproj.github.io/argo-events/installation/

Argo Events Webhook also runs directly with the official YAML：
`kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/webhook.yaml`
`kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/webhook.yaml`

**Comment by juliev0** [comment]
Right, so it looks like your Workflow was deployed in the "argo-events" namespace, while the Workflow Controller is in the "argo" namespace, so the Controller can't see the Workflow. That's why it's stuck in "Pending". The easiest change to make would be to just install everything in one namespace. 

Sorry for the confusion and we can look into clarifying the documentation.

**Comment by LingClassmate** [comment]
> Right, so it looks like your Workflow was deployed in the "argo-events" namespace, while the Workflow Controller is in the "argo" namespace, so the Controller can't see the Workflow. That's why it's stuck in "Pending". The easiest change to make would be to just install everything in one namespace.
> 
> Sorry for the confusion and we can look into clarifying the documentation.

Thank you very much! Argo Events and Workflow are installed in the same namespace as you said.
However, I have a question. How to solve the problem if Argo Events is installed under the `argo-events` namespace?

**Comment by whynowy** [comment]
Install both Argo Events and Workflows in cluster scope.

**Comment by LingClassmate** [comment]
> 

Is there a relevant tutorial?

**Comment by juliev0** [comment]
So, if you look at https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml you'll see there's a workflow-controller Deployment in there. Within there you'll see that spec.container.args contains a line which says "--namespaced". I believe if you take that line out, then the Workflow Controller should be able to look for workflows in all namespaces rather than just the "argo" namespace. If that doesn't work let me know and I'll check it on my side.

**Comment by whynowy** [comment]
@LingClassmate - do you still have trouble?

**Comment by LingClassmate** [comment]
@whynowy I am sorry that I have been too busy these two days. I will try it later. Now I have installed Argo Workflow and Events in the same namespace and they can work normally.

**Comment by LingClassmate** [comment]
@juliev0 
I followed your instructions and removed "--namespaced", but I created the Workflow test and found it didn't work.

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        #- --namespaced
        ...
`
Test workflow：
`apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
  - name: whalesay              # name of the template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
`
I created a Hello Workflow test and found the following error

Cannot read properties of undefined (reading 'undefined')
 Reload this page to try again.

Stack Trace
TypeError: Cannot read properties of undefined (reading 'undefined')
    at t.WorkflowLogsViewer (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:240:76616)
    at $i (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:52993)
    at Io (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:65197)
    at qa (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:90552)
    at Ga (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:90936)
    at Os (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:97823)
    at Ls (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:97203)
    at Rs (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:98578)
    at Tn (https://192.168.101.91:15466/main.569c1241a90daae8ab70.js:531:30569)
Component Stack

    in Unknown
    in div
    in div
    in div
    in Unknown
    in div
    in div
    in Unknown
    in Unknown
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in t
    in Unknown
    in t

**Comment by LingClassmate** [comment]
@juliev0 
**Workflow - Controller dies after a while**

time="2022-03-19T07:45:15.893Z" level=info msg="Watch configmaps 403"
E0319 07:45:15.893582       1 retrywatcher.go:130] "Watch failed" err="unknown (get configmaps)"
time="2022-03-19T07:45:16.894Z" level=info msg="Watch configmaps 403"
E0319 07:45:16.894625       1 retrywatcher.go:130] "Watch failed" err="unknown (get configmaps)"
time="2022-03-19T07:45:17.763Z" level=info msg="List pods 403"
W0319 07:45:17.764146       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "pods" in API group "" at the cluster scope
E0319 07:45:17.764231       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:argo:argo" cannot list resource "pods" in API group "" at the cluster scope
time="2022-03-19T07:45:17.894Z" level=info msg="Watch configmaps 403"
E0319 07:45:17.894542       1 retrywatcher.go:130] "Watch failed" err="unknown (get configmaps)"
time="2022-03-19T07:45:18.150Z" level=info msg="Get leases 200"
time="2022-03-19T07:45:18.155Z" level=info msg="Update leases 200"
time="2022-03-19T07:45:18.586Z" level=info msg="List workflows 403"
time="2022-03-19T07:45:18.586Z" level=info msg=healthz age=5m0s err="workflows.argoproj.io is forbidden: User \"system:serviceaccount:argo:argo\" cannot list resource \"workflows\" in API group \"argoproj.io\" at the cluster scope" instanceID= labelSelector="!workflows.argoproj.io/phase,!workflows.argoproj.io/controller-instanceid" managedNamespace=

**Comment by juliev0** [comment]
Sorry about that @LingClassmate. I guess adding "--namespaced" to quick-start-postgres.yaml isn't sufficient, because the appropriate Roles/RoleBindings, and ServiceAccounts are now also in there to allow the Controller to perform these actions cluster-wide.

Instead of using quick-start-postgres.yaml, please try the instructions that are listed under "Quick Start" on the Argo Workflows Github [page](https://github.com/argoproj/argo-workflows):
_kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/install.yaml_

This deploys the Workflow Controller in the appropriate cluster-scope configuration but also with the accompanying Roles/RoleBindings, and ServiceAccounts. 

Let us know if you have any issues with that. (Or of course also don't feel like you have to do this for us if your priorities have changed, and don't feel that you have to do it immediately.) :)

**Comment by LingClassmate** [comment]
Thank you very much for your active answer to my question @juliev0 I tried "Quick Start" on the Github page of Argo workflow
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/install.yaml

I put before the quick - start - postgres. Yaml uninstalled, direct execution the yaml found no.
Only argo-Server and Workflow-Controller Pods were created, and minio and Postgres Pods were not created.

If YOU open Argo UI, there is a mistake. Is my understanding wrong? Please kindly advise, thank you.
