### ISSUE TITLE
Trigger stopped receiving messages

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1727]
**Describe the bug**
A rare case that a trigger stopped receiving events, which turned out that nats streaming stopped delivering messages to that specific durable queue group.

This is confirmed by checking eventBus (Nats Streaming) monitoring endpoint (the ClusterIP service exposed by EventBus), if doing port-forward that service with port 8222, and then check the endpoint below:

http://localhost:8222/streaming/channelsz?channel=eventbus-${namespace}&subs=1

Within this page, all the eventbus subscription info can be found. To find the subscription for that particular sensor, need to go to Sensor Pod log to find the auto-generated queue group first. For example, following log shows the queue group for the trigger subscription is "**client-1538775570**". 

```
{"level":"info","ts":1646974019.2970517,"logger":"argo-events.sensor","caller":"driver/nats.go:169","msg":"starting ExactOnce cache clean up daemon ...","sensorName":"s-uipbppemrsetup-tidalmigrationdemo3","triggerName":"upstream-deps","clientID":"client-1538775570-66"}
```

Then search "client-1538775570" in the subscription page, check the `last_sent` field, it remains unchanged while new messages keep coming from event sources.

```
    {
      "client_id": "client-3074556577-32",
      "inbox": "_INBOX.fgnZlzF5wmOBNmRR72dv6u",
      "ack_inbox": "_INBOX.ERtL7zbGKRoR4QDU1GsjYl",
      "queue_name": "client-3074556577:client-3074556577",
      "is_durable": true,
      "is_offline": true,
      "max_inflight": 17,
      "ack_wait": 1,
      "last_sent": 83220383,
      "pending_count": 0,
      "is_stalled": false
    },
```

**To Reproduce**
Can not find a way to reproduce.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Checked the Nats community (https://natsio.slack.com/archives/C3KB6SGM8/p1646713224245689), there's no response on this issue.

**Comment by whynowy** [comment]
One more notable thing around the time this issue happened was, the EventBus Pods were restarted due to k8s node upgrade, and before that, those pods had been running in a high memory pressure (hitting mem up limit) for more than 20 days, not sure if that was related.

**Comment by csimplestring** [comment]
same issue experienced +1

**Comment by nettrino** [comment]
Have been seeing a similar issue with 
```
RequestCanceled: request context canceled
caused by: context canceled
```

for eventName s3-triggered-queue with a stacktrace of 
```
github.com/argoproj/argo-events/eventsources/sources/awssqs.(*EventListener).StartListening
	/home/runner/work/argo-events/argo-events/eventsources/sources/awssqs/start.go:105
github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3.1
	/home/runner/work/argo-events/argo-events/eventsources/eventing.go:536
github.com/argoproj/argo-events/common.DoWithRetry.func1
	/home/runner/work/argo-events/argo-events/common/retry.go:106
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/util/wait/wait.go:145
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.29.2/pkg/util/wait/backoff.go:461
github.com/argoproj/argo-events/common.DoWithRetry
	/home/runner/work/argo-events/argo-events/common/retry.go:105
github.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3
	/home/runner/work/argo-events/argo-events/eventsources/eventing.go:535
```
