### ISSUE TITLE
Webhook secret should be optional in Bitbucket Server event source

### ISSUE THREAD

**Issue by daniel-codefresh** [argoproj/argo-events#1743]
**Describe the bug**
ATM, the Bitbucket Server event source requires a webhook secret. Although this field is optional in the event source specification, validation fails if the secret is not provided by the user. This validation rule should be removed and also the code needs to be modified to support the creation of webhooks without a webhook secret.

**Expected behavior**
Webhook secret field should be optional, as Bitbucket Server supports creation of webhooks without webhook secrets.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by tooptoop4** [comment]
https://github.com/argoproj/argo-events/issues/1710 also related
