### ISSUE TITLE
Eventsource is not reaching to the bitbucket 

### ISSUE THREAD

**Issue by swathi-zelarsoft** [argoproj/argo-events#1784]
**Describe the bug**
Trying to create an eventsource for bitbucket repo but its not triggering any webhook for the repo

**Expected behavior**
Sensor has to listen to bitbucket changes

**Screenshots**
{
  "level": "error",
  "ts": 1648638760.9694889,
  "logger": "argo-events.eventsource",
  "caller": "bitbucket/start.go:240",
  "msg": "failed to create new webhook",
  "eventSourceName": "bitbucket",
  "eventSourceType": "bitbucket",
  "eventName": "evtsource",
  "error": "400 Bad Request",
  "stacktrace": "github.com/argoproj/argo-events/eventsources/sources/bitbucket.(*Router).saveBitbucketWebhook\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/bitbucket/start.go:240\ngithub.com/argoproj/argo-events/eventsources/sources/bitbucket.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/bitbucket/start.go:164\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3.1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:469\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:107\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.7-rc.0/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.7-rc.0/pkg/util/wait/wait.go:399\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:468"
}

-------------

{
  "level": "error",
  "ts": 1648638760.9697628,
  "logger": "argo-events.eventsource",
  "caller": "bitbucket/start.go:166",
  "msg": "failed to save Bitbucket webhook",
  "eventSourceName": "bitbucket",
  "eventSourceType": "bitbucket",
  "eventName": "evtsource",
  "error": "failed to create new webhook: 400 Bad Request",
  "errorVerbose": "400 Bad Request\nfailed to create new webhook\ngithub.com/argoproj/argo-events/eventsources/sources/bitbucket.(*Router).saveBitbucketWebhook\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/bitbucket/start.go:241\ngithub.com/argoproj/argo-events/eventsources/sources/bitbucket.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/bitbucket/start.go:164\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3.1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:469\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:107\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.7-rc.0/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.7-rc.0/pkg/util/wait/wait.go:399\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:468\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581",
  "stacktrace": "github.com/argoproj/argo-events/eventsources/sources/bitbucket.(*EventListener).StartListening\n\t/home/runner/work/argo-events/argo-events/eventsources/sources/bitbucket/start.go:166\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3.1\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:469\ngithub.com/argoproj/argo-events/common.Connect.func1\n\t/home/runner/work/argo-events/argo-events/common/retry.go:107\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.7-rc.0/pkg/util/wait/wait.go:211\nk8s.io/apimachinery/pkg/util/wait.ExponentialBackoff\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.21.7-rc.0/pkg/util/wait/wait.go:399\ngithub.com/argoproj/argo-events/common.Connect\n\t/home/runner/work/argo-events/argo-events/common/retry.go:106\ngithub.com/argoproj/argo-events/eventsources.(*EventSourceAdaptor).run.func3\n\t/home/runner/work/argo-events/argo-events/eventsources/eventing.go:468"
}
**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.18.6]
 - Argo: [v3.3.1]
 - Argo Events: [v1.6.0]

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by daniel-codefresh** [comment]
Hey @swathi-zelarsoft ! Could you please provide a screenshot of your EventSource manifest? Also, which auth strategy are you using? Is it Basic Auth or OAuth? 
This issue might have to do with insufficient permissions granted to your token/password. You can refer to the first step in the [Setup section](https://argoproj.github.io/argo-events/eventsources/setup/bitbucket/#setup) of the Bitbucket EventSource documentation to see which permissions must be granted for the EventSource to work as expected.

**Comment by swathi-zelarsoft** [comment]
Hi @daniel-codefresh I used Basic-Auth strategy but I’m unable to connect to bitbucket. I tried the same way for Github, it worked fine.
Coming to EventSource.yaml I used the example one in the github with my details(https://github.com/argoproj/argo-events/blob/master/examples/event-sources/bitbucket.yaml).  Here providing the screenshot of EventSource yaml. Could you please let me where I'm going wrong. Thank you
![image](https://user-images.githubusercontent.com/82637337/165681730-83d93667-b543-4464-8b83-c18db7f66d99.png)

**Comment by swathi-zelarsoft** [comment]
It got worked when I created a new repo and implemented the Basic-Auth strategy. Thank you @daniel-codefresh

**Comment by daniel-codefresh** [comment]
> It got worked when I created a new repo and implemented the Basic-Auth strategy. Thank you @daniel-codefresh

Sure thing!
