### ISSUE TITLE
Jetstream - User should not be able to change Jetstream Stream settings if Sensor/EventSource are attached

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-events#1793]
Since there is just one Stream we can't allow the changing of the Stream Settings once EventSources and Sensors are already using it with the original stream settings.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
In fact, even if all EventSources and Sensors get deleted, once that EventBus has been used even once the stream Settings are in there. You need to delete the EventBus and create a new one. So, maybe we can prevent updating that setting altogether?

**Comment by whynowy** [comment]
> In fact, even if all EventSources and Sensors get deleted, once that EventBus has been used even once the stream Settings are in there, and we won't create a new stream with new settings. You need to delete the EventBus and create a new one. So, maybe we can prevent updating that setting altogether?

Only allow delete -> create then.

**Comment by juliev0** [comment]
@whynowy Do you mean not allow "update" at all for the Jetstream bus then?

**Comment by whynowy** [comment]
> @whynowy Do you mean not allow "update" at all for the Jetstream bus then?

Well, take back what I said, we should only prevent updating several fields.
