### ISSUE TITLE
FMEA testing for Jetstream 

### ISSUE THREAD

**Issue by juliev0** [argoproj/argo-events#1799]
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
Document to keep track of this: https://docs.google.com/document/d/1VVACEHOugs67-a6MPxSKOCk8_uT0cePv4k_6zqygniI/edit#

**Comment by juliev0** [comment]
@whynowy I believe I am done with this, if you want to close it.

**Comment by whynowy** [comment]
@juliev0 - This is great! Can you also post the result as a comment in the issue, and then we can close it.

**Comment by juliev0** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-7dc19937-7fff-db8b-a898-1e5246fef2f7"><h2 dir="ltr" style="line-height:1.5;margin-top:18pt;margin-bottom:12pt;padding:0pt 0pt 5.1pt 0pt;"></h2><div dir="ltr" style="margin-left:0pt;" align="left">

Disruption | How to test | Result
-- | -- | --
Controller Pod deleted | Kubectl delete pod | Restarted successfully.
EventSource Pod deleted | Kubectl delete pod | For 2 pods in active/active, one gets deleted and restarts, connects to jetstream. For 2 pods in active/standby, standby node is able to take over as leader.
Sensor Pod deleted | Kubectl delete pod | If leader is deleted, other pod takes over as leader. Transition is seamless. Verified that new leader can take over on a partially fulfilled conditional expression.
Eventbus Pod Deleted - since a given pod could be a Stream leader, Meta leader, consumer leader, or KV stream leader, I have a script which randomly kills 10 jetstream pods in a row. Then verify subscription still works. | Kubectl delete pod | Performed 10 Jetstream pod deletions in a row. Verified that Sensor pod could continue to subscribe afterward and maintained current state
Controller offline | Scale down to 0 and then back up | If events such as EventSource deletion and creation occur while Controller is down, after it comes back up it is able to perform Reconcile().
EventSource POD offline | Scale down to 0 and then back up | Scales back up and reconnects to Jetstream.
Sensor POD offline | same | Once scaled back up the leader is able to receive any messages it missed, and use the same k/v store as before.
EventBus offline | same | Sensor pod tried to reconnect and couldn’t. Other pod claimed role as leader and first pod restarted as replica. Verified new Sensor was able to pick up where the other one left off, making use of K/V store and original subscription.
Sensor object deleted/recreated | Kubectl delete sensor; kubectl apply -f | No issues with recreation; durable consumer picks up where it left off
EventBus object delete/recreate | Kubectl delete eventbus; kubectl apply -f | Controller does not delete the EventBus if it has EventSource or Sensor connected
EventBus object updated | Try changing the most frequently changed settings. | version: with EventSource and Sensor attached: gradually updated each pod one by one to get new imagesettings: nats-js.conf changes, which the pods notice and reloadpersistence: controller says “updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden". -streamConfig: If Stream has been used at all, any change will get ignored. Need to prevent changing these settings. Issue 1793
Malformed EventBus spec | experiment with different settings | version: results in EventBus having an undeployed Status and failure message. replicas: Admission Controller denies if < 3streamConfig: free form text so allows anything-settings/startArgs: free form text, so we don’t do any validation; eventbus pod will fail if it restartsIssue 1849: It’s possible to configure Jetstream storage > PVC size

</div></b>Disruption
How to test
Result
Controller Pod deleted
Kubectl delete pod
Restarted successfully. 
EventSource Pod deleted
Kubectl delete pod
For 2 pods in active/active, one gets deleted and restarts, connects to jetstream. For 2 pods in active/standby, standby node is able to take over as leader.
Sensor Pod deleted
Kubectl delete pod
If leader is deleted, other pod takes over as leader. Transition is seamless. Verified that new leader can take over on a partially fulfilled conditional expression.
Eventbus Pod Deleted - since a given pod could be a Stream leader, Meta leader, consumer leader, or KV stream leader, I have a script which randomly kills 10 jetstream pods in a row. Then verify subscription still works.
Kubectl delete pod
Performed 10 Jetstream pod deletions in a row. Verified that Sensor pod could continue to subscribe afterward and maintained current state
Controller offline
Scale down to 0 and then back up
If events such as EventSource deletion and creation occur while Controller is down, after it comes back up it is able to perform Reconcile().
EventSource POD offline
Scale down to 0 and then back up
Scales back up and reconnects to Jetstream.
Sensor POD offline
same
Once scaled back up the leader is able to receive any messages it missed, and use the same k/v store as before.
EventBus offline
same
Sensor pod tried to reconnect and couldn’t. Other pod claimed role as leader and first pod restarted as replica. Verified new Sensor was able to pick up where the other one left off, making use of K/V store and original subscription.
Sensor object deleted/recreated
Kubectl delete sensor; kubectl apply -f 


No issues with recreation; durable consumer picks up where it left off
EventBus object delete/recreate
Kubectl delete eventbus; kubectl apply -f 
Controller does not delete the EventBus if it has EventSource or Sensor connected
EventBus object updated
Try changing the most frequently changed settings.
version: with EventSource and Sensor attached: gradually updated each pod one by one to get new image
settings: nats-js.conf changes, which the pods notice and reload
persistence: controller says “updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden". 
-streamConfig: If Stream has been used at all, any change will get ignored. Need to prevent changing these settings. [Issue 1793](https://github.com/argoproj/argo-events/issues/1793)


Malformed EventBus spec
experiment with different settings
version: results in EventBus having an undeployed Status and failure message. 
replicas: Admission Controller denies if < 3
streamConfig: free form text so allows anything
-settings/startArgs: free form text, so we don’t do any validation; eventbus pod will fail if it restarts
[Issue 1849](https://github.com/argoproj/argo-events/issues/1849): It’s possible to configure Jetstream storage > PVC size

**Comment by juliev0** [comment]
@whynowy Posted above. Ignore everything below the table itself - for some reason when I pasted the table in from Google Docs it added both the table and the free form content below.

**Comment by juliev0** [comment]
Okay, fixed
