### ISSUE TITLE
Calendar eventsource and invalid workflow spec causes workflow to be resubmitted continuously

### ISSUE THREAD

**Issue by kenoshi** [argoproj/argo-events#1822]
**Describe the bug**
Lets say you have a templated workflow spec that has a empty container image for a step

When it triggers, its an invalid workflow...But this workflow then gets resubmitted over and over till argo workflow controller crashes and you are left with ~15k workflows to delete after an hour...which takes a long time to delete...

This may be a workflow problem, not quite sure...I notice this to be an issue with the calendar eventsource with a schedule of "30 10 * * *"

No retry strategy set
**To Reproduce**
1. Add a calendar event source with a sensor / trigger with an invalid argo workflow spec
2. watch the show...

**Expected behavior**
Workflow to fail and gets triggered the next day

**Screenshots**
<img width="771" alt="image" src="https://user-images.githubusercontent.com/44850164/162127553-c151b07a-2973-4358-b364-572b1aa1ae0a.png">

<img width="696" alt="image" src="https://user-images.githubusercontent.com/44850164/162127651-7cf0deeb-07ea-49d3-acee-09bf06ca1078.png">

**Environment (please complete the following information):**
 - Kubernetes: EKS v1.21
 - Argo: v3.2.9
 - Argo Events: v1.6.0

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@kenoshi - can you check the sensor pod log to see how many workflows were created? I want to see it's a workflow issue or events issue.
