### ISSUE TITLE
Minio example does not produce the desired behaviour

### ISSUE THREAD

**Issue by lambertsbennett** [argoproj/argo-events#1829]
**Describe the bug**
When following the Minio documentation example instead of the file name being printed in whalesay the default arguments "THIS_WILL_BE_REPLACED" is still present.

**To Reproduce**
Install Argo Events in same namespace as Argo Workflows and kubectl apply the Minio examples from here https://argoproj.github.io/argo-events/eventsources/setup/minio/.

**Expected behaviour**
The uploaded filename should appear in the speech bubble above the whale in the container's logs.

**Screenshots**

<img width="429" alt="WhaleSayFail" src="https://user-images.githubusercontent.com/46295426/162589598-673a9bdc-2a83-42d5-8d69-91bab0b99795.png">

**Environment (please complete the following information):**
 - Kubernetes: [v1.21.0]
 - Argo: [v3.1.0-rc4]
 - Argo Events: [latest?]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
@whynowy You can assign this to me and I'll take a look

**Comment by juliev0** [comment]
@lambertsbennett Do you have log files for the EventSource and Sensor that you can post?

**Comment by lambertsbennett** [comment]
Sensor log file [sensor.txt](https://github.com/argoproj/argo-events/files/8466532/sensor.txt)
EventSource log file [eventsource.txt](https://github.com/argoproj/argo-events/files/8466535/eventsource.txt)

Thanks for looking at this!

**Comment by juliev0** [comment]
Thanks for the logs!

**Comment by juliev0** [comment]
So, I can get it to work if I change the Sensor yaml file in the following ways:
1. 'parameters' lined up directly under 'template' (indentation issue)
2. parameters.0.dest field changed to 'k8s.source.resource.spec.templates.0.container.args.0'

But I need to find out if this is good or if my colleague wants a code change instead to make 'spec.templates.0.container.args.0' work.

**Comment by juliev0** [comment]
That last PR I think may be the "right" way to handle it. Will verify tomorrow.
