### ISSUE TITLE
no Gopkg.lock exists

### ISSUE THREAD

**Issue by hideto0710** [argoproj/argo-events#184]
**Describe the bug**
```
$ dep ensure -vendor-only
no Gopkg.lock exists from which to populate vendor/
```
https://github.com/argoproj/argo-events/commit/89897386b74f62c61baf0d5dc320dab6ead67428#diff-bd247e83efc3c45ae9e8c47233249f18

**To Reproduce**
Follow [contributing guide](https://github.com/argoproj/argo-events/blob/master/CONTRIBUTING.md)

**Environment (please complete the following information):**
```
$ go version
go version go1.10.7 darwin/amd64

$ dep version
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```

**Comment by VaibhavPage** [comment]
this is weird, looks like the gopkg.lock was deleted in one of the latest pr. I'll add it back soon.

**Comment by VaibhavPage** [comment]
The file has been added back.
