### ISSUE TITLE
Improve trigger guide

### ISSUE THREAD

**Issue by afoninsky** [argoproj/argo-events#186]
**Is your feature request related to a problem? Please describe.**

According to [trigger-guide.md](https://github.com/argoproj/argo-events/blob/master/docs/trigger-guide.md#what-resource-types-are-supported-out-of-box):

```
What resource types are supported out of box?
- Argo Workflow
- Standard K8s resources
- Gateway
- Sensor
```

But there are only `argo workflow` resources in [examples](https://github.com/argoproj/argo-events/tree/master/examples/sensors) directory and no additional information provided.

Do not get me wrong, `argo workflow` is great but sometimes we don't want to have one more layer of abstraction.

It is not clear for me how to implement custom gateway which not only translates external events into argo but executes gateway-specific action from corresponding triggers.

**Describe the solution you'd like**
Provide examples how to execute `gateway` and `sensor` resources.

**Describe alternatives you've considered**
Use https://stackstorm.com/ instead or create own bicycle from custom tools

**Additional context**
I want to create `telegram` gateway which will receive commands from the chat and send responses. No need to use `argo-workflow` for it as it should have own custom logic (auth, roles etc.)

**Comment by VaibhavPage** [comment]
I understand the problem. I'll update the documentation and examples that will cover your use-case as soon as possible.

**Comment by VaibhavPage** [comment]
hope this helps https://github.com/argoproj/argo-events/blob/update-trigger-guide/docs/trigger-guide.md#what-resource-types-are-supported-out-of-box

**Comment by VaibhavPage** [comment]
#196
