### ISSUE TITLE
Trigger Conditions Tutorial MinIO Branch does not Work as Expected

### ISSUE THREAD

**Issue by lsl-msft** [argoproj/argo-events#1871]
**Describe the bug**
In Trigger Conditions Tutorial, the minio trigger is not working properly.

**To Reproduce**
Follow the [official tutorial link](https://argoproj.github.io/argo-events/tutorials/06-trigger-conditions/) and do:
1. Deploy webhook event source:
`kubectl -n argo-events apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/tutorials/06-trigger-conditions/webhook-event-source.yaml`
2. Deploy minio event source:
`kubectl -n argo-events apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/tutorials/06-trigger-conditions/minio-event-source.yaml`
3. Deploy circuit sensor to demonstrate conditional trigger:
`kubectl -n argo-events apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/tutorials/06-trigger-conditions/sensor-01.yaml`
4. Upload/Delete a file into S3 bucket named `test`.

**Expected behavior**
``` 
 ------
< test >
 ------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

**Screenshots**
(My bucket name is `bucket1` instead of `test` as you can see)
```
 -----------------------------------------
/ {"notification":[{"eventVersion":"2.0", \
| "eventSource":"minio:s3","awsRegion":"" |
| ,"eventTime":"2022-04-21T02:11:05.423Z" |
| ,"eventName":"s3:ObjectCreated:Put","us |
| erIdentity":{"principalId":"lsl"},"requ |
| estParameters":{"principalId":"lsl","re |
| gion":"","sourceIPAddress":"10.240.0.39 |
| "},"responseElements":{"content-length" |
| :"0","x-amz-request-id":"16E7C76E653A74 |
| 78","x-minio-deployment-id":"9c0954e0-b |
| fe3-4bb3-839a-06fc904177da","x-minio-or |
| igin-endpoint":"http://10.240.0.39:9000 |
| "},"s3":{"s3SchemaVersion":"1.0","confi |
| gurationId":"Config","bucket":{"name":" |
| bucket1","ownerIdentity":{"principalId" |
| :"lsl"},"arn":"arn:aws:s3:::bucket1"}," |
| object":{"key":"test.json","size":23274 |
| ,"eTag":"cd6517d9498561a127c9e36d222562 |
| fe","contentType":"application/json","u |
| serMetadata":{"content-type":"applicati |
| on/json"},"sequencer":"16E7C76E65D83078 |
| "}},"source":{"host":"10.240.0.39","por |
| t":"","userAgent":"MinIO (linux; amd64) |
\ minio-go/v7.0.23"}}]}                   /
 -----------------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

**Environment (please complete the following information):**
 - Kubernetes: v1.22.3
 - Argo: v3.3.1
 - Argo Events: v1.12.0

**Additional context**
N/A

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by lsl-msft** [comment]
It should be a simple fixing PR. Just modify `dataKey:s3.bucket.name` into `dataKey: notification.0.s3.bucket.name`. However I have no permission to create branch so I am not able to create fixing PR. I have referenced `contributing guidelines` but did not find rules or guidelines for this.

**Comment by whynowy** [comment]
Fork the repo, create a branch and submit a PR.

**Comment by lsl-msft** [comment]
> Fork the repo, create a branch and submit a PR.

Thanks. Already created fixing PR https://github.com/argoproj/argo-events/pull/1873
