### ISSUE TITLE
Support for submitting from an existing resource on ArgoWorkflow Trigger

### ISSUE THREAD

**Issue by shirou** [argoproj/argo-events#1908]
**Is your feature request related to a problem? Please describe.**

I would like to submit an existing WorkFlow or CronWorkFlow from an Argo Workflow Trigger. Equivalent to this command.

```
argo submit --from cronwf/my-cron-wf
```

**Describe the solution you'd like**

Currently the [submit code](https://github.com/argoproj/argo-events/blob/master/sensors/triggers/argo-workflow/argo-workflow.go#L137) does not appear to have this feature. My idea is to add a `from` field in `template.argoWorkflow` or elsewhere, and if there is a `from` field, add the `from` as an argument to the argo cli instead of loading a temporary file.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by letthefireflieslive** [comment]
Adding [stackoverflow question](https://stackoverflow.com/questions/72163431/how-can-you-trigger-an-existing-workflow-workflow-template-outside-argo-events-t) for reference as well. Thanks for raising this, we need this thing too
