### ISSUE TITLE
accessToken and webhookSecret should be optional in bitbucketserver eventsource

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#1928]
**Describe the bug**
accessToken and webhookSecret are mandatory in the new syntax style of bitbucketserver eventsource

**To Reproduce**
create a bitbucketserver eventsource from examples (https://github.com/argoproj/argo-events/blob/4d1a8011940680a16d79d432c31cc2054c199898/examples/event-sources/bitbucketserver.yaml) but don't include lines 37-46 about accessToken and webhookSecret

**Expected behavior**
the eventsource is able to receive events even though you don't configure accessToken and webhookSecret in yaml

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: 1.21
 - Argowf: 3.3.5
 - Argo Events: 1.7.0

**Additional context**
logs show errors about accessToken and webhookSecret being mandatory inputs

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by daniel-codefresh** [comment]
Hey @tooptoop4, I'm not sure I understand the issue. Could you please provide some more context? It would be very helpful if you could fill the template that we have for new bug reports: https://github.com/argoproj/argo-events/issues/new?assignees=&labels=bug&template=bug_report.md

**Comment by tooptoop4** [comment]
@daniel-codefresh updated

**Comment by daniel-codefresh** [comment]
@tooptoop4 Here's the related PR: https://github.com/argoproj/argo-events/pull/1976
TBH I didn't see any issues with omitting the webhook secret field as [this previous fix](https://github.com/argoproj/argo-events/pull/1902) makes it optional. Also, it seems like the access token field of the bitbucket server eventsource was never really optional from it's early beginning (although it was optional at the yaml level, it was always required by the eventsource logic itself, so omitting it would've always cause errors) so it seems not related to the new syntax at all. 
Anyway, the new PR should fix the access token field issue and make it totally optional.
