### ISSUE TITLE
clean up old sensors

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#2]
We need the ability to clean up resolved/successful sensors after a certain amount of time. Ideally, we also want to keep a record/store of these sensors in an external store like s3,etc... 

This feature should exist as a separate deployment to the `controller`.

**Comment by VaibhavPage** [comment]
do we still need this issue as users will probably run sensor in `repeat` mode

**Comment by VaibhavPage** [comment]
closing as sensors are by default long running
