### ISSUE TITLE
s3 byte limit too low

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#2022]
i saw https://github.com/argoproj/argo-events/blob/a98978a38dfc90299dc805089716ecba8374461a/sensors/artifacts/s3.go#L64 which means can only read data from s3 that is less than 65kb

its also common for logs to be larger than this

**Comment by whynowy** [comment]
hmmm.... we should increase it...

**Comment by VaibhavPage** [comment]
@whynowy  what was the reason to add LimitReader?

**Comment by whynowy** [comment]
> @whynowy what was the reason to add LimitReader?

We had a security audit that we used `ioutil.ReadAll()` in many places which would potentially cause DoS, then I added the limit to all the places, which might have overkilled. See https://github.com/argoproj/argo-events/issues/1946.

**Comment by whynowy** [comment]
@tooptoop4 - did you really experience any issue with this? This one is for reading the workflow spec definition from S3, we of course can increase the limit to 1 MB also, but it does not make sense to make it more than that.

**Comment by tooptoop4** [comment]
yes, my workflow is more than 65kb
