### ISSUE TITLE
Multi source git trigger

### ISSUE THREAD

**Issue by vaimo-magnus** [argoproj/argo-events#203]
How can i implement a multi source git trigger, basically meaning one for hook miltiple repos. Simplest example would be to just change the repo url based on the hook payload, 

What would be the preferred way of implementing something like that?

**Comment by VaibhavPage** [comment]
Right, the simplest way will be to have multiple triggers with each pointing to the different git repo and the factor deciding which trigger to execute would be `when` condition on a trigger. 

Another way you can do this is to have a single workflow defined in a git repo. But depending on the payload, you would either replace the spec with payload data or substitute the defaults. This assumes that the image would be the same for all triggers.
