### ISSUE TITLE
Failed to create the admission controller- Openshift

### ISSUE THREAD

**Issue by Chandan-SS** [argoproj/argo-events#2033]
**Describe the bug**
Unable to create events-webhook in openshift cluster.  Events-webhook pod ends up in crashloopback with below error

**To Reproduce**
Follow the steps for Openshift cluster https://argoproj.github.io/argo-events/installation/ 

**Expected behavior**
 events-webhook pod must come up fine

**Screenshots**
k logs -f events-webhook-794f488d46-kdc2h
+ kubectl logs -f events-webhook-794f488d46-kdc2h
{"level":"error","ts":1655127551.5780551,"logger":"argo-events.webhook","caller":"webhook/webhook.go:109","msg":"Failed to register webhook","error":"failed to create a webhook: the server could not find the requested resource","errorVerbose":"the server could not find the requested resource\nfailed to create a webhook\ngithub.com/argoproj/argo-events/webhook.(*AdmissionController).register\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:197\ngithub.com/argoproj/argo-events/webhook.(*AdmissionController).Run\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:108\ngithub.com/argoproj/argo-events/webhook/cmd.Start\n\t/home/runner/work/argo-events/argo-events/webhook/cmd/start.go:69\ngithub.com/argoproj/argo-events/cmd/commands.NewWebhookCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/webhook.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/proc.go:255\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581","stacktrace":"github.com/argoproj/argo-events/webhook.(*AdmissionController).Run\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:109\ngithub.com/argoproj/argo-events/webhook/cmd.Start\n\t/home/runner/work/argo-events/argo-events/webhook/cmd/start.go:69\ngithub.com/argoproj/argo-events/cmd/commands.NewWebhookCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/webhook.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/proc.go:255"}
{"level":"fatal","ts":1655127551.5781991,"logger":"argo-events.webhook","caller":"cmd/start.go:70","msg":"Failed to create the admission controller","error":"failed to create a webhook: the server could not find the requested resource","errorVerbose":"the server could not find the requested resource\nfailed to create a webhook\ngithub.com/argoproj/argo-events/webhook.(*AdmissionController).register\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:197\ngithub.com/argoproj/argo-events/webhook.(*AdmissionController).Run\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:108\ngithub.com/argoproj/argo-events/webhook/cmd.Start\n\t/home/runner/work/argo-events/argo-events/webhook/cmd/start.go:69\ngithub.com/argoproj/argo-events/cmd/commands.NewWebhookCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/webhook.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/proc.go:255\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581","stacktrace":"github.com/argoproj/argo-events/webhook/cmd.Start\n\t/home/runner/work/argo-events/argo-events/webhook/cmd/start.go:70\ngithub.com/argoproj/argo-events/cmd/commands.NewWebhookCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/webhook.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/proc.go:255"}

**Environment (please complete the following information):**
 - Kubernetes: v1.11
 - Argo: v3.3.6
 - Argo Events: v1.7.1
- openshift v3.11.0

**Additional context**
Openshift 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
The `ValidatingWebhookConfiguration` we are creating is version `v1`, but openshift v3.11 only supports `v1beta1`.

https://docs.openshift.com/container-platform/3.11/rest_api/admissionregistration_k8s_io/validatingwebhookconfiguration-admissionregistration-k8s-io-v1beta1.html
