### ISSUE TITLE
Timeouts in ArgoSensor when triggering Jobs from SQS

### ISSUE THREAD

**Issue by Shahard2** [argoproj/argo-events#2058]
**Describe the bug**
Hello, we're getting timeouts in Argo Sensor when we trigger around 100+ jobs at the same time from SQS.

**Logs**

`{"caller":"sensors/listener.go:346", "error":"failed to execute trigger: timed out waiting for the condition: The POST operation against Job.batch could not be completed at this time, please try again.", "errorVerbose":"timed out waiting for the condition: The POST operation against Job.batch could not be completed at this time, please try again.
failed to execute trigger
github.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne
	/home/runner/work/argo-events/argo-events/sensors/listener.go:399
github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit
	/home/runner/work/argo-events/argo-events/sensors/listener.go:344
runtime.goexit
	/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581", "kubernetes":{…}, "logger":"argo-events.sensor", "msg":"failed to execute a trigger", "sensorName":"content-worker-sensor", "stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit
	/home/runner/work/argo-events/argo-events/sensors/listener.go:346", "time":"2022-06-29T07:28:36.658839303Z", "triggerName":"create", "triggeredBy":[…], "triggeredByEvents":[…], "ts":1.656487716655088E9}`

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
I believe this is the problem of Kubernetes API server, that it could not handle that many requests concurrently (or it reached the rate limit).

**Comment by Shahard2** [comment]
> I believe this is the problem of Kubernetes API server, that it could not handle that many requests concurrently (or it reached the rate limit).

Thanks mate,
How can I verify it and resolve it?

**Comment by Shahard2** [comment]
Anyone can help ?

@whynowy
