### ISSUE TITLE
SCRAM is not supported in Kafka triggers

### ISSUE THREAD

**Issue by avasiliev** [argoproj/argo-events#2087]
**Describe the bug**
The following configuration works perfectly in Kafka event sources:
```yaml
tls:
  insecureSkipVerify: true
sasl:
  mechanism: SCRAM-SHA-512
  passwordSecret: ***
  userSecret: ***
```
However when I create a trigger with the same config, this kind of messages start to appear in its log:
```
kafka: invalid configuration (A SCRAMClientGeneratorFunc function must be provided to Net.SASL.SCRAMClientGeneratorFunc)
```
with stacktrace
```
github.com/argoproj/argo-events/sensors.(*SensorContext).GetTrigger
	/home/runner/work/argo-events/argo-events/sensors/trigger.go:94
github.com/argoproj/argo-events/sensors.(*SensorContext).triggerOne
	/home/runner/work/argo-events/argo-events/sensors/listener.go:367
github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit
	/home/runner/work/argo-events/argo-events/sensors/listener.go:344
```

I believe the reason of the problem is that SCRAM was not implemented for triggers in [#1528](https://github.com/argoproj/argo-events/pull/1528), and some pieces of code like [this](https://github.com/argoproj/argo-events/blob/5ba897ac3b20413fb81245a91d4e6680984181a3/eventsources/sources/kafka/start.go#L282-L286) are missing [here](https://github.com/argoproj/argo-events/blob/5ba897ac3b20413fb81245a91d4e6680984181a3/sensors/triggers/kafka/kafka.go#L67)

**To Reproduce**
1. Create a sensor with Kafka trigger connecting to a server using SCRAM-SHA-512 SASL mechanism
2. Go to sensor logs in Argo web UI, see `msg=failed to new a Kafka trigger` and `failed to execute a trigger`
3. Get full logs via `kubectl -logs <sensor-pod-name>`, see full error message with stacktrace

**Expected behavior**
Trigger works successfully

**Environment:**
 - Kubernetes: v1.22.9-eks-a64ea69
 - Argo: untagged, GitCommit: fd6f3c263412a1174de723470a14721b220c4651
 - Argo Events: 1.7.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@avasiliev - thanks for reporting this issue! I wonder if you would like to submit a PR to add it?
