### ISSUE TITLE
Some backend services are in UNHEALTHY state (when using ingress to route to service webhook-eventsource-svc)

### ISSUE THREAD

**Issue by vaporpin** [argoproj/argo-events#2094]
**Describe the bug**
I tested a set of event source and sensor (instructions from https://argoproj.github.io/argo-events/tutorials/01-introduction/) without creating an ingress, just using **port forwarding** and the implementation worked. 

However when I tried to deploy an GCE class ingress (which automatically creates a external Load Balancer) to route path /argoevents to webhook-eventsource-svc, there is error : "**Some backend services are in UNHEALTHY state**" namely the [xxxxx-argo-events-webhook-eventsource-svc-xxxxx] backend service. So when I curl http://xx.xx.xx.xx/argoevents, **response 404 (backend NotFound), service rules for the path non-existent**

**my ingress**
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: argo-events
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /argoevents
            pathType: ImplementationSpecific
            backend:
              service:
                name: webhook-eventsource-svc
                port:
                  number: 12000
          - path: /v2
            pathType: ImplementationSpecific
            backend:
              service:
                name: hello-world-2
                port:
                  number: 80

I created a usual deployment and service resource, hello-world-2 and created another route path **v2** to test. I'm able to get a response from the service via the ingress using curl xx.xx.xx.xx/v2, which means that ingress is working. 

Anyone can advice on this issue? Thanks!

**Comment by whynowy** [comment]
Check if this helps.

https://github.com/argoproj/argo-events/blob/master/docs/eventsources/webhook-health-check.md

**Comment by vaporpin** [comment]
@whynowy , thanks for the help. 

I created a NodePort service using the doc https://argoproj.github.io/argo-events/eventsources/services/ and managed to trigger the sensor from outside the cluster. Also tried this health check end point and it return OK. 

But when the service is routed to the ingress, it states that it is in unhealthy state.
