### ISSUE TITLE
Support non-inotify file gateway

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-events#212]
**Is your feature request related to a problem? Please describe.**

The file gateway doesn't work with a file system which doesn't support inotify because fsnotify doesn't support it.
https://github.com/fsnotify/fsnotify/issues/9

**Describe the solution you'd like**

Utilize naivewatcher which I implemented in #180.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by dtaniwaki** [comment]
It seems it works with my NetApp storage mounted as NFS unexpectedly. Maybe, [FPolicy](https://library.netapp.com/ecmdocs/ECMP1120826/html/GUID-54FE1A84-6CF0-447E-9AAE-F43B61CA2138.html) does some trick?

**Comment by VaibhavPage** [comment]
I guess this is handled in one of the earlier prs. Can we close this?

**Comment by dtaniwaki** [comment]
I don’t think so. I thought this feature is necessary but I realized the netapp NFS in my cluster can handle inotify which should not be handled by normal NFS. So, I stopped investigating it.

**Comment by VaibhavPage** [comment]
I see.

**Comment by VaibhavPage** [comment]
I guess https://github.com/radovskyb/watcher will solve the issue. Now, the question is do we use fsnotify and fall back on this if fsnotify is not supported, or just use this library altogether?

**Comment by wktmeow** [comment]
+1 Also interested in this being fixed for NFS

**Comment by whynowy** [comment]
I assume this has been implemented, can I close this issue? @dtaniwaki @matveybrant
