### ISSUE TITLE
Trigger resources without namespace can not be created

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-events#214]
**Describe the bug**

I found omitting namespace in trigger resources causes an error in this line.
https://github.com/argoproj/argo-events/blob/a68118076fdf3e54ab63864661b25f4048327e3f/sensors/trigger.go#L230

Here's the actual error log.

```
2019-03-08T11:01:48Z | error | msg: trigger failed to execute |  error="failed to create resource object. err: an empty namespace may not be set during creation" sensor-name:hdfs-sensor trigger-name:hdfs-workflow-trigger
```

**To Reproduce**

Omit `namespace` in your trigger resources.

**Expected behavior**

https://github.com/argoproj/argo-events/blob/ac66a69bb09847b5369b4aeb74738ec43d13b6bf/pkg/apis/sensor/v1alpha1/types.go#L259
This line describes the default namespace is the namespace of the service account. However, it seems the default namespace is not applied.

I think the namespace of the service account is hard to imagine. Should we use the namespace of the sensor, or `default` namespace?

**Screenshots**

N/A

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: N/A
 - Version: N/A

**Additional context**

N/A

**Comment by VaibhavPage** [comment]
Hmm... Somehow  I thought this was taken care of. I think we should fall to `Sensor` namespace mainly because many users install argo and argo-events in the same namespace.

**Comment by dtaniwaki** [comment]
I’ll fix it like so!
