### ISSUE TITLE
Error when trying to Install Argo Events on OpenShift (cannot use port 443)

### ISSUE THREAD

**Issue by stratus-ss** [argoproj/argo-events#2159]
**Describe the bug**
This bug report is exactly the same as https://github.com/argoproj/argo-events/issues/1726 

The user closed the bug without specifying a solution. Myself and a second user are interested in this fix/solution as well but I fear bumping a closed ticket will not receive any attention and I cannot reopen the old ticket.

How do we get the webhook to listen on a different port? Do we have to recompile the application? The namespace is an env variable but the port is not. Ideally this would be set to 8443 as an alternative

Thanks!

The error for reference is 

```
{"level":"info","ts":1661952821.062444,"logger":"argo-events.webhook","caller":"webhook/webhook.go:199","msg":"Webhook already exists"}
{"level":"info","ts":1661952821.0676394,"logger":"argo-events.webhook","caller":"webhook/webhook.go:205","msg":"Updating webhook"}
{"level":"info","ts":1661952821.0784574,"logger":"argo-events.webhook","caller":"webhook/webhook.go:112","msg":"Successfully registered webhook"}
{"level":"error","ts":1661952821.0789645,"logger":"argo-events.webhook","caller":"webhook/webhook.go:117","msg":"ListenAndServeTLS for admission webhook errored out","error":"listen tcp :443: bind: permission denied","stacktrace":"github.com/argoproj/argo-events/webhook.(*AdmissionController).Run.func1\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:117"}
{"level":"fatal","ts":1661952821.0790799,"logger":"argo-events.webhook","caller":"cmd/start.go:70","msg":"Failed to create the admission controller","error":"webhook server failed to start","errorVerbose":"webhook server failed to start\ngithub.com/argoproj/argo-events/webhook.(*AdmissionController).Run\n\t/home/runner/work/argo-events/argo-events/webhook/webhook.go:125\ngithub.com/argoproj/argo-events/webhook/cmd.Start\n\t/home/runner/work/argo-events/argo-events/webhook/cmd/start.go:69\ngithub.com/argoproj/argo-events/cmd/commands.NewWebhookCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/webhook.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/proc.go:255\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581","stacktrace":"github.com/argoproj/argo-events/webhook/cmd.Start\n\t/home/runner/work/argo-events/argo-events/webhook/cmd/start.go:70\ngithub.com/argoproj/argo-events/cmd/commands.NewWebhookCommand.func1\n\t/home/runner/work/argo-events/argo-events/cmd/commands/webhook.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/argoproj/argo-events/cmd/commands.Execute\n\t/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19\nmain.main\n\t/home/runner/work/argo-events/argo-events/cmd/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.1/x64/src/runtime/proc.go:255"}
```

**Comment by fhochleitner** [comment]
how are you isntalling argo events? we are using it on openshift and installed it via the community helm-chart. the option "openshift: true" it should work out of the box.

**Comment by whynowy** [comment]
Anybody wants to submit a PR to make the port configurable (e.g. in the `args`)?

**Comment by nirsht** [comment]
Hi @whynowy, I can do it

**Comment by stratus-ss** [comment]
> how are you isntalling argo events? we are using it on openshift and installed it via the community helm-chart. the option "openshift: true" it should work out of the box.

I might have missed the helm chart option. Looking back in my history I see I definitely used the `kubectl apply` method.
I want to say that I also tried the helm installation as well but this box's history has rolled over since then but if I did, I missed the option that I see is present (when I know to look for it)

@nirsht thank you for volunteering to make a PR. I am sure I won't be the last person to focus on applying the yamls instead of using the helm chart!

**Comment by nirsht** [comment]
Hi @stratus-ss, the port is indeed not configurable either way, if only the port would be configurable it would help. I made PR https://github.com/argoproj/argo-events/pull/2215 with option to configure the port, while setting the default to 443. If the PR looks good to you, I will update the docs also.

**Comment by stratus-ss** [comment]
@nirsht this was exactly the direction I *thought* would be available. I found the environment variable for namespace while i was trying to see if there was a setting for the port.

much appreciated

**Comment by whynowy** [comment]
@nirsht - thank you! PR merged, will be available in next release.
