### ISSUE TITLE
Request to add configurable annotations to eventsource services

### ISSUE THREAD

**Issue by mstory21** [argoproj/argo-events#2186]
**Is your feature request related to a problem? Please describe.**
Our Ambassador deployment requires that we use service annotations to control http mappings for access outside of the cluster.  We'd like to be able to add these annotations to the services created for event sources -- specifically for generic webhooks and github.

**Describe the solution you'd like**
I would like to have a way to add custom annotations to services per-event source.

**Describe alternatives you've considered**
We've discussed using Mapping resources with our Kubernetes team but they would rather use annotations since they don't leave around abandoned mappings when the service goes away.

**Additional context**
Example Ambassador annotation:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: svc1-service_mapping
      host: svc1.your-domain
      prefix: /
      service: svc1:80

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Pod annotation on EventSource and Sensor can be done by setting

```
spec:
  template:
    metadata:
      annotations:
        a: b
```

**Comment by whynowy** [comment]
I see. I think you were talking about the service for webhook EventSource, we actually recommend you creating the service by yourself, see the link below.

https://github.com/argoproj/argo-events/blob/master/docs/eventsources/services.md

**Comment by mstory21** [comment]
OK, I'll go that route.
