### ISSUE TITLE
Documentation out of date - userPayload depreciated field

### ISSUE THREAD

**Issue by jackmead515** [argoproj/argo-events#2190]
**Describe the bug**
The documentation and examples clearly indicates that an EventSource of type "calendar" can define a `userPayload` as additional data to send in the event. The `userPayload` is a depreciated field and replaced with `metadata`

https://github.com/argoproj/argo-events/blob/v1.7.1/examples/event-sources/calendar.yaml#L32
https://argoproj.github.io/argo-events/eventsources/setup/calendar/

**Environment (please complete the following information):**
 - Argo Events: [e.g. v1.7.1]

**Additional context**
Just need to update documentation and the examples with the new `metadata` argument.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Thanks, will fix it.
