### ISSUE TITLE
Kafka Based Event Source: Support for pass-through on Kafka configuration

### ISSUE THREAD

**Issue by Rakesh627** [argoproj/argo-events#2206]
**Is your feature request related to a problem? Please describe.**
Currently, the Kafka Eventsource has limited set of exposed Kafka configurations. 

**Describe the solution you'd like**
Expose Kafka client configuration of the underlying client (sarama) as a pass through in eventsource to pass batching and other kafka consumer config.

**Describe alternatives you've considered**
Tuning `limitEventsPerSecond` configuration which didn't help.

**Additional context**
Currently `limitEventsPerSecond` causes a high amount of fetch requests to Kafka brokers, I would like to be able to configure batching and backoff configurations to limited unwanted fetch requests sent to Kafka consumer.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Closed by https://github.com/argoproj/argo-events/pull/2161
