### ISSUE TITLE
Support multitenancy in workflows

### ISSUE THREAD

**Issue by mattdarwin** [argoproj/argo-events#223]
We want to schedule a regular job which should happen for multiple tenants. For example, at 3pm each day, run 25 workflows in parallel (one for each tenant).  Rather than having 25 calendar gateways, we'd like just one.  

In the general case, we might also want to have a single web hook call trigger multiple workflows (one for each tenant).  The list of tenants is metadata, and we should be able to easily add and remove from this list.  

One workaround is to have a workflow triggered which loops through a list of tenants (stored in some config map) and triggers a workflow call for each, supplying the relevant tenantId each time.

**Comment by VaibhavPage** [comment]
From what I understand, you are basically looking for a `for` loop over triggers?

**Comment by VaibhavPage** [comment]
the for loop feature can be added by introducing `withItems` and `withParams`.

**Comment by adrienjt** [comment]
If tenant means cluster, you can run a workflow across clusters with multicluster-scheduler:
https://github.com/admiraltyio/multicluster-scheduler
https://admiralty.io/blog/running-argo-workflows-across-multiple-kubernetes-clusters/
