### ISSUE TITLE
EventBus failed to get nats streaming version

### ISSUE THREAD

**Issue by pockyhe** [argoproj/argo-events#2261]
**Describe the bug**
I tried to enable Argo Event in k8s with Argo Event helm chart. whiile applying eventbus, It caused error:
{"level":"error","ts":1666002222.3261538,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:56","msg":"reconcile error","namespace":"argo-main","eventbus":"default","error":"failed to get nats streaming version, err: unsupported version \"0.22.1\", supported versions: \"latest\"","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:56\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

And kubectl describe eventbus. It indicates that:
Status:
Conditions:
Last Transition Time: 2022-10-17T10:28:59Z
Status: True
Type: Configured
Last Transition Time: 2022-10-17T10:28:59Z
Message: Failed to build a statefulset spec
Reason: BuildStatefulSetFailed
Status: False
Type: Deployed

**Environment (please complete the following information):**
Helm Chart: Argo Workflow(Version 0.20.1) and Argo Event(Version 2.0.6)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
The helm chart is maintained by community folks, I think there's some configuration missing in it. You can fix the problem in the controller configmap, follow https://github.com/argoproj/argo-events/blob/master/manifests/base/controller-manager/controller-config.yaml#L10-L12.
