### ISSUE TITLE
Cannot Create resource "argo-events"

### ISSUE THREAD

**Issue by emmayylu** [argoproj/argo-events#2266]
**Describe the bug**
This issue (https://github.com/argoproj/argo-events/issues/1418) still exists in Argo Events v1.7.3

When using this (https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/webhook.yaml) to create a Argo Event Sensor to trigger a workflow, I get this error message `failed to execute trigger: timed out waiting for the condition: default is forbidden: User \"system:serviceaccount:argo-events:operate-workflow-sa\" cannot create resource \"argo-events\" in API group \"\" at the cluster scope`. Resource always equals namespace name.

To make it work we need to edit definition like this:
``` triggers:
     - template:
         name: webhook-workflow-trigger
         k8s:
+          group: argoproj.io
+          version: v1alpha1
+          resource: workflows
           operation: create
           source:
             resource:
               apiVersion: argoproj.io/v1alpha1
               kind: Workflow
```

**To Reproduce**
Go through "Get started" https://argoproj.github.io/argo-events/quick_start/

**Expected behavior**
The triggered workflow would run successfully

**Environment (please complete the following information):**
 - Kubernetes: v1.21.7
 - Argo: v2.11.7
 - Argo Events: v1.7.3

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Anybody else sees this?
