### ISSUE TITLE
Parameterization a block of k8s resource (set of key values)

### ISSUE THREAD

**Issue by GoshaDo** [argoproj/argo-events#2272]
**Describe the bug**
I am trying to parametrize an entire block of k8s trigger using payload. the payload converted to string with backslashes and can't be injected to overwrite the block. Workflows CRD getting `cannot unmarshall spec: cannot restore struct from: string.`

Here is an example of the sensor:
```apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: example
  namespace: argocd
spec:
  template:
    serviceAccountName: argo-wf
  dependencies:
    - name: example-dep
      eventSourceName: example-event-source
      eventName: event-test
  triggers:
    - template:
        name: example-template
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: injected-block-
              spec:
                entrypoint: main
                arguments:
                  parameters:
                    - name: message
                      value: hello world
                serviceAccountName: argo-wf  
                templates:
                  - name: main
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args:
                        - "hello world"
          parameters:
            - src:
                dependencyName: example-dep
                dataKey: body.injected
              dest: spec.templates.0.container```

After debugging the sensor I have found that in line 124 sensors/triggers/params.go get serialized json with backslashes:
```
func ApplyParams(jsonObj []byte, params []v1alpha1.TriggerParameter, events map[string]*v1alpha1.Event) ([]byte, error) {
...
tmp, err := sjson.SetBytes(jsonObj, param.Dest, *value)
...

*values values is:
```
Actual state: "{\"image\":\"docker/whalesay:latest\",\"command\":[\"cowsay\"],\"args\":[\"injected\"]}"
 Desired state: "{"image":"docker/whalesay:latest","command":["cowsay"],"args":["injected"]}"
```

The source of that serialization in github.com/cloudevents/sdk-go/v2 that used in eventbus/stan/sensor.(*STANTriggerConn).Subscribe.func1. 

Better option would be to use this differently and use sjson.SetRawBytes function instead of sjson.SetBytes in sensors/triggers/params.go

**To Reproduce**
1. Deploy the sensor from above.
2. send the following json body to the event source:
```
{
  "injected": {
    "image": "docker/whalesay:latest",
    "command": ,
    "args": [
      "injected"
    ]
  }
}
```
**Expected behavior**
Create a workflow that marshal spec right.

**Screenshots**
<img width="1252" alt="Screen Shot 2022-10-25 at 10 37 58" src="https://user-images.githubusercontent.com/86723475/197712459-38eb27bf-5006-4e1f-ae7a-4cd86e29438d.png">

**Environment (please complete the following information):**
 - Kubernetes: v1.24.0
 - ArgoWorkflows: v3.4.2
 - Argo Events: v1.7.3

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by idanrookout** [comment]
👍
