### ISSUE TITLE
Use CloudEvents sdk-go

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-events#234]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Use https://github.com/cloudevents/sdk-go to easily support cloudevent (v0.2).

**Describe alternatives you've considered**

N/A

**Additional context**

I think we should use cloudevents sdk-go to support various types of event protocol instead of implementing it by ourselves, and also to update event spec easily.

**Comment by VaibhavPage** [comment]
Definitely. We can add this as a part of the work required for `EventSource` CRD which will be the focus after v1.0. 

We should also start fleshing out the roadmap for v2.0

**Comment by dtaniwaki** [comment]
Nats streaming has not been supported in cloudevents sdk-go.
However, there's a PR for the feature.
https://github.com/cloudevents/sdk-go/pull/136

**Comment by dtaniwaki** [comment]
I found the current format is slightly different from [the examples in CloudEvents v0.1](https://github.com/cloudevents/spec/blob/v0.1/json-format.md#32-examples).

Here's a current format example.

```
{"context":{"eventType":"webhook","eventTypeVersion":"v0.10","cloudEventsVersion":"0.1","source":{"scheme":"","user":"","password":"","host":"webhook-gateway:example","port":0,"path":"","query":"","fragment":""},"eventID":"32663132666664612d623661642d313165392d383366612d303234326163313130303161","eventTime":"2019-08-04T11:44:14.688738Z","schemaURL":null,"contentType":"application/json"},"payload":null}
```

@VaibhavPage Do you know why we're using a different format? Can we start to use the correct format?

I will also support v0.2 and v0.3 format after implementing cloud SDK adoption with v0.1.

**Comment by n3wscott** [comment]
👀

**Comment by VaibhavPage** [comment]
I think when I referred to spec, it was even before v0.1, thats why the discrepancies.

**Comment by dtaniwaki** [comment]
So, can I change the format of v0.1?

**Comment by VaibhavPage** [comment]
yep.

**Comment by VaibhavPage** [comment]
Closing the issue. This is implemented and cloud-events-sdk is part of Argo-Events,
