### ISSUE TITLE
Delivery Guarantees don't seem to hold

### ISSUE THREAD

**Issue by EyalAr** [argoproj/argo-events#2340]
**Describe the bug**
The docs state:

> we are able to achieve 1) "exactly once" in almost all cases, with the exception of pods dying while processing messages, and 2) "at least once" in all cases.

I believe 2 is incorrect. This is based on analysis of the Sensor code, and on stress tests in which I randomly killed sensor pods.

**To Reproduce**
I sent hundreds of events/second to a webhook EventSource, each with a unique UUID.
I built an HTTP server, and configured a sensor to have an HTTP trigger which calls this server with the event UUID.
The server kept account of events sent and events received, and produced a report of which UUIDs were sent but never received.
During the test I randomly killed the sensor pod, and observed that this caused some UUIDs to never be received by my HTTP server.

**Expected behavior**
All UUIDs to be delivered to the HTTP server at least once.

**Additional context**
![image](https://user-images.githubusercontent.com/1146412/206248255-f9fcfb8e-a002-4655-b8e8-8d8d4ec1f6c7.png)
The above diagram is based on analysis of the Sensor code.
Seemingly, at-least-once is achieved by acking the message only after `actionFunc` returns - which is good.
But, inside `actionFunc` a goroutine is started, inside of which the actual trigger action is performed (the `execute` method).
This means that `actionFunc` returns **before** the trigger action is performed. And this will possibly (likely) mean that the message is ack'ed before the trigger is executed.
If the pod dies after the message is ack'ed, but before the trigger is executed, the at-least-once guarantee doesn't hold.

Note: This is based on the Jetstream implementation.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
The doc needs to be revised.

**Comment by danryan** [comment]
> This means that actionFunc returns before the trigger action is performed. And this will possibly (likely) mean that the message is ack'ed before the trigger is executed.

That seems okay, though. I don’t think your is failing the guarantee. The message is delivered at least once successfully. Triggers have no guarantees.
