### ISSUE TITLE
[Partition] Kafka Trigger

### ISSUE THREAD

**Issue by Thomasr-02** [argoproj/argo-events#2357]
**Describe the bug**

I cannot use round-robin on Kafka Trigger

**Additional context**

The partition parameter on Kafka trigger is mandatory following the doc, but, if we see the code, the parameter is not validated by  `validateKafkaTrigger`. it is a point. 

if we do not set the partition parameter, It is set to 0 as a default value ( Meaning that: all messages are delivered to topic on 0 partition)
if we set X on partition parameter, all message is delivery to topic on X partition, 
but if we want use, default round-robin on Kafka ( it is not supported by the argo-events)

**Expected behavior**

I hoped that by setting it as `-1` As the partition parameter, I would be removing the partition property. Thus using the default kafka’s round-robin

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by jwillker** [comment]
This will be very useful.
