### ISSUE TITLE
GCP PubSub messages coming in as base64 encoded, unable to decrypt Part 2

### ISSUE THREAD

**Issue by nicolas-vivot** [argoproj/argo-events#2384]
**Describe the bug**

Can you please re-open and consider to fix this critical bug ?

https://github.com/argoproj/argo-events/issues/1371

**Comment by whynowy** [comment]
Re-opened, @nicolas-vivot - would you like to submit a PR?

**Comment by nicolas-vivot** [comment]
Was an issue between the chair and the keyboard. Closing.
