### ISSUE TITLE
Errors returned by StartEventSource are silently ignored

### ISSUE THREAD

**Issue by discordianfish** [argoproj/argo-events#240]
**Describe the bug**
Returning an error in StartEventSource is silently ignored.

**Expected behavior**
An error should be logged and handled accordantly.

**Comment by discordianfish** [comment]
Looks like it gets handled but it doesn't show up in the logs:
https://github.com/argoproj/argo-events/blob/master/gateways/event-sources.go#L170

Not sure what's the intended design here is. I'd feel like the errors should be logged there instead of having to log them in the gateway implementations.

**Comment by VaibhavPage** [comment]
handled in #243
