### ISSUE TITLE
Kafka Trigger - Avro - Sensor

### ISSUE THREAD

**Issue by Thomasr-02** [argoproj/argo-events#2422]
**Describe the bug**

When SchemaRegistry is defined, the fisrt message published is correct on avro format. But, the next messages is published in json format. 
After much investigation, I understood the behavior: In the first message `schema` is different of nil and the message is published in avro format [in this line](https://github.com/argoproj/argo-events/blob/master/sensors/triggers/kafka/kafka.go#L210), in the next event, the schema is nil and is not published in avro, but why?? The schema value is losted after first event!?! I dont know why, but it's the behavior, others parameters of KafkaTrigger like (Trigger, Sensor,...) is not losted

**To Reproduce**
Define the SchemaRegistry on KafkaTrigger and see the format of message published

**Expected behavior**
All messages published in avro format

**Environment:**
 - Argo Events: branch master

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by Thomasr-02** [comment]
@whynowy  you can help me to fix this.

**Comment by whynowy** [comment]
You put https://github.com/argoproj/argo-events/blob/master/sensors/triggers/kafka/kafka.go#L138-L144 in a wrong place, it should be at https://github.com/argoproj/argo-events/blob/master/sensors/triggers/kafka/kafka.go#L146.

Can you please fix it? @Thomasr-02

**Comment by jwillker** [comment]
Hey, @whynowy I'm been working with @Thomasr-02, so I have made your code change suggestion, makes a lot of sense, I have tested and worked perfectly.

I just open a PR to fix this: https://github.com/argoproj/argo-events/pull/2423
