### ISSUE TITLE
Support parsing headers of consumed messages of Kafka triggers to enable distributed tracing from/to Argo Workflows

### ISSUE THREAD

**Issue by jae-ryu** [argoproj/argo-events#2442]
**Is your feature request related to a problem? Please describe.**
For an event-driven, asynchronous distributed workload - such as Argo Workflows triggered by a Kafka message produced by another service - insights from distributed tracing across boundaries can be useful for system-wide stability & optimization. 

Pattern I've seen for establishing distributed trace across event-driven async workloads is to interject headers into Kafka message with parent span/trace metadata before producing to Kafka -> enable receiving Kafka consumer to parse the headers of Kafka msg -> and only after post-processing, append a child_span to the parent span passed via Kafka headers upstream.

ref for example: https://newrelic.com/blog/how-to-relic/distributed-tracing-with-kafka

However, currently, Argo-Events kafka event source retrieves only the content of the message & assigns it to ```eventData.Body```. (src code: https://github.com/argoproj/argo-events/blob/master/eventsources/sources/kafka/start.go#L391) 

**Describe the solution you'd like**
When consuming a message from Kafka eventsource topic,
if ```message.Headers``` exists for the message being consumed, make it accessible for workflow to be triggered at ```eventData.Headers```
 

**Describe alternatives you've considered**
To pass trace context across services not directly talking to each other except indirectly via Kafka queue, if headers metadata cannot be parsed by Argo Events Kafka trigger, I considered 2 non-ideal short-term & 1 hope-not medium-term options:

Short-term 1) Inject the metadata deeper into the message, into the message protobuf fields themselves
* non-starter for us, introduces too much noise into protobuf schema that's used by other services that's not Argo that can parse msg headers, so this would be a protobuf schema specially tailored only for Argo-portion of our stack

Short-term 2) Retrieve the metadata from somewhere else both disconnected services can access, e.g. database
* also non-starter storing uuid's of ephemeral data that we only need for short retention period. becomes fragile with increased dependencies, fail points 

Hope-not 3) Change our Argo Workflows sensor trigger to HTTP trigger accepting payloads, by a new Kafka consumer that would be listening for the message that is currently triggering my Argo-workflows --> then fwding that payload with parent trace metadata to HTTP trigger endpoint.
* if the reviewers don't expect this feature request to be prioritized, this might be the option I have to go with given our need for distributed tracing
* but this is anti-pattern to how majority of our workflows are structured today. I would like to avoid the refactoring cost if this feature is a relatively small manageable scope to implement, which at the surface it seems so.  

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by jae-ryu** [comment]
I also posted on Stackoverflow to see if there are known workarounds & demand across users: https://stackoverflow.com/questions/75254481/argo-events-kafka-triggers-cannot-parse-message-headers-to-enable-distributed-tr

**Comment by OneCricketeer** [comment]
Related #968
