### ISSUE TITLE
Create "exotic" equivalent for Jetstream EventBuses

### ISSUE THREAD

**Issue by JacobHenner** [argoproj/argo-events#2462]
**Is your feature request related to a problem? Please describe.**

STAN [is being deprecated](https://docs.nats.io/legacy/stan/intro#warning-deprecation-notice) and [JetStream](https://docs.nats.io/nats-concepts/jetstream) is set to replace it. Although Argo Events supports both, [only STAN](https://github.com/argoproj/argo-events/blob/master/api/event-bus.md) can be configured to rely on a separately-provisioned NATS/STAN cluster. For JetStream, only Argo Events-managed JetStream clusters can be defined.

For Argo Events-enabled Kubernetes clusters that rely heavily on namespacing, the need to provision a separate JetStream cluster in each namespace can quickly become an inefficient use of resources.

**Describe the solution you'd like**

If an "exotic" equivalent for JetStream was supported, operators could create their own optimized JetStream clusters, and define connection configuration in an `EventBus` in each namespace.

**Describe alternatives you've considered**

If [a Kafka-based EventBus](https://github.com/argoproj/argo-events/issues/1682) (that relied on externally-provisioned Kafka) was available it would serve as a suitable alternative for my specific situation, but it may not be suitable for all cases (some users may prefer JetStream over Kafka for other reasons).

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by tooptoop4** [comment]
https://github.com/dfarr/kafkanaut mentioned in https://dfarr.medium.com/exploring-messaging-systems-with-argo-events-a259f663bd30 is exploring it

**Comment by whynowy** [comment]
Interesting... we didn't add external JetStream support because we thought nobody uses the `exotic` stan....

**Comment by wolfdate25** [comment]
I configured using nat's exotic but I seems not working.

**Comment by gokulav137** [comment]
I would like to contribute to this feature

For NATS streaming exotic, the format is 
```yaml
spec:
  nats:
    exotic:
```
and for native, the format is
```yaml
spec:
  nats:
    native:
```
This differs in the format for jetstream native which is
```yaml
spec:
  jetstream:
```
So how should I go ahead on this. 

-  Should I change this to a consistent format

```yaml
spec:
  jetstream:
    native:
# And
spec:
  jetstream:
    exotic:
```
But this will introduce incompatibility with older versions.

OR
- Should I add the exotic like so
```yaml
spec:
  jetstream-exotic:
```
@whynowy , would like your opinion on this.

**Comment by joshadambell** [comment]
I think consistency in the API would be nice but I don’t think this is worth a breaking change.

my vote is 
```
spec:
  jetstreamExotic:
```

**Comment by gokulav137** [comment]
> I think consistency in the API would be nice but I don’t think this is worth a breaking change.
> 
> 
> 
> my vote is 
> 
> ```
> 
> spec:
> 
>   jetstreamExotic:
> 
> ``` 

I agree too. I'll try to draft a PR for this.
