### ISSUE TITLE
Improve errors

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-events#247]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

I found there are many kinds of error creation ways in the code. For example, `fmt.Errorf`, `errors.New` and `errors.Errorf` (`github.com/pkg/errors`). Although all of these ways create an `error`, the latter is preferable because it has stack traces. One way to force the error type is defining `ArgoEventsError` interface which is just the same as the error returned by `errors.Errorf` (`github.com/pkg/errors`). I described how the interface look like below. Then use this error interface in our code. In this way, if a native go or 3rd party method returns an `error`, we need to wrap it to fulfill `ArgoEventsError`.

```
package errors

import (
	"fmt"

	"github.com/pkg/errors"

	log "github.com/Sirupsen/logrus"
)

type ArgoEventsError interface {
	StackTrace() errors.StackTrace
	Error() string
	Cause() error
}

// LogErrorWithStack emits a log message with errors.ArgoEventsError level and stack trace with debug level
func LogErrorWithStack(err ArgoEventsError) {
	var fields log.Fields
	if log.GetLevel() == log.TraceLevel {
		fields = log.Fields{"stacktrace": fmt.Sprintf("%+v", err)}
	}
	log.WithFields(fields).Error(err)
}

func Errorf(s string, args ...interface{}) ArgoEventsError {
	return errors.WithStack(fmt.Errorf(s, args...)).(ArgoEventsError)
}

func New(s string) ArgoEventsError {
	return errors.WithStack(fmt.Errorf(s)).(ArgoEventsError)
}

func WithStack(err error) ArgoEventsError {
	if err == nil {
		return nil
	}
	if argoeventserr, ok := err.(ArgoEventsError); ok {
		return argoeventserr
	}
	return errors.WithStack(err).(ArgoEventsError)
}
```

Maybe, there's a better way. Let's discuss what's the ideal way to regularize the errors.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by VaibhavPage** [comment]
This looks much better 👍
