### ISSUE TITLE
GitHub Enterprise auth logic broken

### ISSUE THREAD

**Issue by Kitanotori** [argoproj/argo-events#2494]
**Describe the bug**
BaseURL is not applied to auth logic, resulting in auth logic trying to call actual GitHub instead of GitHub Enterprise server.

**To Reproduce**
In EventSource, set `githubBaseURL: https://ghe.mydomain.com/api/v3/`

**Expected behavior**
Auth logic should use the provided base URL.

**Cause**

BaseURL not applied to AuthTransport: https://github.com/argoproj/argo-events/blob/master/eventsources/sources/github/appauth.go#L31

Ultimate cause is poor implementation of ghinstallation, which just uses hard-coded base URL at https://github.com/bradleyfalzon/ghinstallation/blob/master/appsTransport.go#L57

**Solution**

Either fix ghinstallation (https://github.com/bradleyfalzon/ghinstallation/blob/master/transport.go#L91) or apply e.g. following to appauth.go:

```
func (t *AppsAuthStrategy) AuthTransport() (http.RoundTripper, error) {
	key, err := jwt.ParseRSAPrivateKeyFromPEM([]byte(t.PrivateKey))
	tr := t.transport()
	appTransport := ghinstallation.NewAppsTransportFromPrivateKey(tr, t.AppID, key)
	appTransport.BaseURL = t.BaseURL
	return ghinstallation.NewFromAppsTransport(appTransport, t.InstallationID), err
}
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@Kitanotori - Thanks for reporting the issue, since you already provided a solution, would you like to put it in a PR?

**Comment by Kitanotori** [comment]
@whynowy Ok. I'm not sure how clean the solution is, but I confirmed it fixed the issue.

**Comment by daniel-codefresh** [comment]
@whynowy was wondering if there are any plans to release a patch that includes this fix in the near future?
