### ISSUE TITLE
email inbox/IMAP event source

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#2497]
this eventsource/sensor would be able to trigger a workflow for each email that arrives in a certain inbox. ie whenever fill_name_here@somedomain.com receives an email

**Comment by mustafayildirim** [comment]
@tooptoop4 I'd like to work on it.

**Comment by dberardo-com** [comment]
i also wanted to give this a go, but since Golang is not my preferred language, i would like to implement it in python, is there any example that  i can use for it ?

also, in my use case i might need to read files from the incoming emails, is it possible to send the attachment over the NATS event bus os it impossible due to size limitations ? in that case i need to store the attachment in a filesystem to move it along the event chain.

let me know.

**Comment by dberardo-com** [comment]
ok, i got somewhere, check this out: https://github.com/dberardo-com/argo-events-custom/tree/main/event-sources/imap-event-source

awaiting feedback and contributions ...


in particular:

* how to use the "payload" field somewhere else in the flow ? i dont see that attribute being logged in the "log sink" of argo
* what are the configs shown in the EventSource definition (https://argoproj.github.io/argo-events/eventsources/generic/) ? what are they used for ?

**Comment by tooptoop4** [comment]
u gotsta golang it

**Comment by dberardo-com** [comment]
> Contributor

well i mean, it works in python as well. the repo i have linked is indeed functional. you can test it on your deployment and fork it to improve it if you wish, otherwise simple advice on how to improve it would be appreciated.

btw is it a policy to have golang only contributions on this project?

**Comment by dberardo-com** [comment]
@AleCeli in case you might wanna have a look or might benefit from the implementation: https://github.com/dberardo-com/argo-events-custom/tree/main/event-sources/imap-event-source

**Comment by tooptoop4** [comment]
golang only

**Comment by rossigee** [comment]
fwiw, I've been looking into implementing this for my own evil purposes and made some initial progress. At least, it connects to the IMAP server 😆 . Please feel free to play, comment, debug etc.

https://github.com/rossigee/argo-events/tree/imap-source
