### ISSUE TITLE
Use exotic Nats got an eventbus not ready error

### ISSUE THREAD

**Issue by YanRyan** [argoproj/argo-events#2506]
I use exotic nats and got an eventbus not ready error.

I use helm to install the argo-events and the apiVersion is 1.7.6 as below.
![image](https://user-images.githubusercontent.com/22273064/223950691-195daa7d-8a51-4133-9e25-e487ab95388f.png)

Below is my EventBus yaml

![image](https://user-images.githubusercontent.com/22273064/223950949-73df34e0-c7a2-414a-94ab-72107b3ad856.png)

When I apply the EventSorce I got an eventbus not ready error.  So I add some logs to the eventbus controller.

![image](https://user-images.githubusercontent.com/22273064/223951623-d63a930d-8c0f-45da-9c63-db3eef284184.png)

At first the eventbus DeepCopy contains nats config in the Eventbus as below

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/22273064/223952214-8ea18a0a-d6f1-4d4d-b19c-782fab37e667.png">

But when the eventbus  controller run update func the eventbus DeepCopy has changed it do not contains nats config in the eventbus status  as below.

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/22273064/223952776-7fd9f662-e69d-4747-9724-2228fe41fd7d.png">

I think maybe the update func caused this problem.

**Comment by whynowy** [comment]
Duplicate - https://github.com/argoproj/argo-events/issues/2507
