### ISSUE TITLE
Argo Events deployment causes frequent App reconciliations

### ISSUE THREAD

**Issue by noroutine** [argoproj/argo-events#2519]
**Describe the bug**
When deployed via ArgoCD argo-events causes frequent reconciliations

**To Reproduce**
1. Deploy argo-events via latest helm chart as argocd app
2. In the logs of argocd controller, watch around 3+ reconciliations per second and increased argocd load

**Expected behavior**
No extra reconciliations introduced

**Screenshots**

<img width="2048" alt="Screenshot 2023-03-14 at 15 54 43" src="https://user-images.githubusercontent.com/1372328/225041020-3b785efd-f508-4060-81cf-efc56ed4a6ae.png">

<img width="421" alt="Screenshot 2023-03-14 at 15 55 37" src="https://user-images.githubusercontent.com/1372328/225041460-e4d7663a-94f4-44ca-9736-17354ab9f604.png">

**Environment (please complete the following information):**
 - Kubernetes: v1.26.2
 - Argo: v3.4.5
 - Argo Events: v1.7.6

**Additional context**
I have argo-workflows and argo-events deployed into one namespace via app-of-apps form another app-of-apps
```
lab03:
  - argo-workflows-apps:
       - argo-workflows
       - argo-events
``` 
As investigation shows, there is at least a frequent configmap update for leader election and this triggers reconciliation of all chain of these apps

I tried to add ignore for managed fields to argocd config, but it seems to have no effect
```
    resource.customizations.ignoreDifferences.all: |
      managedFieldsManagers:
      - kube-controller-manager
      - argo-events
```

also tried to ignore specifc configmap in all apps

finally in the AppProject, i ignored the configmap at all with
```
  orphanedResources:
    warn: true
    ignore:
      - kind: ConfigMap
        name: argo-events-controller
```
Configmap is gone from Argo UI, but looks it has no effect on reconciliations

Also configmap is only resource i _noticed_ to be frequently updated, maybe there are other updates I should ignore?
Unsure how to proceed

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by noroutine** [comment]
so small update to this, i tracked it to the https://github.com/argoproj/argo-cd/issues/8100 and was able to workaround the issue via moving argo-events to separate project and commenting out orphan tracking as per comment here https://github.com/argoproj/argo-cd/issues/8100#issuecomment-1111520296

In the end reconciliations stopped, however i'll keep the bug at your discretion. Via audit logs i found that reconciliations are caused by updates to above configmap to both managed fields and annotations. I think, if not completely avoiding configmap updates, the solution would be to limit updates to just managed fields

**Comment by whynowy** [comment]
@noroutine - the ConfinMap `argo-events-controller` is used for controller HA (leader election), this is a very common use case for k8s applications to achieve high availability. To my understanding, this should be tacked by argo-cd.

However, if you want to disable HA for Argo Events controller (with which you won't see the configmap changes), you can add `--leader-election=false` to the start args.

**Comment by noroutine** [comment]
Hi @whynowy i think it would make sense at least to update configmap during leader changes only, rather than updating annotations with timestamps every few seconds

But you are right this is not issue isolated to argo-events, so makes sense to close it

Thanks for the hint about parameter!
