### ISSUE TITLE
Argo Events docker image uses an old version of Argo CLI

### ISSUE THREAD

**Issue by AdrianSkierniewski** [argoproj/argo-events#2581]
**Describe the bug**
Argo events docker image uses an old version of Argo CLI, which causes the issue when submitting a template that contains `when` statement with an expression.  This behavior was added in Argo v3.4.2

```
Failed to submit workflow: templates.start when expression doesn't support 'expr' format '{{='. 'Wh
en' expression is only support govaluate format {{
```

**To Reproduce**
Create a sensor with workflow-trigger that uses `workflowTemplateRef` to reference the template that includes when statement with expression `{{=`

**Expected behavior**
I'd expect that I can submit all workflows that are supported by argo workflows server through argo events workflow trigger.

**Environment:**
 - Kubernetes: v1.25.4
 - Argo: v3.4.4
 - Argo Events: latest

**Additional context**
It looks like this version hasn't been updated for some time https://github.com/argoproj/argo-events/blob/master/Dockerfile#L11

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by AdrianSkierniewski** [comment]
Any plans to do this upgrade before the next release?

**Comment by daniel-codefresh** [comment]
@AdrianSkierniewski The upgrade to v3.4.8 should now be present in `latest` tag. Hopefully it will be included in the next stable release.
