### ISSUE TITLE
"Make start" doesnt work with ARM 

### ISSUE THREAD

**Issue by eduardodbr** [argoproj/argo-events#2588]
**Describe the bug**

I'm trying to test my local changes, however, the command `make start` fails if executed on ARM architecture. It seems easy to fix the issue, it is only necessary to check if the arch is ARM and build with `dist/argo-linux-arm64` instead of `dist/argo-linux-amd64`.  Should I open a PR? 

**To Reproduce**
Execute `make start` in a machine with ARM architecture. 

**Expected behavior**
It should build the image in order to do local testing.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@eduardodbr - thanks! Appreciate if you could submit another PR for it.
