### ISSUE TITLE
Add filters for signals

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#26]
**Is your feature request related to a problem? Please describe.**
We need to add a filtering capability so that a user can apply the filter the signal payload.

**Describe the solution you'd like**
JQ Filter looks like a good candidate for this. 
https://stedolan.github.io/jq/manual/
https://github.com/savaki/jq

**Comment by vicaire** [comment]
Will this support filtering events from GCS/S3 based on the name of the file that was created in GCS/S3?

**Comment by magaldima** [comment]
Yes, this feature should be generic enough to support filtering by json fields.. given that you can marshal the content/payload of an event, you should be able to filter it.
