### ISSUE TITLE
Sensor not getting all events from EventSource

### ISSUE THREAD

**Issue by akunafin** [argoproj/argo-events#2620]
### Discussed in https://github.com/argoproj/argo-events/discussions/2612

<div type='discussions-op-text'>

<sup>Originally posted by **akunafin** May 11, 2023</sup>
I've created a GitHub EventSource listening for release events. In GitHub, when I create a new release, I see it generates and sends 3 events at the same time:
- release.released
- release.created
- release.published

I see that all 3 events have been successfully delivered and in the EventSource logs I see "succeeded to publish an event" message for each of them. However, in the sensor logs I see only the first event, while other 2 events are missing. Also I see that trigger was executed only once. 
Could you please help me understand what am I missing here and how to make all 3 events to trigger a task.</div>

**Comment by jkldrr** [comment]
We are currently seeing a similar behaviour with our argo-events 1.7.6 and NATS EventBus Setup. We have 5 Sensors that listen to the same `eventSourceName`, `eventName` and have the same `filter`, but the number of workflows triggered for each Sensor is different. Are there any limitation or things to consider?
