### ISSUE TITLE
The Try in the docs is broken:

### ISSUE THREAD

**Issue by fabltd** [argoproj/argo-events#2649]
This link does not work:

[Access the demo environment](https://workflows.apps.argoproj.io/event-flow/argo?showWorkflows=true) (login using GitHub)

Result is 
```

502 Bad Gateway
nginx
```

**Comment by whynowy** [comment]
Thanks @fabltd !

**Comment by arcud** [comment]
FYI https://workflows.apps.argoproj.io/ is resulting in a 503 again
