### ISSUE TITLE
sensor s3 trigger source fails with nil pointer reference

### ISSUE THREAD

**Issue by robintanner** [argoproj/argo-events#267]
When adding a sensor trigger source for s3 I get a nil pointer reference error in the logs for the pod that is created when the trigger is invoked. This same trigger works fine when the workflow is inline. The inline workflow is pulling from the same s3 bucket, and to verify it's not a permission issue, I've granted admin permissions in the namespace to the argo-events-sa service account.

Here is my trigger:

`
          s3:
            bucket:
              name: s3bucket
              key: dev/workflows/unit_test_recent_records-nested-steps.yaml
            endpoint: minio-service.argo-events:9000
            insecure: true
            accessKeySecret:
              name: metadata-creds
              key: accessKey
            secretKeySecret:
              name: metadata-creds
              key: secretKey
`

![image](https://user-images.githubusercontent.com/13090419/55647966-dbbe4680-5793-11e9-8391-9a9529b3c5ce.png)

Here is the error 

`
2019-04-05T18:05:04Z | info  | msg: sensor state updated successfully |  phase:Active sensor-name:calendar-sensor-recent-records
2019-04-05T18:05:04Z | info  | msg: successfully persisted sensor resource update and created K8s event |  sensor-name:calendar-sensor-recent-records
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1192067]

goroutine 20 [running]:
github.com/argoproj/argo-events/store.GetCredentials(0x16285a0, 0xc000482000, 0xc00038e000, 0xb, 0xc00048ac90, 0x40cd0d, 0x1405a80, 0xc000412900)
        /home/vaibhav/go/src/github.com/argoproj/argo-events/store/creds.go:40 +0x47
github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).executeTrigger(0xc00043e700, 0xc00048ac30, 0x0, 0x0, 0x0, 0xc0002661e0, 0x1, 0x1, 0x1, 0x0)
        /home/vaibhav/go/src/github.com/argoproj/argo-events/sensors/trigger.go:203 +0xa8
github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).processTriggers(0xc00043e700)
        /home/vaibhav/go/src/github.com/argoproj/argo-events/sensors/trigger.go:114 +0x2aa
github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).processUpdateNotification(0xc00043e700, 0xc0003b0a80)
        /home/vaibhav/go/src/github.com/argoproj/argo-events/sensors/event-handler.go:111 +0x9db
github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).WatchEventsFromGateways.func1(0xc00043e700)
        /home/vaibhav/go/src/github.com/argoproj/argo-events/sensors/event-handler.go:186 +0x5a
created by github.com/argoproj/argo-events/sensors.(*sensorExecutionCtx).WatchEventsFromGateways
        /home/vaibhav/go/src/github.com/argoproj/argo-events/sensors/event-handler.go:184 +0x54
`

**Comment by VaibhavPage** [comment]
That's because `s3` configuration is not correct. There are keys called `accessKeySecret` and `secretKeySecret`. 

Have a look at this example https://github.com/argoproj/argo-events/blob/2a5f965ff704bab535e6a753d999232b9b00b9e5/examples/sensors/context-filter-webhook.yaml#L26
