### ISSUE TITLE
Tutorial does not work with helm

### ISSUE THREAD

**Issue by soujiro32167** [argoproj/argo-events#272]
**Describe the bug**
After installing argo-events with helm in the `argo-events` namespace, no pod is created when applying the `Gateway`

**To Reproduce**
1. On a GKE Kubernetes cluster
2. `helm install argo/argo-events --name argo-events --namespace argo-events`
3. `kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/gateways/webhook-gateway-configmap.yaml`
4.  `kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/examples/gateways/webhook-http.yaml`
5. Nothing happens - no gateway pod is created
 
**Expected behavior**
A gateway pod and service should be created

*Note:* following the https://github.com/argoproj/argo-events#using-kubectl installation does get the gateway and sensors pods created

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**

**Comment by VaibhavPage** [comment]
Helm chart is out of date. Can you upgrade the chart to v0.9?

**Comment by VaibhavPage** [comment]
I'll update the chart asap.

**Comment by soujiro32167** [comment]
Thanks!

**Comment by norbjd** [comment]
Just facing the same issue, except that I'm using the newest yaml files in the tutorial :

2. `kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/webhook.yaml`
3. `kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/gateways/webhook.yaml`

@VaibhavPage have the chart been updated ?
