### ISSUE TITLE
Allow Jetstream have a replica of 1

### ISSUE THREAD

**Issue by joelcomp1** [argoproj/argo-events#2743]
**Is your feature request related to a problem? Please describe.**
When we run Argo Events on a ARMv8 embedded device as a single node, it doesn't make sense to run Jetstream as a replica set of 3 containers for resource consumption stand point.  We would like to set replica set of 1 in these cases 

**Describe the solution you'd like**
Allow you to create a Jetstream event bus with replicas of 1

**Describe alternatives you've considered**
Use Kafka

**Additional context**
Current when I set replica set to 1 I get this error:

{"level":"error","ts":1691758787.683924,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:91","msg":"validation failed","namespace":"argo","eventbus":"default","error":"invalid spec: a jetstream eventbus requires at least 3 replicas","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:91\ngithub.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:56\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
We can make it possible - default replica number is still 3, but setting to 1 is possible.

Appreciate if anyone wants to help on it.

**Comment by joelcomp1** [comment]
I can a crack at making the change and test it out locally and then submit a merge request.

**Comment by ondrejmo** [comment]
@joelcomp1 Is there any ETA on this feature? I have a similar use-case and I can test it as well once there is some alpha version. Thank you

**Comment by joelcomp1** [comment]
Sorry was working on it but got side tracked. I have the event bus part done but now ssue is the sensors / event sources configure the Jetstream stream with a assumed replica of 3 so need to figure that part out to close it out

**Comment by joelcomp1** [comment]
@ondrejmo put a PR in for this today, give it a test if you are able to but i validated it both locally with replica of 1 and 3
