### ISSUE TITLE
Adding sprig all functions to templates

### ISSUE THREAD

**Issue by kync** [argoproj/argo-events#2766]
**Is your feature request related to a problem? Please describe.**
I would like to use spring nonhermetic functions in sensors, specially uuidv4. 
**Describe the solution you'd like**
We are adding only hermetic sprig functions to template, adding hermetic sprig functions will be the solution.
**Describe alternatives you've considered**
No alternatives found If I want to use `uuidv4` function in the sensor.

**Additional context**
I don't know the idea of not adding nonhermetic functions to sensors, If there is no real cases for that, would be great to add all sprig functions to sensors.

https://github.com/argoproj/argo-events/blob/a760bfde222c717f068d4ab111f1ddfe2e3f4ce2/sensors/triggers/params.go#L278C2-L278C2

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by kync** [comment]
I can create the PR if there is no issue adding hermetic functions into the templates.

**Comment by whynowy** [comment]
> I can create the PR if there is no issue adding nonhermetic functions into the templates.

You are welcome to do so, thanks!
