### ISSUE TITLE
Script filters do not work as described

### ISSUE THREAD

**Issue by unredundant** [argoproj/argo-events#2767]
**Describe the bug**
Hey, pretty simple one... as far as I can tell, [script filters](https://argoproj.github.io/argo-events/sensors/filters/script/) as described in the docs simply don't work.  

Even the example on that page doesn't seem to work.

**To Reproduce**
Follow the instructions on that doc page.  Will not run even for the payload designated as "valid"

**Expected behavior**
Filter should pass for valid payloads

**Screenshots**
As you can see, I created the resources, port forwarded the service, and then posted the two example payloads (one valid, one invalid, as per the filter).

<img width="1143" alt="CleanShot 2023-08-23 at 08 45 58@2x" src="https://github.com/argoproj/argo-events/assets/5607577/51af5e27-2491-4b00-afd1-17a4aecd2648">

However, in the events dashboard, you can see that no workflows were run

<img width="1871" alt="CleanShot 2023-08-23 at 08 46 56@2x" src="https://github.com/argoproj/argo-events/assets/5607577/ef8f5e49-3987-48b3-aa33-992b08f054d6">

**Environment (please complete the following information):**
 - Kubernetes: 1.27.4
 - Argo Workflows 3.4.9
 - Argo Events: Unsure (presumably latest-ish, recent helm chart installation)

**Additional context**
None

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by unredundant** [comment]
Ok, I figured out the issue... though, I'm not familiar enough with YAML syntax to say exactly what's up here. 

In the example, the script is show as follows 

```yaml
filters:
  script: |-
    if event.body.a == "b" and event.body.d.e == "z" then return true else return false end
```

This doesn't work.

However, if you remove the hyphen behind the pipe like so

```
filters:
  script: |
    if event.body.a == "b" and event.body.d.e == "z" then return true else return false end
```

Then the script succeeds.

[This](https://docs.paperspace.com/gradient/workflows/using-yaml-for-data-science/#multi-line-commands) random resource seems to indicate that pipedash _is_ syntactically correct, so I'm not sure why this would be causing the issue.

**Comment by unredundant** [comment]
docs on how to inspect delivered payloads would be very useful.  really hard to piece together issues with these sensors.

**Comment by whynowy** [comment]
@unredundant - Glad you have figured out what happened, but it is also weird to me that it didn't work at the beginning...
