### ISSUE TITLE
"Getting Started" examples resource link is broken

### ISSUE THREAD

**Issue by bells17** [argoproj/argo-events#277]
**Describe the bug**

"Getting Started" examples resource link is broken
    

**To Reproduce**
1. open https://github.com/argoproj/argo-events/blob/b68b94abb38b8318bd97c6a0a86873e2accad07f/docs/index.md#get-started
2. execute `kubectl apply -n argo-events -f ~` commands that are written on "Getting Started"
3. Occured 404 error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by VaibhavPage** [comment]
please check https://argoproj.github.io/argo-events/getting_started/
