### ISSUE TITLE
Configure External EventBus

### ISSUE THREAD

**Issue by joshadambell** [argoproj/argo-events#2836]
**Is your feature request related to a problem? Please describe.**
I want to run argo events in all of my clusters for watching K8s resources but I don't want or need an EventBus to also run in every cluster.

**Describe the solution you'd like**
I would like a way of configuring an external event bus vs requiring an in cluster local event bus. This would allow me to have a "master" event bus for sending all events to.

**Describe alternatives you've considered**
We've looked at alternative products like knative eventing and expanding our current watcher apps.

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by gokulav137** [comment]
Is this related to #2462.

**Comment by joshadambell** [comment]
Yes I believe that is a similar ask. Thanks!
