### ISSUE TITLE
failed to get existing webhook with id

### ISSUE THREAD

**Issue by Erik-Securenative** [argoproj/argo-events#287]
**Describe the bug**
After argo github gateway create github webhook and the pod restarted he cant get from github api  the webhook error="failed to get existing webhook with id 1. err: GET https://api.github.com/repos/XXXX/XXXX/hooks/1: 404 Not Found []" event-source=example

i got to this after my webhook stoped to work after pod restart (get timeout)

**To Reproduce**
setup github example
restart gateway
check gateway logs

**Expected behavior**
no error in logs and webhook keep working

**Additional context**
to bypass it delete to webhook and recreat it

**Comment by VaibhavPage** [comment]
Can you confirm that the hook with ID with `1` is created? Because the gateway will always try first to register the webhook with the given ID

**Comment by Erik-Securenative** [comment]
It was created and after i checked with the api it was different Id 116345 
So i change to this id in my config 
Why its not the same id i gave him?

**Comment by Erik-Securenative** [comment]
i dont understand why we give id
the id is internal or its github id?
after my pod restart i get failed to get existing webhook with id on all

**Comment by devstein** [comment]
Also just encountered this issue

**Comment by k** [comment]
Why is an id required? I thought the webhook was created dynamically?
