### ISSUE TITLE
Only allowing EventBus to be from jetstream

### ISSUE THREAD

**Issue by alexlatchford** [argoproj/argo-events#2905]
**Describe the bug**

We'd like to lock down Argo Events `EventBus` to just allow clients to use `jetstream` but the `ValidateConfig` method enforces at least one version of each [here](https://github.com/argoproj/argo-events/blame/master/controllers/config.go#L125).

**To Reproduce**
1. Update the `argo-events-controller-config` `ConfigMap` to remove the `eventBus.nats.versions` array.
2. Redeploy the `controller-manager`, keep some items in the `eventBus.jetstream.versions` array.
4. See error `no stan versions were provided in the controller config` in the `controller-manager` pod logs.

**Expected behavior**

No error, should be possible to not give the option to run `nats` as the `EventBus`.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: v1.24 (whatever the latest EKS version is 😅)
 - Argo Events: v1.8.0

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by ryancurrah** [comment]
Seems this should not be closed, nats-streaming is no longer maintained. 

> The NATS Streaming Server is being deprecated. Critical bug fixes and security fixes will be applied until June of 2023. NATS enabled applications requiring persistence should use [JetStream](https://docs.nats.io/nats-concepts/jetstream).

https://github.com/nats-io/nats-streaming-server
