### ISSUE TITLE
Invalid EventSource resource can cause argo-events-controller-manager to fail to start

### ISSUE THREAD

**Issue by erikschul** [argoproj/argo-events#2910]
**Describe the bug**
When Argo Events is installed cluster-wide, the operation can fail across the cluster if an object in some namespace is invalid.

**To Reproduce**

1. new cluster
2. use argocd to install argo events
3. some namespace contains an EventSource with invalid YAML
4. argo-events-controller-manager fails to start

This causes the error:
```
reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.EventSource: json: cannot unmarshal string into Go struct field EventSourceSpec.items.spec.webhook of type v1alpha1.WebhookEventSource
```

**Expected behavior**
- Invalid resource should be caught by admission check.
- controller-manager should continue normal operations, but log the error

**Environment (please complete the following information):**
 - Kubernetes: v1.28.1
 - Argo: 5.45.1
 - Argo Events: 2.4.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@erikschul - do you have the optional validating webhook installed? 

We should expose the full CRD spec.
