### ISSUE TITLE
Support multiple dependencies using the same datasource in sensor

### ISSUE THREAD

**Issue by MartinForReal** [argoproj/argo-events#293]
**Is your feature request related to a problem? Please describe.**
I need to watch changes of two k8s resource in the same kind( e.g. two deployment resource) and deploy other resource if the resource which is being watched is ready. 

**Describe the solution you'd like**
Support multiple dependencies using the same datasource in sensor 

**Describe alternatives you've considered**
define multiple datasource and use circuit to merge result（which is not supported because nodeid is  named using datasource-sensor format）

**Additional context**
no

**Comment by ptemmer** [comment]
+1
Not sure if I fully understand what you mean by merging, however I have a use case that also applies I think.
I have a webhook as datasource which is being used by Github on the following events:
- branch pull request
- branch push
- tag created

Depending on the event, the trigger to be executed is slightly different. Using the 'when' parameter makes this possible. However, I'm unable to create a circuit with different dependencyGroups, as the dependency source is the same for all events.

**Comment by whynowy** [comment]
I believe this is now supported. Please reopen it or create a new issue if there's a disagreement.
