### ISSUE TITLE
Forward headers for HTTP events

### ISSUE THREAD

**Issue by logicfox** [argoproj/argo-events#294]
**Is your feature request related to a problem? Please describe.**
The current implementation of the HTTP gateway only forwards the received payload to sensors. There are many cases where the incoming headers could be useful in sensor triggered workflows/resources. 

**Describe the solution you'd like**
A way to receive the headers received by the HTTP gateway to sensors. I suppose this could be one of the trigger params.

Usecase: I'm trying to use Argo-events to trigger workflows in a CI usecase. The source of the webhook is Bitbucket Cloud, which transmits the event type (`repo:push`) as a header to webhook receivers. The same data is also encoded in the payload, but as a JSON key requiring non-trivial parsing. This can be avoided if the headers are transmitted to the sensor along with the payload, making the trigger workflow simple.

**Comment by VaibhavPage** [comment]
Makes sense, I will add it to the next release

**Comment by ptemmer** [comment]
Just ran into this. GitHub webhooks put the type of event in a header called X-GitHub-Event

**Comment by VaibhavPage** [comment]
available in v0.12 and onwards.
