### ISSUE TITLE
can't delete eventbus、eventsource、eventsensor

### ISSUE THREAD

**Issue by 985958118** [argoproj/argo-events#2962]
argo event verson is v1.8.1

When I try to delete an event source or event sensor or event bus, I find that they get recreated.
cmd like this:
kubectl delete deployment -n argo-events workflow-pod-event-source-eventsource-zltjg

Setting the finalizers to [] was ineffective; the finalizers value for the newly auto-created eventbus still defaults to "eventsource-controller"

**Comment by whynowy** [comment]
Do you have the controller running?
