### ISSUE TITLE
Argo Events Controller trying to delete the event bus continuously 

### ISSUE THREAD

**Issue by srinivin** [argoproj/argo-events#2970]
**Describe the bug**
While checking the argo events controller logs it is trying to delete the event bus every ~10-15 mins.
It is failing delete for expected reasons due to attached sensors and event sources.
Not sure why it is trying to delete the event source consistently,
Argo Events Version : 1.8.1

{"level":"info","ts":1704899004.2813487,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:76","msg":"**deleting eventbus**","namespace":"test-argo-events","eventbus":"default"}
{"level":"error","ts":1704899004.2814589,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:80","msg":"failed to uninstall","namespace":"test-argo-events","eventbus":"default","error":"can not delete an EventBus with 5 EventSources connected","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:80\ngithub.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:56\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1704899004.2814937,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:58","msg":"reconcile error","namespace":"test-argo-events","eventbus":"default","error":"can not delete an EventBus with 5 EventSources connected","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:58\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1704899659.6526575,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:76","msg":"**deleting eventbus**","namespace":"test-argo-events","eventbus":"default"}
{"level":"error","ts":1704899659.652761,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:80","msg":"failed to uninstall","namespace":"test-argo-events","eventbus":"default","error":"can not delete an EventBus with 5 EventSources connected","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:80\ngithub.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:56\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1704899659.6527884,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:58","msg":"reconcile error","namespace":"test-argo-events","eventbus":"default","error":"can not delete an EventBus with 5 EventSources connected","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:58\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1704900659.6635575,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:76","msg":"**deleting eventbus**","namespace":"test-argo-events","eventbus":"default"}
{"level":"error","ts":1704900659.6637022,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:80","msg":"failed to uninstall","namespace":"test-argo-events","eventbus":"default","error":"can not delete an EventBus with 5 EventSources connected","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:80\ngithub.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:56\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1704900659.6637373,"logger":"argo-events.eventbus-controller","caller":"eventbus/controller.go:58","msg":"reconcile error","namespace":"test-argo-events","eventbus":"default","error":"can not delete an EventBus with 5 EventSources connected","stacktrace":"github.com/argoproj/argo-events/controllers/eventbus.(*reconciler).Reconcile\n\t/home/runner/work/argo-events/argo-events/controllers/eventbus/controller.go:58\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

**To Reproduce**
1. Check argo-events controller pod logs

**Expected behavior**
There shouldnt be any attempt of deleting the event bus unless requested.

**Environment (please complete the following information):**

 - Argo Events: [e.g. v1.0.0] : V1.8.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Is your EventBus object marked for deleting (`deletionTimestamp` has value)?
