### ISSUE TITLE
Ability to use IAM roles to establish AWS session for SQS and SNS event sources.

### ISSUE THREAD

**Issue by hemildesai** [argoproj/argo-events#298]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the SQS Gateway in an EKS cluster. I'm using kiam to manage IAM roles. So the Gateway has the necessary IAM role to access the SQS queue. Yet I'm unable to use the IAM role as it is mandatory to specify the `accessKey` and `secretKey` in the SQS event source.

**Describe the solution you'd like**
I want the ability to create an SQS event source without having to specify the access credentials. The Go AWS SDK should fall back to the IAM role of the pod to establish a session.

**Describe alternatives you've considered**
An alternative is to write a custom Gateway, but I feel like this is a feature that should be available since a lot of the users might be using EKS or K8s clusters in AWS with IAM roles mounted on the pods.

**Comment by VaibhavPage** [comment]
Understood. I will add it to the next release.

**Comment by hemildesai** [comment]
Oh awesome. Let me know if I can help with that!
