### ISSUE TITLE
Sensors in different namespace than gateway - communication error

### ISSUE THREAD

**Issue by automagic** [argoproj/argo-events#299]
If I setup a whalesay example sensor in a different namespace than the Gateway, i get an error like this dispatching:

WARN[2019-06-10 21:22:37] failed to dispatch event to sensor watcher over http. communication error  error=“Post http://aws-sqs-sensor-whalesay-svc:9300/: dial tcp: lookup aws-sqs-sensor-whalesay-svc on 10.100.0.10:53: no such host” sensor-name=aws-sqs-sensor-whalesay

**Comment by VaibhavPage** [comment]
This error makes sense. The gateway should use .svc.local to reach sensor service in another namespace. I'll add the fix in the next release.

**Comment by VaibhavPage** [comment]
#317
