### ISSUE TITLE
JWT Bearer Tokens for Webhook Gateway

### ISSUE THREAD

**Issue by pplavetzki** [argoproj/argo-events#303]
**Is your feature request related to a problem? Please describe.**
Enhance the existing webhook gateway to provide authorization and authentication using Bearer JWTs.  

**Describe the solution you'd like**
The implementation should allow the plugging in of existing middleware to authenticate and authorize hitting the defined and exposed endpoints.  By passing the standard Authorization header and value of Bearer XXXX.XXX.XXX the gateway should somehow offload the JWT authentication and authorization to the middleware.

The gateway should not be responsible for any user management.

Should be able to define in the event source whether or not the individual endpoints are to be secured using Bearer JWTs.

Should the middleware be responsible for 100% of Authentication and Authorization of the api request, the gateway really only be a "passthrough" to the middleware?  Or should the gateway take on some of the responsibility of decoding and verifying the JWT?

**Describe alternatives you've considered**
Considered creating a new custom gateway to build this feature.

**Comment by pplavetzki** [comment]
@VaibhavPage glad to help out if you provide some guidance on how you want this implemented.

**Comment by VaibhavPage** [comment]
@pplavetzki we now support authentication using basic auth check for all `webhook` type eventsources #821
