### ISSUE TITLE
ArgoWorkflow trigger with submit-from operation throws errors even though it submits the template

### ISSUE THREAD

**Issue by Nicarim** [argoproj/argo-events#3033]
**Describe the bug**
I'm trying to submit WorkflowTemplate through a Sensor using ArgoWorkflow trigger. The Workflow gets indeed run, but it throws following errors
```
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m Name:                hello-world-tmpl-42w72
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m Namespace:           argo
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m ServiceAccount:      unset
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m Status:              Pending
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m Created:             Thu Feb 22 21:42:51 +0000 (now)
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m Progress:
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m {"level":"error","ts":1708638171.9234018,"logger":"argo-events.sensor","caller":"sensors/listener.go:379","msg":"Failed to execute a trigger","sensorName":"hello-world-sensor","error":"failed to execute trigger, wor
kflows.argoproj.io \"hello-world-tmpl\" not found","triggerName":"argo-workflow-trigger","triggeredBy":["test-dep"],"triggeredByEvents":["34313965333736322d326235642d343631652d393562342d353036376639646437386261"],"stacktrace":"github.com/argoproj/argo-events/sens
ors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:379\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:360"}
hello-world-sensor-sensor-dh6jd-ddb6f7657-2qd2m {"level":"error","ts":1708638171.9234366,"logger":"argo-events.sensor","caller":"sensors/listener.go:364","msg":"Failed to execute a trigger","sensorName":"hello-world-sensor","error":"failed to execute trigger, wor
kflows.argoproj.io \"hello-world-tmpl\" not found","triggerName":"argo-workflow-trigger","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:364"}

```

**To Reproduce**
1. Create WorkflowTemplate
2. Create Sensor that triggers created workflowTemplate
3. It should submit the Workflow successfully, but subsequently fail to observe it.

**Expected behavior**
No errors should be thrown after successfully running `submit-from` operation

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes:  1.27.1-k3s
 - Argo: 3.5.4
 - Argo Events: 1.9.1

**Additional context**
I've narrowed it down to this line: https://github.com/argoproj/argo-events/blob/master/sensors/triggers/argo-workflow/argo-workflow.go#L203
It tries to get a workflow object, based on workflowTemplate name, which obviously won't work because created Workflow object name has randomized suffix. I imagine it should use the same labels it is using for `submit` to find the Workflow in `submit-from` operation. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by mstrange96** [comment]
I've run into this issue as well.

**Comment by joebowbeer** [comment]
Permalink to code:
https://github.com/argoproj/argo-events/blob/0d31a3e9fe5297ae1cdeebc74ef3b2fc967200ea/pkg/sensors/triggers/argo-workflow/argo-workflow.go#L202-L204

**Comment by joebowbeer** [comment]
/notstale

Can this be reopened?

**Comment by jmichaelsmotus** [comment]
We have also run into this issue when trying to put some monitoring in place. This effectively makes the failed events metric coming out of a Sensor totally useless. Can this be reopened?

**Comment by KrisF-Midnight** [comment]
It's still an issue and it shouldn't be stale. As above, workflow gets executed but 2x error is thrown:

```
{"level":"error","ts":1732116150.2619948,"logger":"argo-events.sensor","caller":"sensors/listener.go:379","msg":"Failed to execute a trigger","sensorName":"test-sensor","error":"failed to execute trigger, workflows.argoproj.io \"cron-e2e-test\" not found","triggerName":"call-e2e-test","triggeredBy":["github-eventsource-dep"],"triggeredByEvents":["31336137653437312d653436632d343664662d393130662d356565376439613731343065"],"stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).triggerWithRateLimit\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:379\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).triggerActions.func1\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:360"}
```

**Comment by Nicarim** [comment]
This is definitely not stale. I feel like this project is kinda abandoned.

**Comment by ianmuge** [comment]
It would be nice to reopen this
