### ISSUE TITLE
Trailing whitespace in tokenFile causes `net/http: invalid header field 

### ISSUE THREAD

**Issue by charlesa101** [argoproj/argo-events#306]
Describe the bug
Github Gateway pod unable to create webhook because of trailing whitespace that gets appended to the webhook token in the header
Is this a bug? YES
Is there a deployment method to prevent it?

Environment (please complete the following information):

OS: macOS Mojave 10.14.4
minikube: v1.0.1
Helm: v2.14.0
argo workflow: v2.2.1
Argo-events: v0.9.2

**Comment by whynowy** [comment]
it's fied.
