### ISSUE TITLE
Gitlab gateway always creates "PushEvents"

### ISSUE THREAD

**Issue by ironreality** [argoproj/argo-events#307]
**Describe the bug**
Gitlab gateway always creates "PushEvents" along with other specified event type.

**To Reproduce**
Create the [example](https://github.com/argoproj/argo-events/blob/master/examples/event-sources/gitlab.yaml) event source with event field equal "TagPushEvents"

**Expected behavior**
The gitlab gateway creates the exact event type solely without additional "PushEvents"

**Screenshots**
<img width="1234" alt="Pasted_Image_7_9_19__6_03_PM" src="https://user-images.githubusercontent.com/3636109/60900512-fa414b80-a274-11e9-9137-a0112d22d76e.png">

**Environment (please complete the following information):**
 - argo-events version: 0.9.2
 - argo-events Helm chart version: 0.4.2
 - Gitlab version: 11.11.4
 - Kubernetes version: 1.14.1

**Comment by VaibhavPage** [comment]
I'll take a look
