### ISSUE TITLE
Support Slack Interactive messages

### ISSUE THREAD

**Issue by logicfox** [argoproj/argo-events#308]
**Is your feature request related to a problem? Please describe.**
Slack's new Block messaging composition allows adding interactive elements to messages. A user interacting with these elements causes Slack to trigger [a POST request](https://api.slack.com/messaging/interactivity/enabling) to a configured endpoint. This request can be the basis of triggering a workflow.

**Describe the solution you'd like**
When a user interacts with an interactive message in Slack (say, clicks a button), a workflow should be triggered.

**Describe alternatives you've considered**
This can be achieved with a http webhook gateway, but Slack requires that interactive message actions be acknowledged within 3 seconds. A new gateway or retrofitting the existing Slack gateway would quite easily address this usecase.

**Comment by VaibhavPage** [comment]
Interesting. Are these new Block messaging events same as regular slack events?

**Comment by logicfox** [comment]
Not quite. The current Slack gateway does not parse payloads sent from block elements. There are two separate APIs - the Events API that the gateway currently supports and the interaction API as documented [here](https://api.slack.com/messaging/interactivity/enabling)

> A request payload is both a way of notifying your app about an interaction and a bundle of information containing the where and when (and many other Ws) of the interaction. It is vital to the interaction process, so your app has to be able to understand it.
> The request will be made to your specified request URL in an HTTP POST. The body of that request will contain a payload parameter. Your app should parse this payload parameter as JSON.

**Comment by logicfox** [comment]
I think there may be more to it. I changed the Slack gateway code to accommodate for this event type, but it looks like the expected interaction events payload is different in different parts of the Slack library. The parser in slackevents seems to only handle attachment type events, not block events.

**Comment by VaibhavPage** [comment]
looks like it means you would need a separate gateway for interactive events

**Comment by logicfox** [comment]
@VaibhavPage I got it work with the existing library. I made PR #324 to merge this back to master.
