### ISSUE TITLE
Too old resource version: 25098 (25860)

### ISSUE THREAD

**Issue by theomessin** [argoproj/argo-events#318]
Keep getting this:

```
ERROR: logging before flag.Parse: W0726 13:20:05.478764 1 reflector.go:341] github.com/argoproj/argo-events/controllers/gateway/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 25098 (25860)
```

**Comment by VaibhavPage** [comment]
These are K8s debug logs, these are safe to ignore.

**Comment by wreed4** [comment]
To restate this problem, i continually get these logs from the Application controller and when I get into this state, ArgoCD cannot refresh apps.  The UI hangs on syncing and refreshing until I delete the application controller pod.  This happens repeatedly and continuously.
