### ISSUE TITLE
Make job executors imagePullPolicy configurable

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo-events#32]
**Is your feature request related to a problem? Please describe.**
The sensor jobs executor has the imagePullPolicy of `PullIfNotPresent` hard-coded. This makes development difficult.

**Describe the solution you'd like**
It will be good if the imagePullPolicy for the executor is also made configurable similar to the properties likes executor image name, resources, etc.

**Describe alternatives you've considered**
Continuing the current way would require deleting the executor image everytime from all the nodes in the cluster to ensure that the image is pulled again which is cumbersome.

**Comment by magaldima** [comment]
Makes sense.
