### ISSUE TITLE
SFTP Event Source not Appearing as of v1.9.1

### ISSUE THREAD

**Issue by ekbaker7** [argoproj/argo-events#3210]
**Describe the bug**
When the SFTP Event Source is used ( https://github.com/argoproj/argo-events/blob/master/api/event-source.md#sftpeventsource ) the actual `SFTP` keyword/spec is not being registered when added to Argo. I have tried using both the example script in the Setup docs (https://github.com/argoproj/argo-events/blob/master/docs/eventsources/setup/sftp.md) and writing my own SFTP Event Source. 

Both times, the YAML can be uploaded to Argo just fine, but upon viewing the Spec in Argo the `SFTP` keyword and all underlying information is gone, and no Event Source can be found in the Event Flow. The sensor can still be created, but it seems to not actually check if the `SFTP` event source exists. 

**To Reproduce**
1. Either use the example setup YAML or create your own SFTP Event Source
2. Upload to Argo either via the GUI or Command Line
3. Navigate to your event source in the GUI and open the corresponding YAML
4. Notice that scrolling down to `spec` that the SFTP keyword and all underlying data is not present
5. Going to "Event Flow" shows that no Event Source was created either.

**Expected behavior**
SFTP Event Source is created, can be found under the `spec` in the yaml, and viewed in Event Flow. 

**Screenshots**
![image](https://github.com/user-attachments/assets/023618f4-80ce-4a7e-8c58-77c6896e898b)

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.30.2]
 - Argo: [e.g. v3.5.8]
 - Argo Events: [e.g. v1.9.1+]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by harinlee0803** [comment]
I'm facing the same issue. @ekbaker7 were you able to get the SFTP Event Source to show up in a previous version (like when it was first supported in [ v.1.8.1](https://github.com/argoproj/argo-events/releases/tag/v1.8.1))?
