### ISSUE TITLE
nats config fails when JS_KEY value starts with an integer

### ISSUE THREAD

**Issue by cushdan** [argoproj/argo-events#3231]
**Describe the bug**
`eventbus-default-js` pods fail to start if the randomly generated secret/eventbus-default-js-server "encryption" value starts with an integer. The error that is reported is:

> nats-server: variable reference for 'JS_KEY' on line 17 could not be parsed: Parse error on line 1: 'Expected a top-level value to end with a new line, comment or EOF, but got 'N' instead.'

**To Reproduce**
1. edit secret value for "encryption" to be a base64 encoded value of a key that starts with an integer. Example
`printf "384KNjNxieWe" | base64`
Mzg0S05qTnhpZVdl
2. delete eventbus pods so they restart
3. See error

**Expected behavior**
Pods should start

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: 1.29.6
 - Argo Events: v1.8.0

**Additional context**
Editing the cm/eventbus-default-js-config and adding double quotes around the $JS_KEY environment variable appears to fix the issue and allow the nats server to read the value as a string properly.

```
jetstream {
     key: "$JS_KEY"
```
https://github.com/argoproj/argo-events/blob/7b44edd366a35bd187edcbb86597ea67d50f47bc/controllers/eventbus/installer/assets/jetstream/nats.conf#L17

https://github.com/argoproj/argo-events/blob/7b44edd366a35bd187edcbb86597ea67d50f47bc/controllers/eventbus/installer/assets/jetstream/nats-cluster.conf#L17

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by corkupine** [comment]
Can we reopen this? Looks like the location of files has changed:
https://github.com/argoproj/argo-events/blob/master/pkg/reconciler/eventbus/installer/assets/jetstream/nats.conf
https://github.com/argoproj/argo-events/blob/master/pkg/reconciler/eventbus/installer/assets/jetstream/nats-cluster.conf

Would it help if we opened a PR?
