### ISSUE TITLE
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.

### ISSUE THREAD

**Issue by Nataliia5722** [argoproj/argo-events#3252]
**Describe the bug**
Hi Team! 
After upgrading to v1.9.2, getting the next error in Argo Events controller:
`[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 162 [running]:
	>  runtime/debug.Stack()
	>  	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc000d29540, 0x10?)
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/deleg.go:111 +0x32
	>  github.com/go-logr/logr.Logger.Info({{0x3f7e570?, 0xc000d29540?}, 0xc000df47a8?}, {0xc000b983f0, 0x61}, {0xc000e874a0, 0x6, 0x6})
	>  	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.4.1/logr.go:276 +0x72
	>  sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0xc000ca2280)
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/recorder/recorder.go:104 +0x1e7
	>  k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
	>  	/home/runner/go/pkg/mod/k8s.io/client-go@v0.29.0/tools/record/event.go:401 +0x11d
	>  created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher in goroutine 119
	>  	/home/runner/go/pkg/mod/k8s.io/client-go@v0.29.0/tools/record/event.go:387 +0x109`

I assume the issue is related to the breaking changes for controller-runtime in the 0.15.0 and higher release https://github.com/kubernetes-sigs/controller-runtime/issues/2622#issuecomment-1855819427

Please, let me know if any additional information is needed.

Thank you!

**To Reproduce**
1. Upgrade argo-events to the latest version 1.9.2

**Expected behavior**
No errors are present in the controller pod

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.30.3]
 - Argo: [e.g. v2.12.0]
 - Argo Events: [e.g. v1.9.2]

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by EugeneLugovtsov** [comment]
@whynowy @edlee2121 @jessesuen could you please help? we are using v1.9.2

<img width="1480" alt="Screenshot 2024-11-20 at 11 26 03" src="https://github.com/user-attachments/assets/ddf1f836-eda8-4dc7-9aa9-0f58dae2d898">

**Comment by Nataliia5722** [comment]
The issue has been reproduced in v1.9.3:
```go
{"time":"2024-11-28T07:34:44.057500661Z","level":"INFO","msg":"trying to resolve absolute path","path":"/etc/argo-events"}
{"time":"2024-11-28T07:34:44.057565973Z","level":"INFO","msg":"adding path to search paths","path":"/etc/argo-events"}
{"time":"2024-11-28T07:34:44.057570351Z","level":"INFO","msg":"attempting to read in config file"}
{"time":"2024-11-28T07:34:44.057573878Z","level":"INFO","msg":"searching for config in paths","paths":["/etc/argo-events"]}
{"level":"info","ts":1732779284.0586967,"logger":"argo-events.eventbus-controller","caller":"cmd/start.go:190","msg":"Starting controller manager","version":"v1.9.3"}
I1128 07:34:44.059030       1 leaderelection.go:250] attempting to acquire leader lease argo-events/argo-events-controller...
I1128 07:35:18.846554       1 leaderelection.go:260] successfully acquired lease argo-events/argo-events-controller
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 124 [running]:
	>  runtime/debug.Stack()
	>  	/opt/hostedtoolcache/go/1.22.9/x64/src/runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc000b51d40, 0x1)
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/log/deleg.go:111 +0x32
	>  github.com/go-logr/logr.Logger.Info({{0x41798b8?, 0xc000b51d40?}, 0x0?}, {0xc001556620, 0x62}, {0xc000e96cc0, 0x6, 0x6})
	>  	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.4.1/logr.go:276 +0x6e
	>  sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0xc000fe2008)
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/recorder/recorder.go:104 +0x1cf
	>  k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
	>  	/home/runner/go/pkg/mod/k8s.io/client-go@v0.29.0/tools/record/event.go:401 +0x126
	>  created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher in goroutine 27
	>  	/home/runner/go/pkg/mod/k8s.io/client-go@v0.29.0/tools/record/event.go:387 +0xff
```

**Comment by lanceatcollibra** [comment]
Any updates? I see it on the latest char 2.14.12

**Comment by rtoma** [comment]
The issue has been reproduced in v1.9.5.

Please reopen.

**Comment by Nataliia5722** [comment]
The issue has been reproduced in v1.9.6:

```
I0603 17:15:46.081116       1 leaderelection.go:257] attempting to acquire leader lease argo-events/argo-events-controller...
I0603 17:16:20.488013       1 leaderelection.go:271] successfully acquired lease argo-events/argo-events-controller
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 105 [running]:
	>  runtime/debug.Stack()
	>  	/opt/hostedtoolcache/go/1.24.2/x64/src/runtime/debug/stack.go:26 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc000c80680, 0x1)
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/log/deleg.go:111 +0x32
	>  github.com/go-logr/logr.Logger.Info({{0x43e09b8?, 0xc000c80680?}, 0xc000ad6150?}, {0xc000079ea0, 0x62}, {0xc000819c80, 0x6, 0x6})
	>  	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.4.2/logr.go:276 +0x6e
	>  sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*Provider).getBroadcaster.func1.1(0xc0008ae788)
	>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/recorder/recorder.go:104 +0x1c7
	>  k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
	>  	/home/runner/go/pkg/mod/k8s.io/client-go@v0.32.2/tools/record/event.go:418 +0x126
	>  created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher in goroutine 24
	>  	/home/runner/go/pkg/mod/k8s.io/client-go@v0.32.2/tools/record/event.go:404 +0xb2
```

**Comment by mmclane** [comment]
I just upgraded Argo Events to the latest helm chart 2.4.16 running argo-events:v1.9.7 and I am still seeing this in the logs.

Why is this not planned, and a stale bug?

<img width="1395" height="481" alt="Image" src="https://github.com/user-attachments/assets/6fdb97f0-ff8a-479a-bed4-1c469aeb4c3c" />

**Comment by kirrmann** [comment]
Also happens with argo-events 1.9.9
