### ISSUE TITLE
Argument list too long if step argument has a very long argument

### ISSUE THREAD

**Issue by dahuriner** [argoproj/argo-events#3281]
**Describe the bug**
We have some big workflows and we hit the following error:

`exec /bin/argo-events: argument list too long`

After digging a bit, we realized it's because our workflow is big. After deleting some tasks from the workflow, it started to work fine. I checked some issues on `argo-workflows` repo and I noticed that this issue(https://github.com/argoproj/argo-workflows/issues/12190) has been reported before and then eventually fixed on `argo-workflows`. I was thinking we should fix it in `argo-events` too. 

**To Reproduce**
1. Create a big workflow. You can duplicate more than 50 tasks, so you can hit the limit.
2. Publish it as a sensor.
3. Check `argo-events` log for that sensor.
4. You should see this error message: `exec /bin/argo-events: argument list too long`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: v1.30.2+k3s1
 - Argo: v3.4.11
 - Argo Events: v1.7.6

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Is this a `argoWorkflow` trigger? we can bump up to the fixed version in next release.

**Comment by b-erdem** [comment]
@whynowy Yes, we've argo workflows that gets triggered with events coming from argo-events.
