### ISSUE TITLE
Unable to delete cluster-scoped resources with the Kubernetes object trigger

### ISSUE THREAD

**Issue by tvandinther** [argoproj/argo-events#3300]
**Describe the bug**
When using the Kubernetes object trigger to delete a cluster-scoped resource (such as a persistent volume), the message `object not found, nothing to delete...` is logged.

**To Reproduce**
Delete any cluster-scoped resource (other than `namespace` or `node`) using the Kubernetes object trigger.

**Expected behavior**
The resource should be identified as cluster-scoped and found and deleted appropriately.

**Environment (please complete the following information):**
 - Kubernetes: v1.30
 - Argo Events: v1.9.1

**Additional context**
It is possible this issue affects operations other than `Delete`. I noticed that in [this part of the code](https://github.com/argoproj/argo-events/blob/e3ce354204708b0922b7b5b7bb57439d64d5b7eb/sensors/triggers/standard-k8s/standard-k8s.go#L43), only namespaces and nodes are listed as cluster-scoped resources. Following a static analysis of the code, I presume the namespace is [set to the sensor namespace](https://github.com/argoproj/argo-events/blob/e3ce354204708b0922b7b5b7bb57439d64d5b7eb/sensors/triggers/standard-k8s/standard-k8s.go#L141) and subsequently not found.

I'd expect that this issue is fixed by making the list exhaustive (for standard resources), or a new mechanism used to determine cluster-scoped resources so that cluster-scoped CRs can also be identified.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by tvandinther** [comment]
This may be fixed upstream if the dynamic client is amended to find cluster-scoped resources even when a namespace is set as per this issue: https://github.com/kubernetes/kubernetes/issues/111248

It also seems that this stale issue covers the same problem: https://github.com/argoproj/argo-events/issues/3132

**Comment by whynowy** [comment]
> This may be fixed upstream if the dynamic client is amended to find cluster-scoped resources even when a namespace is set as per this issue: [kubernetes/kubernetes#111248](https://github.com/kubernetes/kubernetes/issues/111248)
> 
> It also seems that this stale issue covers the same problem: #3132 

Would you like to submit a PR to add those (maybe not all but often used) cluster scope resources?

**Comment by tvandinther** [comment]
If you're happy with that approach I can submit the PR.
