### ISSUE TITLE
Resource doc page links to a 404 specification

### ISSUE THREAD

**Issue by jmhodges** [argoproj/argo-events#3301]
**Describe the bug**
All of the EventSource documentation pages have "specification" links that all 404.

For example, the page https://argoproj.github.io/argo-events/eventsources/setup/resource/ (which I believe is [this file](https://github.com/argoproj/argo-events/blob/master/docs/eventsources/setup/resource.md)) in the line:

```
Resource event-source specification is available [here](https://github.com/argoproj/argo-events/blob/master/api/event-source.md#resourceeventsource).
```

links to https://github.com/argoproj/argo-events/blob/master/api/event-source.md#resourceeventsource which 404s.

I'm not sure what the correct link should be.

**Comment by joebowbeer** [comment]
The `event-source.md` file is there now.

However, these two files are missing, causing broken links on other pages:

sensor.md
event-bus.md

**Comment by whynowy** [comment]
Will fix all the doc links, thanks for raising the issue.
