### ISSUE TITLE
Is there anyone using Kafka EventBus?

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#3308]
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Will deprecate it if no one uses it.

**Comment by piby180** [comment]
Hi,
We use kafka event bus -> kafka event source -> kafka sensor

**Comment by whynowy** [comment]
> Hi, We use `kafka event bus -> kafka event source -> kafka sensor` as we already maintain AWS MSK cluster. May I ask what it the reason you are thinking about deprecating it? Honestly , we are facing some issue with reliabiliy of this event architecture. The sensors just stop processing messages after a few days. #3273
> 
> We are planning to revisit our event architecture. If you have other suggestions for us for a reliable event trigger system, please let us know. We are already maintaining kafka cluster so it makes sense for us to use Kafka everywhere.

Good to know you are using Kafka EventBus - I thought there was nobody.. :)

I thought of deprecation because of 1.) possibility of no user 2.) lack of maintenance.

Appreciate if you would like to look into the reliability issue you mentioned.

**Comment by whynowy** [comment]
Close it, as we will not do it.
