### ISSUE TITLE
404 on jetstream full spec link

### ISSUE THREAD

**Issue by jblsk** [argoproj/argo-events#3312]
**Describe the bug**
Dead link in "Check [here](https://github.com/argoproj/argo-events/blob/master/api/event-bus.md#argoproj.io/v1alpha1.JetstreamBus) for the full spec of jetstream." on the page https://argoproj.github.io/argo-events/eventbus/jetstream/#properties

**To Reproduce**
1. Go to 'https://argoproj.github.io/argo-events/eventbus/jetstream/#properties'
2. Click on 'here' in the sentence: "Check [here](https://github.com/argoproj/argo-events/blob/master/api/event-bus.md#argoproj.io/v1alpha1.JetstreamBus) for the full spec of jetstream."
3. See error http 404

**Expected behavior**
A page with jetstream full spec appears.

**Screenshots**
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/80c9b9ef-6dc6-42a7-80b6-02d929f33169">

**Environment (please complete the following information):**
n/a

**Additional context**
n/a
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Fixed by https://github.com/argoproj/argo-events/pull/3310
