### ISSUE TITLE
Add argo-ci and pr check

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#34]
**Is your feature request related to a problem? Please describe.**
Since this project is now under the Argo Project, we should follow suite with the other projects and add an `.argo-ci/ci.yaml` file and setup the appropriate build/test checks.

**Describe the solution you'd like**
Create the CI process for Argo-Events.

**Describe alternatives you've considered**
I have a working `.travis.yml` file in the repo and was previously using Travis-CI test/builds to verify PR checks. I would need access to the Travis CI for Argo.

**Comment by magaldima** [comment]
@edlee2121 @shrinandj Can you guys tackle this issue? Right now, we just need it to run the project tests.

**Comment by shrinandj** [comment]
Sure. I'll do this.

**Comment by shrinandj** [comment]
I have access to the Kubernetes cluster where Argo's current builds happen.

Currently creating the workflow for building `argo-events`. Once I have the workflow executing correctly, I'll create the appropriate webhooks in Github to send the request to K8s cluster for building everytime a PR is created.

**Comment by shrinandj** [comment]
I created a workflow for running the CI for argo-events. However, I'm running into a problem where the workflow does not complete even though the pod execution has completed. Filed an issue on the main argo repo for it.

https://github.com/argoproj/argo/issues/898

**Comment by shrinandj** [comment]
CI for pull-requests has been setup.
