### ISSUE TITLE
Add Sensor's gateway usage via configMap 

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-events#341]
Is it possible to "add" new sensors for a Gateway via Sensors ConfigMaps ?

Ex. I would like to share stream Gateways between all Sensors which uses streams, and configure the sensors Gateway config via ConfigMap  (which GateWay to use)

ex move the below part from the Gateway to each Sensors ConfigMap 
watchers:
    sensors:
    - name: "sensor-ci-flow-amqp-triggered-ms-backend"
    - name: "sensor-ci-flow-amqp-upload-ei-subscription-ms-frontend"

**Comment by VaibhavPage** [comment]
Not currently. There have been similar requests as yours. I am going to open an issue to discuss possible architectures.

**Comment by ptemmer** [comment]
Wouldn't it be possible to have the gateway-controller watch for Sensor objects and accordingly add/remove watchers based on the defined dependencies in the Sensors?

Or allow the watchers to contain regular expressions and use convention over configuration.
```
watchers:
  sensors:
  - name: mywebhook-*
```
Sensors created with mywebhook-some_distinguised_name would automatically be included as watchers.
This comes in handy for use cases where Sensors trigger the creation of new sensors (for example git pull requests should create another sensor to listen for git pushes of that particular branch).
It might need some extra work on the controller side to populate the proper svc urls for the different sensors

**Comment by VaibhavPage** [comment]
@ptemmer the reason for having `watchers` defined in gateway resource was to have multiple custom resources act as watchers. My concern for gateway controller watching updates in sensor resource is that it will tightly couple gateway with a sensor. In the future, by de-coupling gateway and sensor, a user will be able to simply deploy just a gateway or sensor. 

Usecase for a standalone gateway - User already has an application server running and just wants a mechanism to consume events from an external source and pass then to the application server.
Usecase for a standalone sensor - User already has the event processor in place and needs a mechanism to manage the events and triggers

What do you think if we introduce a new resource called `Targets` which will simply contain a list of K8s services(not specific to the sensor services)? The gateway will just refer to `Target` resource/s and simply send events to services listed in that. The sensor, on the other hand, will also refer `Targets` in its specification and the `sensor controller` will watch updates to the sensor resource which it already does and update the `Targets` resource with the sensor's service. Source and Sink are completely decoupled from each other.

`Targets` resource - 
```
apiVersion: v1alpha1
kind: Targets
metadata:
  name: targets
spec:
  endpoints:
    - "my-service-1-url"
    - "my-service-2-url"
    - "my-random-service-url/hello"
```

`Gateway` will have a field called `targets` and it will refer to a list of targets.
`Sensor` will have also have a field called `targets` with a list of targets. The sensor controller will add the sensor's service url in all the listed targets

**Comment by ptemmer** [comment]
Yup, that would make sense.
I'm not too convinced about the naming though. 'target' is very broad and is hard to deduce what it stands for, especially from a Sensor's point of view. What about 'watcherGroup', 'notificationGroup', 'subscription' or 'subscriptionGroup'

**Comment by VaibhavPage** [comment]
Yeah, I like `Subscription`

**Comment by ptemmer** [comment]
This is closed, however I don't see that it is actually implemented, or is it?
In v0.12 the Gateway resource still requires sensors to be included as a list. Difference compared to v0.11 is that they aren't called watchers anymore, but subscibers. Can you elaborate?
