### ISSUE TITLE
sensor should set ownerReferences

### ISSUE THREAD

**Issue by OmerKahani** [argoproj/argo-events#343]
**Is your feature request related to a problem? Please describe.**
Sensor should set ownerReferences to the objects it triggers. So it will be visible in ArgoCD

**Describe the solution you'd like**
Objects that are trigger should have: 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/8766193/63416687-8adc8100-c408-11e9-9cf5-dd0befe22a87.png">

**Comment by VaibhavPage** [comment]
Will add it.

**Comment by VaibhavPage** [comment]
v0.12 has the fix.
