### ISSUE TITLE
GIT Artifact not respecting insecureIgnoreHostKey: true

### ISSUE THREAD

**Issue by pplavetzki** [argoproj/argo-events#346]
**Describe the bug**
When using the `insecureIgnoreHostKey: true` property the workflow fails in the init container with the following error:
```
time="2019-08-28T20:18:49Z" level=fatal msg="ssh: handshake failed: knownhosts: key is unknown\ngithub.com/argoproj/argo/errors.Wrap\n\t/go/src/github.com/argoproj/argo/errors/errors.go:88\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/go/src/github.com/argoproj/argo/errors/errors.go:71\ngithub.com/argoproj/argo/workflow/artifacts/git.gitClone\n\t/go/src/github.com/argoproj/argo/workflow/artifacts/git/git.go:91\ngithub.com/argoproj/argo/workflow/artifacts/git.(*GitArtifactDriver).Load\n\t/go/src/github.com/argoproj/argo/workflow/artifacts/git/git.go:41\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).LoadArtifacts\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:165\ngithub.com/argoproj/argo/cmd/argoexec/commands.loadArtifacts\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:34\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewInitCommand.func1\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/init.go:14\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/src/github.com/spf13/cobra/command.go:766\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/src/github.com/spf13/cobra/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/src/github.com/spf13/cobra/command.go:800\nmain.main\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
```
This does not occur using the same workflow outside of argo events.  The git repo is a private gitlab server and not something that gets added to the default list of known_hosts.

**To Reproduce**
1. Add a simple git artifact that uses a gitlab private repo in a workflow (https://github.com/argoproj/argo/blob/master/examples/input-artifact-git.yaml#L38)
2. add the `insecureIgnoreHostKey: true`
3. execute -> this will work!
4. add this as a trigger in a sensor
5. execute
6. this will fail with the above message

**Expected behavior**
I expect the git artifact to be create successfully as it is when executing the workflow

**Environment (please complete the following information):**
 - OS: Ubuntu 16.0.4 LTS, k8S 1.15.1
 - Version:
```
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```

**Additional context**

**Comment by cchanley2003** [comment]
Is there any work around for this?

**Comment by cchanley2003** [comment]
So I believe the issue is likely that argo events depends off argo 2.2, and the flag was introduced to the schema in 2.3 so it is the flag is being dropped. Seems like just upgrading to 2.3 should maybe fix the problem.

**Comment by pplavetzki** [comment]
My 1st attempt at a workaround was using initContainers but again this was an issue because it's a v2.3 feature of argo, so that did not work.

My final hack (workaround) was to create another step in the workflow that I created an artifact with the code repo cloned.  I used a secret with the known hosts file and mounted that into the container. I then used that artifact in the other steps.

**Comment by Syps** [comment]
This is affecting me as well. Any timeline on when we can expect an upgrade on the argo dependency from 2.2 -> 2.3?

**Comment by VaibhavPage** [comment]
I'll update the Argo worklow version to 2.3 asap.

**Comment by whynowy** [comment]
I think this is not an issue any more.
