### ISSUE TITLE
Allow a sensor to update an existing resource

### ISSUE THREAD

**Issue by julienp** [argoproj/argo-events#348]
**Is your feature request related to a problem? Please describe.**

Currently a sensor always creates a new resource, but can not replace or update an existing one. My specific use case is to update a deployment with information coming from a webhook.

**Describe the solution you'd like**

It should be possible to update an existing resource in a sensor trigger. Either by specifying a behaviour on the trigger, or by detecting a resource with the given name already exists.

**Comment by VaibhavPage** [comment]
Makes sense, I can add `operation` key in template spec which by default is `create` but you override with `update`

**Comment by jvaibhav123** [comment]
Hi Vaibhav,

Just wanted to check is there any targate date for v0.12.
Also , is it possible to delete the k8s resource or scale down the resource if source events has no data for perticular time period. e.g sqs or sns when no events , scale down k8s resource

**Comment by VaibhavPage** [comment]
Please have a look at #401
