### ISSUE TITLE
Events as CRD

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#35]
Making events as CRD,

1) As soon as signal receives the event, we create a CRD with appropriate labels.

2) Once all signals are resolved, we create and "watch" the trigger. As soon as trigger resource successfully completes, we mark associated Event CRDs as complete and delete them(we may provide option to store them in a datastore like ElasticSearch) (Drawback here is what if the trigger is not a Kubernetes resource then how to make sure it completed). Deleting event CRDs as soon as trigger resource completes prevents us from having useless event CRDs.

3) In case a sensor dies(for any reason whatsoever) in middle of execution, we already have the events received as CRDs. So when user recreates that sensor, we provide an option whether to replay all events associated with that sensor or cherry pick the events.

Also we can have a vacuum process just how Brigade has it to clear the old events CRD.

Looking at Brigade.js, they are considering making events as CRD.

`Brigade events are currently specified as Kubernetes Secrets with particular labels. We use secrets because at the time of development, Third Party Resources were deprecated and Custom Resource Descriptions are not final. This aspect of the system may change between the 0.1.0 release of Brigade and the 1.0.0 release.`

Also I am wondering whether we should have a sensor gateway similar to Brigade gateway, although I am not sure how that fits with our architecture.

**Comment by vicaire** [comment]
Does this address some shortcomings of the current implementation? (It would be nice to get a sense of the advantages/disadvantages of the current implementation compared to the new one proposed here).

**Comment by magaldima** [comment]
The goal of this implementation is to work towards better guarantees around events + triggers in addition to the ability to replay triggers from old events. The current implementation lacks a concept of an event log (see #4 ) and I believe this issue introduces the kubernetes etcd store as a short-term event log. 

> Also I am wondering whether we should have a sensor gateway similar to Brigade gateway, although I am not sure how that fits with our architecture.

I believe this note introduces an entirely new concept altogether and should be discussed separately to the one that I think this issue started off as.

**Comment by magaldima** [comment]
the motivation behind this will be addressed in #4
