### ISSUE TITLE
Sensors should be able to dispatch events to a pool of workers

### ISSUE THREAD

**Issue by bgh** [argoproj/argo-events#350]
**Is your feature request related to a problem? Please describe.**

There is a lot involved in spinning up a pod for each event (especially if the events are small and coming in quickly).  It would be nice to be able to have pool workers running and ready to accept/process events instead of paying the startup cost for each event.

**Describe the solution you'd like**

Instead of triggering a new pod it would be great if we could somehow get the event to an already running worker.  There are a lot of ways this could potentially work: sensor sends events to a pub/sub system or sends an http post to the worker (but in that case we would also have to figure out how to load balance the requests amongst the workers).

**Comment by VaibhavPage** [comment]
To define a worker pool of unique K8s resource and managing them scale from 0 to n is not difficult. Only problem with argo-events is that the sensor can trigger any K8s resource. So defining a pool of workers is not possible.

**Comment by VaibhavPage** [comment]
I am closing this issue for now. Let me know if I have missed an obvious solution here.
