### ISSUE TITLE
Example to trigger a workflow using rabbitmq

### ISSUE THREAD

**Issue by piby180** [argoproj/argo-events#355]
Hey all,

I am trying to trigger Argo workflow using rabbitmq events. Here are my event source, gateway and sensor yaml files

Event Source

    # This configmap contains the event sources configurations for AMQP gateway
    
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: amqp-event-source
      labels:
        # do not remove
        argo-events-event-source-version: v0.10
    data:
      # no retries if connection to amqp service is not successful
      example-without-retry: |-
        # url of the service
        url: amqp://localhost:5672
        # name of the exchange
        exchangeName: "argo-exchange"
        # type of the exchange
        exchangeType: fanout
        # routing key for the exchange
        routingKey: "argo routing key"
      # retry after each backoff to set up a successful connection
      example-with-retry: |-
        url: amqp://localhost:5672
        exchangeName: "argo-exchange"
        exchangeType: fanout
        routingKey: "argo routing key"
        backoff:
          # duration in nanoseconds. following value is 10 seconds
          duration: 10000000000
          # how many backoffs
          steps: 5
          # factor to increase on each step.
          # setting factor > 1 makes backoff exponential.
          factor: 2
Gateway

    apiVersion: argoproj.io/v1alpha1
    kind: Gateway
    metadata:
      name: amqp-gateway
      labels:
        # gateway controller with instanceId "argo-events" will process this gateway
        gateways.argoproj.io/gateway-controller-instanceid: argo-events
        # gateway controller will use this label to match with it's own version
        # do not remove
        argo-events-gateway-version: v0.10
    spec:
      # type of the gateway
      type: "amqp"
      # event source configmap name
      eventSource: "amqp-event-source"
      # port of the gateway server to send event source configuration to.
      # you can configure it to any open port
      processorPort: "9330"
      # protocol used to send event from gateway to sensor. HTTP in this case
      eventProtocol:
        type: "HTTP"
        # port on which sensor is listening to events
        http:
          port: "9300"
      # template is K8s PodSpec
      template:
        metadata:
          name: "amqp-gateway"
          labels:
            gateway-name: "amqp-gateway"
        spec:
          containers:
            - name: "gateway-client"
              image: "argoproj/gateway-client"
              imagePullPolicy: "Always"
              command: ["/bin/gateway-client"]
            - name: amqp-events
              image: "argoproj/amqp-gateway"
              imagePullPolicy: "Always"
              command: ["/bin/amqp-gateway"]
          serviceAccountName: "argo-events-sa"
      # sensors to send events to
      watchers:
        sensors:
        - name: "amqp-sensor"

Sensor

    apiVersion: argoproj.io/v1alpha1
    kind: Sensor
    metadata:
      name: amqp-sensor
      labels:
        # sensor controller with instanceId "argo-events" will process this sensor
        sensors.argoproj.io/sensor-controller-instanceid: argo-events
        # sensor controller will use this label to match with it's own version
        # do not remove
        argo-events-sensor-version: v0.10
    spec:
      template:
        spec:
          containers:
            - name: "sensor"
              image: "argoproj/sensor"
              imagePullPolicy: Always
          serviceAccountName: argo-events-sa
      eventProtocol:
        type: "HTTP"
        http:
          port: "9300"
      dependencies:
        - name: "amqp-gateway:example-with-retry"
      triggers:
        - template:
            name: amqp-workflow-trigger
            group: argoproj.io
            version: v1alpha1
            kind: Workflow
            source:
              inline: |
                apiVersion: argoproj.io/v1alpha1
                kind: Workflow
                metadata:
                  generateName: amqp-
                spec:
                  entrypoint: whalesay
                  arguments:
                    parameters:
                    - name: message
                      # this is the value that should be overridden
                      value: hello world
                  templates:
                  - name: whalesay
                    inputs:
                      parameters:
                      - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]
          resourceParameters:
            - src:
                event: "amqp-gateway:example-with-retry"
              dest: spec.arguments.parameters.0.value

Pika Python file

    import pika
    
    
    if __name__ == '__main__':
        connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
        channel = connection.channel()
        channel.queue_declare(queue='hello')
        channel.basic_publish(exchange='argo-exchange',
                          routing_key='argo routing key',
                          body='Hello World!')
        print(" [x] Sent 'Hello World!'")
        connection.close()

I can see the messages are being sent but nothing happens when I run

argo list -n argo-events

**Comment by VaibhavPage** [comment]
You may want to provide actual service address and port instead of `localhost` in the `url` under `event-source-configmap`
