### ISSUE TITLE
[Feature Request] [Resource Gateway] Replace Labels and Annotations in ResourceFilter with LabelSelector

### ISSUE THREAD

**Issue by logicfox** [argoproj/argo-events#358]
**Is your feature request related to a problem? Please describe.**
This is a feature request.
The Resource Filter config in Resource Gateways currently supports Labels and Annotations, but these filters require specifying a value. Enhancing this with the [Label Selector](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#labelselector-v1-meta) would allow for more fine grained definition of selectors. 

**Describe the solution you'd like**
Replace Labels and Annotations in ResourceFilter with LabelSelector or have it in addition to the current options.

**Describe alternatives you've considered**
No alternatives available

**Additional context**
I have a case where I want to execute a workflow if a certain label exists in a Namespace. The value for this label differs. With the current set of options, I have to have multiple configuration blocks for each label value.

This would also imply that there would be lesser code to maintain.

**Comment by VaibhavPage** [comment]
Cool, I'll add it.
