### ISSUE TITLE
Allow default circuit behavior to be configured

### ISSUE THREAD

**Issue by jaygorrell** [argoproj/argo-events#362]
**Is your feature request related to a problem? Please describe.**
I have a number of workflows triggered by various calendar events and webhooks that pass their own `userPayload`. Each job is technically independent, they just happen to share a very similar workflow.

Currently, I have to specify a large number of entries for `dependencyGroups` and an equally large circuit that `||`s them together (not to mention the `dependencies` list and `resourceParameters` mappings).

**Describe the solution you'd like**
The default behavior of `circuit` is to `&&` them together. I'd like an option (`circuitDefault: "OR"`?) to override that.

**Comment by VaibhavPage** [comment]
Cool. I'll add it.

**Comment by VaibhavPage** [comment]
It looks like this feature will introduce unnecessary complexity to the codebase. The same thing can be achieved using `Circuits & Switch`. Closing the issue.
