### ISSUE TITLE
Clarification for file sensor  example

### ISSUE THREAD

**Issue by clementrey** [argoproj/argo-events#374]
Hello every one
I tried to apply the example  for file sensor. I deployed the 3 files: 

- https://github.com/argoproj/argo-events/blob/b68b94abb38b8318bd97c6a0a86873e2accad07f/examples/event-sources/file.yaml

- https://github.com/argoproj/argo-events/blob/b68b94abb38b8318bd97c6a0a86873e2accad07f/examples/gateways/file.yaml

- https://github.com/argoproj/argo-events/blob/b68b94abb38b8318bd97c6a0a86873e2accad07f/examples/sensors/file.yaml

I looked a the configuration of the  example-with-path and I was not able to figure out in which bin directory of which container/host I should create the x.txt files.

Thank you very much for your help
Regards

**Comment by VaibhavPage** [comment]
With `example-with-path`, you need to create a file called x.txt in `file-events` container in  `Gateway` pod

**Comment by VaibhavPage** [comment]
And if you have file system you want to monitor and trigger workflows, mount the volume for `file-events` container in `Gateway` pod as well.

**Comment by VaibhavPage** [comment]
Closing the issue, let me know if you are still facing the issue
