### ISSUE TITLE
Publish containers to docker hub

### ISSUE THREAD

**Issue by kerinin** [argoproj/argo-events#38]
**Describe the bug**
The [k8s deployment manifest](https://github.com/argoproj/argo-events/blob/master/hack/k8s/manifests/sensor-controller-deployment.yaml) references `argoproj/sensor-controller:latest` however this image doesn't exist

**To Reproduce**
1. `kubectl create -f hack/k8s/manifests/*`
2. `kubectl get po && kubectl describe <sensor-controller-pod>`

**Expected behavior**
Pod is running

**Screenshots**
```Events:
  Type     Reason                 Age   From                         Message
  ----     ------                 ----  ----                         -------
  Normal   Scheduled              8s    default-scheduler            Successfully assigned sensor-controller-6dc9694978-t2npf to docker-for-desktop
  Normal   SuccessfulMountVolume  8s    kubelet, docker-for-desktop  MountVolume.SetUp succeeded for volume "argo-events-token-2kd6f"
  Normal   Pulling                7s    kubelet, docker-for-desktop  pulling image "argoproj/sensor-controller:latest"
  Warning  Failed                 7s    kubelet, docker-for-desktop  Failed to pull image "argoproj/sensor-controller:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for argoproj/sensor-controller, repository does not exist or may require 'docker login'
  Warning  Failed                 7s    kubelet, docker-for-desktop  Error: ErrImagePull
  Normal   BackOff                6s    kubelet, docker-for-desktop  Back-off pulling image "argoproj/sensor-controller:latest"
  Warning  Failed                 6s    kubelet, docker-for-desktop  Error: ImagePullBackOff```
```

**Environment (please complete the following information):**
 - OS: macOS

**Comment by magaldima** [comment]
The repository `argoproj/sensor-controller` does not exist on DockerHub yet. We should create this repository. 

In the meantime, if you are trying to run this on `Minikube` on Mac you can try:
1. Point docker to use the minikube docker daemon
`eval $(minikube docker-env)`
2. Build the project which executes a docker build.
`make controller-image`
3. Verify the image is available on the minikube docker daemon:
`docker images`

**Comment by magaldima** [comment]
I've created a DockerHub for the `sensor-controller` and pushed the latest tag `v0.5-alpha1` as well as the latest master version. 
https://hub.docker.com/r/argoproj/sensor-controller/tags/
