### ISSUE TITLE
Kustomize manifest is not working properly for v0.10

### ISSUE THREAD

**Issue by ptemmer** [argoproj/argo-events#388]
**Describe the bug**
The sensor-controller and gateway-controller deployments in https://github.com/argoproj/argo-events/tree/master/hack/k8s/manifests in the v0.10 release tag point to images with tag 'latest'. However, the 'latest' images in Docker hub haven't been updated for the last 9 months.

**To Reproduce**
1. Generate a kustomize manifest using https://github.com/argoproj/argo-events/tree/master/hack/k8s/manifests as base
2. Deploy the manifest
3. Verify that the sensor-controller and gateway-controller aren't running the latest images that correspond to v0.10.

**Expected behavior**
Either:
- the sensor-controller and gateway-controller image tags to be explicitly set in the Kustomize config to the specific version tag
- 'latest' images in Docker hub to updated

**Comment by VaibhavPage** [comment]
I'll take a look.

**Comment by VaibhavPage** [comment]
please try with v0.12
