### ISSUE TITLE
transform issue when doing go build

### ISSUE THREAD

**Issue by XiangChen666** [argoproj/argo-events#389]
**Describe the bug**
/go/src/github.com/argoproj/argo-events/gateways/transformer.go:75:10: assignment mismatch: 1 variable but uuid.NewV1 returns 2 values
**To Reproduce**
doing go build when module=off
**Expected behavior**
should be eventId, _ := suuid.NewV1()
**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**

**Comment by VaibhavPage** [comment]
I think we should switch to google's stable uuid lib to prevent all future conflicts

**Comment by XiangChen666** [comment]
ok. Let me fix it
