### ISSUE TITLE
Missing changes in v0.11

### ISSUE THREAD

**Issue by sudermanjr** [argoproj/argo-events#398]
**Describe the bug**

After installing events v0.11, applying a Gateway with the label `argo-events-gateway-version: v0.11` does not get picked up by the controller.

In addition, the hack/k8s folder does not seem to include changes to the ClusterRole to allow the viewing of WorkflowTemplates. 

**To Reproduce**
1. Apply a gateway manifest with the label `argo-events-gateway-version: v0.11`
2. Run `kubectl get po` 
3. Note that no gateway pod gets created.

**Expected behavior**
A gateway pod will get created.

**Environment (please complete the following information):**
 - Kube: 1.14.8
 - Argo-events: v0.11
 - Argo version v2.4.2

**Comment by VaibhavPage** [comment]
@sudermanjr is it still happening?

**Comment by sudermanjr** [comment]
@VaibhavPage I have left my sensor and gateway labels as `l argo-events-gateway-version: v0.10` to work around it, so I haven't really tested anything.  Is there a change somewhere that I should test since release of 0.11?

**Comment by sudermanjr** [comment]
@VaibhavPage I tried installing argo-events with the `latest` docker image instead of v0.11 and it seems to have fixed the issue.  Would it be possible to get a patch release so that I can update the helm chart and not have to use `latest`?

**Comment by retnuh** [comment]
As I mentioned in #412 the tag for `v0.11` seems to be against the wrong version; I built some images from commit 3cdc92fab20f809c1279e419b6d03b4d83f1cd77 which seems to have the correct `v0.11` updates.

**Comment by VaibhavPage** [comment]
Closing the issue as `argo-events-gateway-version` not relevant anymore.
