### ISSUE TITLE
event log storage

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#4]
**Feature Gap**
Currently, we do not store a log of the signal `events` in the sensor status as this would cause the sensor object to grow in size. We only store the latest event for a certain signal in the sensor status. These events should be persisted somewhere in order to allow replaying of events + signals and for repeatability purposes.

**Design Requirements**
- Persistent storage with backup (guarantee that we don't lose an event)
- CRUD actions
- Query by sensor name and time

**Proposal**
We should implement an `event-transaction-log` storage interface by which users can implement and expose a data sink to store signal events.
Implementation ideas:
- Event CRD (on etcd) - see #35 
- FluentD
- ElasticSearch
- Logrus -> route to sink?

**Comment by VaibhavPage** [comment]
Agreed, a plugin based  https://github.com/hashicorp/go-plugin solution would be nice.

**Comment by VaibhavPage** [comment]
ElasticSearch as default implementation? as it is perfect for storing events and do queries on top of it.

**Comment by VaibhavPage** [comment]
with NATS streaming supported, do we still need this?

**Comment by magaldima** [comment]
we can debate whether we need to do more here.. I envision a future where this log storage is an abstraction layer on top of any specific implementation such as `NATS Streaming`... 

Also, does this persistence layer exist between gateway event source and gateway client or between gateway client and sensor? I'm of the opinion it would exist between gateway client and sensor, however this would be defined within the gateway `api`. I would not include this is `v1`, but maybe as a major enhancement of breaking api part of `v2`.
