### ISSUE TITLE
Add support for a custom cluster domain for the ServiceDNSName function

### ISSUE THREAD

**Issue by mool** [argoproj/argo-events#402]
**Is your feature request related to a problem? Please describe.**
I'm using a custom domain instead of "cluster.local" for my kubernetes cluster and I'm getting this kind of errors:
```
webhook-gateway-http gateway-client WARN[2019-11-12 20:30:09] failed to dispatch event to sensor watcher over http. communication error  error="Post http://whalesay-sensor-svc.argo-events.svc.cluster.local:9300/: dial tcp: lookup whalesay-sensor-svc.argo-events.svc.cluster.local on 10.80.2.21:53: no such host" sensor-name=whalesay-sensor
```

The `ServiceDNSName` function has the cluster domain hardcoded as `cluster.local` https://github.com/argoproj/argo-events/blob/master/common/util.go#L44-L46

**Describe the solution you'd like**
I would like to remove the cluster domain from the result and only use `<svc name>.<namespace>.svc` or maybe be able to configure a custom domain.

**Comment by yujingz** [comment]
having the same issue

**Comment by VaibhavPage** [comment]
v0.12 lets you define any URL for the subscriber.
