### ISSUE TITLE
Documentation: following getting started doesn't create webhook gateway container

### ISSUE THREAD

**Issue by amibln** [argoproj/argo-events#403]
**Description**
I was following the official guide on https://argoproj.github.io/argo-events/installation/
Gateway-controller and Sensor-controller have been created successfully when following the installation step.
Following the GettingStarted (deploy webhook gateway and sensor) the gateway controller should  create corresponding gateway pod and service.
But unfortunately nothing will be created.
The logs of Gateway controller doesn't show any indication that it was triggered at all.
The log only shows the three lines from startup.

36mINFO 2019-11-13 13:51:21 watching gateway-controller config map updates 
36mINFO 2019-11-13 13:51:21 detected EventSource update. updating the gateway-controller config. 

I cannot find any events in the cluster with an indication that placement / version or something else doesn't match.

**To Reproduce**
1. installed docker for mac (Catalina) again from scratch
2. setup argo workflow - it works as expected
3. installation of argo-events (using commands from official page) (helm chart is argo-events-0.5.2)
4. executing "getting started"
 
**Expected behavior**
Following the getting started should work with specified commands.

**Environment:**
 - OS: macOS Catalina
 - Docker for Mac 2.1.0.4
- Engine: 19.03.4
- Kubernetes: v1.14.7

I did the same exercise on a clean AWS EKS cluster as well with same result.
I am absolutely sure that it has a very simple reason.
The project is that impressive and heavily used that it can only be a documentation issue.

**Comment by amibln** [comment]
Did the setup again and checked that all resources are using same namespace.
The only thing I see in "kube-controller-manager logs" is about  a "too old watch":

```bash
# kube-controller-manager

# apply events_sa
W1114 09:11:52.827552       1 reflector.go:289] k8s.io/client-go/informers/factory.go:133: watch of *v1beta1.Event ended with: The resourceVersion for the provided watch is too old.

# apply sensor_controller_deployment
I1114 09:21:03.430983       1 event.go:209] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"argo-events", Name:"sensor-controller", UID:"146a5ad9-06c0-11ea-b72c-025000000001", APIVersion:"apps/v1", ResourceVersion:"39362", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set sensor-controller-546db4df6 to 1
I1114 09:21:03.439084       1 event.go:209] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"argo-events", Name:"sensor-controller-546db4df6", UID:"146b470d-06c0-11ea-b72c-025000000001", APIVersion:"apps/v1", ResourceVersion:"39363", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: sensor-controller-546db4df6-jvq8f

# apply gateway_controller_deployment
I1114 09:22:11.902397       1 event.go:209] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"argo-events", Name:"gateway-controller", UID:"3d3a62a4-06c0-11ea-b72c-025000000001", APIVersion:"apps/v1", ResourceVersion:"39465", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set gateway-controller-57957cc5f5 to 1
I1114 09:22:11.914880       1 event.go:209] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"argo-events", Name:"gateway-controller-57957cc5f5", UID:"3d3b34a8-06c0-11ea-b72c-025000000001", APIVersion:"apps/v1", ResourceVersion:"39466", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: gateway-controller-57957cc5f5-cpmfs

W1114 09:32:20.996139       1 reflector.go:289] k8s.io/client-go/informers/factory.go:133: watch of *v1beta1.Event ended with: The resourceVersion for the provided watch is too old.
W1114 09:46:12.507316       1 reflector.go:289] k8s.io/client-go/informers/factory.go:133: watch of *v1beta1.Event ended with: The resourceVersion for the provided watch is too old.

# deployments are ready
kubectl get Deployments -n argo-events
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
gateway-controller   1/1     1            1           33m
sensor-controller    1/1     1            1           35m

# CRDs and Objects have been deployed and are showing no events when running "describe"
$ kubectl get Gateway -n argo-events
NAME              AGE
webhook-gateway   3m39s

$ kubectl get Sensors -n argo-events
NAME             AGE
webhook-sensor   52s


```

**Comment by amibln** [comment]
I think I have found the reason now.
The default deployment described in the "installation section" is using "latest" image version for "gateway-controller" and "gateway-sensor".
When I change the examples manually to e.g. "argoproj/sensor-controller:v0.11" the controller detects the CRDs object definitions and starts the container accordingly:

```bash
kubectl get pods -n argo-events                                                     <aws:default>
NAME                                  READY   STATUS    RESTARTS   AGE
gateway-controller-74dd57c47f-njztc   1/1     Running   0          15m
sensor-controller-7567c69548-2hxnt    1/1     Running   0          9m39s
webhook-gateway-http                  2/2     Running   1          13m
webhook-sensor                        1/1     Running   0          9m33s
```

**Comment by VaibhavPage** [comment]
Thanks for pointing that out. Latest still refers to v0.10, I'll update it t v0.11

**Comment by tomaszwostal** [comment]
@VaibhavPage Please do :)

**Comment by tomaszwostal** [comment]
@VaibhavPage I did not notice that you have already done it. Thanks.

**Comment by CH-karthikprasad** [comment]
For the kafka gateway and sensor, even after trying to use 0.11, it seems to not work. i had to revert back to 0.10

**Comment by VaibhavPage** [comment]
@CH-karthikprasad v0.11 and v0.12 had issue with Kafka gateway. Please use v0.12.1 for Kafka gateway.
