### ISSUE TITLE
Only create Gitlab gateway webhook integration if it doesn't already exist

### ISSUE THREAD

**Issue by Syps** [argoproj/argo-events#408]
**Is your feature request related to a problem? Please describe.**
I have a Gitlab gateway running in my namespace. In the course of development, I sometimes will delete the gateway and later recreate it in the same namespace. Whenever this happens, the gateway creates a new webhook integration on my Gitlab repo; however, it doesn't check to see if such an integration already exists. In the end, I end up with multiple duplicate webhooks in my gitlab repo, which causes duplicate events. To fix this, I have to manually go into the repo settings and delete the duplicate webhook integrations.

**Describe the solution you'd like**
I propose that when the gateway is created, it performs an initial check of the webhook integrations that already exist on the gitlab repo. Then, only if the integration for this gateway does _not_ yet exist on the repo will it be created.

**Comment by VaibhavPage** [comment]
v0.13.0 fixes the issue.
