### ISSUE TITLE
AWS SNS gateway rejects configurations in version v0.11 with v0.11

### ISSUE THREAD

**Issue by clementlecorre** [argoproj/argo-events#412]
**Describe the bug**

AWS SNS gateway rejects configurations in version v0.11 with v0.11 (latest version).

**To Reproduce**

1. Deploy argo-events with helm chart (v0.11)
2. Deploy sns gateway with latest(I think v0.11) version (argoproj/aws-sns-gateway@sha256:259549e6deab59cbadeb3e173cc7b7962792fb4ad97698064e3de2f10b74b821)
3. configmap aws-sns-event-source with labels (argo-events-event-source-version: v0.11)
4. See error in aws-sns-gateway/gateway-client logs

```
kubectl -n argo  logs -f aws-sns-gateway -c gateway-client
```
Error : version mismatch.
```

INFO[2019-11-27 17:32:36] activating new event source                   event-source=processing
ERRO[2019-11-27 17:32:36] event source is not valid                     validation-failure="event source version mismatch. gateway expects v0.10 version, and provided version is v0.11"
```

**Expected behavior**

A configuration with the version  v0.11 as in the example.
```
metadata:
  labels:
     argo-events-event-source-version: v0.11
```

I think v0.11 version is missing in the registry, and latest version is v0.10

**Environment :**

 - k8s : v1.14.8-eks
 - Argo events : v0.11
- Argo workflow : v2.4.2

**Comment by retnuh** [comment]
I'm getting the same thing; I think there's some problems with tagged images for v0.10.  I've noticed a few problems with the repo on the v0.11 tag:

- VERSION file still has v0.10 in it
- Makefile still has IMAGE_TAG var at 0.10

I've corrected the above and am building/pushing the images to my personal dockerhub account; will followup with any new information.

**Comment by retnuh** [comment]
Okay it's more complicated than that; each different gateway type also has a hard-coded string along the lines of:

```
const ArgoEventsEventSourceVersion = "v0.10"
```

I'll try changing them to possibly refer to `argoevents.version` which gets the ldflags magic at build time or see if there's some other convenient makefile-hackery to accomplish something similar.

**Comment by retnuh** [comment]
Okay it looks like commit 3cdc92fab20f809c1279e419b6d03b4d83f1cd77 had all the appropriate `v0.10` -> `v0.11` changes made; I did a clean build from that commit and pushed them to `retnuh/*:v0.11`.  I'm going to commence testing them shortly.
