### ISSUE TITLE
argo documents page need upgrade

### ISSUE THREAD

**Issue by alvinyeats** [argoproj/argo-events#425]
I'm learning argo-events by reading argo documnet, https://argoproj.github.io/argo-events/getting_started/
when I try to trigger my gateway by setting port-ward, my service can't be trigger until I realize maybe I use the wrong port

the project page using port 9330:
![image](https://user-images.githubusercontent.com/9098011/70680126-23f21900-1cd2-11ea-821f-163fe6414d91.png)

Actually we should use port 12000 by argo [getting started](https://argoproj.github.io/argo-events/getting_started/#getting-started), when I try to edit this page, I found [master code ](https://github.com/argoproj/argo-events/edit/master/docs/getting_started.md)is right, so maybe you should update your project page to avoid making newbie feel confused
![image](https://user-images.githubusercontent.com/9098011/70680419-3b7dd180-1cd3-11ea-8580-9f3eadc2cbc6.png)

Thanks

**Comment by VaibhavPage** [comment]
This is addressed in the `master` branch, needs to update the docs site.

**Comment by VaibhavPage** [comment]
Docs are now updated.
