### ISSUE TITLE
Breaking changes to gateway images; examples/docs never pin versions

### ISSUE THREAD

**Issue by jaygorrell** [argoproj/argo-events#433]
**Describe the bug**
Before 0.11, our systems suddenly stopped working. It turns out, it was because the 0.11 image was published for sensor, gateway-client, and webhook-gateway and our `argo-events-event-source-version` needed bumed to v0.11, even though we weren't on 0.11 yet. We ended up just upgrading everything and it fixed the problem.

Fast forward to today, and things broke again. I see that v0.12 was published last night (also to `latest`), which seems to be the cause. If we pin our sensor/gateway images to 0.11 things work fine.

Sensor logs:
`panic: sensor controller instance ID is not provided`

Gateway logs:
`panic: gateway name not provided`

Is the solution here to pin versions? I don't think I've seen that recommendation in the docs and certainly not in the examples. Instead, is it expected that new versions aren't breaking in this way? I assumed last time was an accident but this is twice in a row.

**Environment (please complete the following information):**
 - Version v0.11

**Additional context**
Previous instance comment: https://github.com/argoproj/argo-events/issues/407#issuecomment-558457657

**Comment by VaibhavPage** [comment]
Sorry for the inconvenience. The examples will have pinned versions from now on.

**Comment by jaygorrell** [comment]
Thanks, so I assume that is the recommendation? It's going to be common for new versions to break existing setups?

**Comment by VaibhavPage** [comment]
Yep, every release will have examples pinned to that version so it doesn't break the previous setup.
