### ISSUE TITLE
Getting Started page is not up to date with the current system setup

### ISSUE THREAD

**Issue by dbuschman7** [argoproj/argo-events#453]
**Describe the bug**
It appears the getting started page is not up to date with the current configuration of the project. 

I have a brand new EKS cluster on AWS running 1.14.9 and I have tried to get a simple basic setup working for argo-events for the last few days. My Argo install is running fine and all the examples work as expected. But I cannot get any of the paths described in the Getting Started page to do anything but sit there like a bump on a log. No errors in the resource events, nothing in the logs. 

Not sure how to proceed here. 

**To Reproduce**
1. Use or create AWS account 
2. Create a test EKS cluster using 1.14.9 
3. Install Argo, verify the examples are working. 
4. Install Argo-events and attempt to complete the getting started page. 

**Expected behavior**
I see something happen in the gateway or sensor controller logs to indicate it is trying to do something. 
NOTE: Argo is installed in the argo namespace, argo-events is installed in the argo-events namespace. Both are configured to watch all namespaces. 

NOTE: No deployments of gateways are attempted and no events are logged onto any of the resources it can find. 

**Screenshots**
INFO[2020-01-04 06:06:10] starting gateway-controller                   instance-id=argo-events version=v0.11+6bc863f.dirty
INFO[2020-01-04 06:06:10] watching gateway-controller config map updates 
INFO[2020-01-04 06:06:10] detected EventSource update. updating the gateway-controller config. 
W0104 06:22:37.626315       1 reflector.go:302] github.com/argoproj/argo-events/controllers/gateway/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 2312311 (2313130)
INFO[2020-01-04 06:22:38] detected EventSource update. updating the gateway-controller config. 

**Environment (please complete the following information):**
 - AWS EKS 1.14.9
 - Kubectl v1.16.3
 - Argo - v2.4.2
 - Argo-Events : 0.11

**Additional context**
The Helm chart in the argo-helm project is missing on the the 3 CRDs and will not accept any of the examples either.

**Comment by VaibhavPage** [comment]
I have put in a PR to update Helm chart. Meanwhile, you can give it a try by following https://argoproj.github.io/argo-events/installation/#one-command-installation

**Comment by joebowbeer** [comment]
@VaibhavPage where is the PR to update Getting Started?

Currently, Getting Started is missing instructions to install CRDs. Should I create a new issue?
