### ISSUE TITLE
No Service Assoicated with SQS Gateway Example

### ISSUE THREAD

**Issue by nfickas** [argoproj/argo-events#470]
**Describe the bug**
Via this documentation: https://argoproj.github.io/docs/argo-events/docs/gateways/aws-sqs.html. We are supposed to wait for both the pod and the service to be running before installing the event source.

There is no service defined in the example aws-sqs.yaml file located here: https://github.com/argoproj/argo-events/blob/master/examples/gateways/aws-sqs.yaml.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**
Should there be a service defined in this file?

**Comment by VaibhavPage** [comment]
The `sqs` gateway doesn't need a service. The documentation needs to be updated.

**Comment by VaibhavPage** [comment]
SQS gateway doesn't need a service as SQS doesn't make HTTP request like SNS
