### ISSUE TITLE
Azure EventGrid Event Source

### ISSUE THREAD

**Issue by Ant59** [argoproj/argo-events#471]
**Is your feature request related to a problem? Please describe.**
Argo Events has no Azure EventGrid event source.

**Describe the solution you'd like**
An event source for Azure EventGrid.

**Describe alternatives you've considered**
Using the Webhook event source.

**Comment by Ant59** [comment]
https://docs.microsoft.com/en-gb/azure/event-grid/overview

**Comment by VaibhavPage** [comment]
Since v0.12, azure events hub gateway is part of argo-events. https://github.com/argoproj/argo-events/blob/master/examples/event-sources/azure-events-hub.yaml

**Comment by Ant59** [comment]
Indeed. Though Azure EventHub and Azure EventGrid are different products. I'd be interested in whether it's worth an event source for EventGrid, although the Webhook seems to suffice.

**Comment by VaibhavPage** [comment]
Ah, I confused it with the EventHub. I need to investigate the go sdk exposing the Grid API. But upon a quick look, it feels like a webhook gateway should be enough to handle the events.

**Comment by VaibhavPage** [comment]
Closing the issue, we can revisit it in the future if need be.

**Comment by SebastiaanDev** [comment]
Any update on this? I think adding an Azure EventGrid event source would be a great addition.
