### ISSUE TITLE
Gerrit events trigger

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo-events#473]
Q regarding if Argo-events (Gateways) can trigger workflows on Gerrit events like Gerrit patchset-created events ?

https://gerrit-review.googlesource.com/Documentation/cmd-stream-events.html#_patchset_created

**Comment by VaibhavPage** [comment]
If Gerrit supports the webhook integration, then the webhook gateway should be able to consume the events.

**Comment by emichaf** [comment]
Yes using the Gerrit webhhok today with argo-event webhook gateway. But I have a use case where webhook plugin is not part of the Geerit server (I no plans to install it)..  Looking for a Gerrit Event handler, and hoped Argo-event gateways supported that!

**Comment by VaibhavPage** [comment]
Got it. I'll add the Gerrit gateway in v0.13.

**Comment by emichaf** [comment]
Thanks alot, sounds great!

**Comment by chaseterry** [comment]
There's a Gerrit package for Golang (https://godoc.org/golang.org/x/build/gerrit), but it is limited and lacks the ability to consume streamed events. There's another user-created library (https://godoc.org/github.com/andygrunwald/go-gerrit), but still no support for streaming. 

It would be possible to build a gateway that polls for changes, but that would not be ideal. Leaving this as just a Gerrit webhook.
