### ISSUE TITLE
Sensor wrong tigger with switch and circuit

### ISSUE THREAD

**Issue by Erik-Securenative** [argoproj/argo-events#482]
**i am running v12**

**My EventSource is:**
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
spec:
  github:
    sncarlo:
      active: true
      apiToken:
        key: token
        name: github-access
      contentType: json
      events:
      - push
      insecure: false
      namespace: argo-events
      owner: XXXXX
      repository: sncarlo
      webHookSecret:
        key: secret
        name: github-access
      webhook:
        endpoint: /sncarlo/push
        method: post
        port: '12000'
        url: https://github.XXXXX.com
    sndockerci:
      active: true
      apiToken:
        key: token
        name: github-access
      contentType: json
      events:
      - push
      insecure: false
      namespace: argo-events
      owner: XXXXX
      repository: sndockerci
      webHookSecret:
        key: secret
        name: github-access
      webhook:
        endpoint: /sndockerci/push
        method: post
        port: '12000'
        url: https://github.XXXX.com
  type: github

**My Sensor is:**

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  template:
    spec:
      containers:
        - name: sensor
          image: argoproj/sensor:v0.12
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: sncarlo
      gatewayName: github-gateway
      eventName: sncarlo
    - name: sndockerci
      gatewayName: github-gateway
      eventName: sndockerci

  # group event dependencies
  dependencyGroups:
    - name: sncarlo
      dependencies:
        - sncarlo
    - name: sndockerci
      dependencies:
        - sndockerci

  # trigger when either group_1 or group_2 resolves
  circuit: "sncarlo || sndockerci"

  subscription:
    http:
      port: 9300
  triggers:
    - template:
        # when is the switch that determines whether to execute the trigger or not
        switch:
          # all is boolean equivalent of AND.
          # you can use `any` as well which is boolean equivalent of OR.
          all:
            - sncarlo
        name: sncarlo
        k8s:
          group: ""
          version: v1
          operation: create
          resource: pods
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: sncarlo-
              spec:
                containers:
                  - name: hello-container
                    args:
                      - "hello-world-"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"
    - template:
        switch:
          all:
            - sndockerci
        name: sndockerci
        k8s:
          group: ""
          version: v1
          operation: create
          resource: pods
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: sndockerci-
              spec:
                containers:
                  - name: hello-container
                    args:
                      - "hello-world-"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"

**When a github sent from sncarlo or sndockerci the 2 templates running**

**the log from sensor is:**
INFO[2020-02-06 16:33:13] received event                                source=github-gateway subject=sncarlo
INFO[2020-02-06 16:33:13] received an event notification                event-source=github-gateway
INFO[2020-02-06 16:33:13] phase marked as completed                     node-name=sncarlo node-type=EventDependency
INFO[2020-02-06 16:33:13] applying filters on event notifications if any  event-source=github-gateway
INFO[2020-02-06 16:33:13] applying circuit logic if any or checking if all dependencies are resolved  event-source=github-gateway
INFO[2020-02-06 16:33:13] phase marked as completed                     node-name=sncarlo node-type=EventDependency
INFO[2020-02-06 16:33:13] executing triggers                            event-source=github-gateway
INFO[2020-02-06 16:33:13] resolving the trigger implementation          event-source=github-gateway trigger-name=sncarlo
INFO[2020-02-06 16:33:13] fetching trigger resource if any              event-source=github-gateway trigger-name=sncarlo
INFO[2020-02-06 16:33:13] applying resource parameters if any           event-source=github-gateway trigger-name=sncarlo
INFO[2020-02-06 16:33:13] executing the trigger resource                event-source=github-gateway trigger-name=sncarlo
INFO[2020-02-06 16:33:13] trigger resource successfully executed        event-source=github-gateway trigger-name=sncarlo
INFO[2020-02-06 16:33:13] applying trigger policy                       event-source=github-gateway trigger-name=sncarlo
INFO[2020-02-06 16:33:13] successfully processed the trigger            event-source=github-gateway trigger-name=sncarlo
INFO[2020-02-06 16:33:13] resolving the trigger implementation          event-source=github-gateway trigger-name=sndockerci
INFO[2020-02-06 16:33:13] fetching trigger resource if any              event-source=github-gateway trigger-name=sndockerci
INFO[2020-02-06 16:33:13] applying resource parameters if any           event-source=github-gateway trigger-name=sndockerci
INFO[2020-02-06 16:33:13] executing the trigger resource                event-source=github-gateway trigger-name=sndockerci
INFO[2020-02-06 16:33:13] trigger resource successfully executed        event-source=github-gateway trigger-name=sndockerci
INFO[2020-02-06 16:33:13] applying trigger policy                       event-source=github-gateway trigger-name=sndockerci
INFO[2020-02-06 16:33:13] successfully processed the trigger            event-source=github-gateway trigger-name=sndockerci
INFO[2020-02-06 16:33:13] marking node phase                            node-name=sncarlo node-type=EventDependency phase=Complete
INFO[2020-02-06 16:33:13] persisting the sensor state
INFO[2020-02-06 16:33:13] sensor state updated successfully             phase=Active

**Comment by VaibhavPage** [comment]
You can apply `switch` condition only on the `dependencyGroups`.

**Comment by Erik-Securenative** [comment]
So i change the group name and its working
