### ISSUE TITLE
Support GKE Workload Identity for GCP PubSub

### ISSUE THREAD

**Issue by giorgioazzinnaro** [argoproj/argo-events#503]
**Is your feature request related to a problem? Please describe.**
When using GCP PubSub as an EventSource, a file is required with a service account credentials.
However, the recommended method to authenticate Google Service Accounts in a GKE cluster is to use [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity).

**Describe the solution you'd like**
Make the `credentialsFile` parameter optional in the `spec.pubsub` block, similar to #300 and use 

**Describe alternatives you've considered**
I'm not sure if one could simply set up Workload Identity first and then use the path to the default application credentials file in the configuration. Wouldn't be proper though, as the Go client provides ways to autodiscover this.

**Additional context**
I still need to understand whether the `argo-events-sa` service account has anything special to it?
For Workload Identity to work properly, the service account being used in Kubernetes must have a specific annotation set. This is the only requirement from the Kubernetes side of things.

**Comment by VaibhavPage** [comment]
I am not familiar with the workload identity, I need to investigate a bit.

**Comment by tmshn** [comment]
#593 seems to fix this, but the name is wrong. "WorkflowIdentity" should be "WorkloadIdentity".
(but I don't know the policy how field deprecation proceeds on argo-events)
