### ISSUE TITLE
codegen makes PR conflicts on every types.go change

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#56]
This is not a true issue but more of an annoyance.

I'm noticing that the file: `generated.pb.go` has many merge conflicts whenever the `types.go` file is changed in 2 concurrent PRs. Resolving these conflicts is annoying. I wonder if this is a result of:
```
[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.10"
```
as this wasn't an issue before #51 .

**Comment by shrinandj** [comment]
Generally, I'd hope upgrading should make things better :D ... But if moving to 1.10 is making things worse, I can explore reverting back.

As mentioned [earlier](https://github.com/argoproj/argo-events/issues/46#issuecomment-406106499), the reason to move to the newer release was that  existing code-generation didn't work.

Another possibility is that the conflicts are a result of only bumping up the version of `code-generator` and not of the other packages. We could ask for `argo` to do a newer release with newer package versions. Then argo-events can upgrade the argo package as well as all the other dependencies.

**Comment by shrinandj** [comment]
@jessesuen pointed out that it is possible to have `[[override]]` in Gopkg.toml with which we could move the `k8s.io/api`, `k8s.io/apimachinery` to version 1.10 and client-go to `release-7.0` even though `argo` is on release 1.9 and client-go version 6.0.

I tried doing that and was able to get builds succeeding, tests working and basic sensors running just fine.. 

I will have a PR out for this but after `0.5beta1` is released.

**Comment by shrinandj** [comment]
Fixed with:
```
commit 0b73937c2983689910c547b28085c98331e2e8a2
Author: Shri Javadekar <shrinandj@users.noreply.github.com>
Date:   Fri Jul 27 11:21:21 2018 -0700

    Use Kubernetes package version 1.10. (#74)

    Had to use them as [[overrides]] and not directly as [[constraints]] because
    argo still uses version v1.9.

    Testing done:

    1. Builds worked just fine.
    2. Unit tests worked just fine.
    3. Ran the controller and a couple of sensors. They worked too.
```
