### ISSUE TITLE
Why Best Effort QoS are chosen for gateways, sensors, and the controllers?

### ISSUE THREAD

**Issue by k2n** [argoproj/argo-events#563]
**Describe the bug**
Gateways and sensors such as `calendar-gateway` and `calendar-sensor` are evicted but no pod is running as the replacement.
I understand they are evicted as the node where the pods are running no longer has enough memory, but would like to know the rationals why gateways, sensors, and the controllers for gateway and sensors are configured as "BestEffort" QoS without specifying resources limits/requests. 
I suspect it's related to the k8s env rather than `argo-events` codebase, though.
I searched the log output of `argo-events-gateway-controller` and `argo-events-sensor-controller` but didn't find the errors related to restarting the pods.

I understand Guaranteed eliminates and Burstable reduces the change of eviction. What is the rationale not to specify resource requests/limits in the controllers, and is there a way to specify the resource definitions to gateways and sensors managed by the controllers?

**To Reproduce**
This happens when the underlying node memory resource becomes low, and Kubernetes evicts the pods.

**Expected behavior**
A new pod for the evicted gateways and sensors

**Screenshots**
![Cursor_and_Default__k9s_](https://user-images.githubusercontent.com/64663/77812942-4a548c80-70e8-11ea-8b4d-253005b86f8d.png)

Excerpt from `kubectl describe pod/calendar-gateway-...`

```
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: memory. Container gateway-client was using 134100Ki, which exceeds its request of 0. Container calendar-events was using 125380Ki, which exceeds its request of 0.
```

**Environment (please complete the following information):**
 - OS: Amazon Linux2 with AWS EKS1.14
 - Browser N/A
 - Version 0.11

**Comment by VaibhavPage** [comment]
the v0.11 has a memory leak issue with the gateway and that may be the reason the pod is getting evicted. Can you use v0.13 which fixes the issue.

**Comment by k2n** [comment]
@VaibhavPage Thank you for the advice. I noticed v0.12 introduced the breaking change to require the conversion from ConfigMaps to CRDs. Is it possible to upgrade leaving the old ConfigMaps and the convert, or does it require a big-bang migration to convert them at the same time to upgrade?

**Comment by VaibhavPage** [comment]
Yeah, v0.12+ is not backward compatible with v0.11, introduces EventSource CRD and changes to both gateway and sensor specification. So I'd say it is sort of big changes, take a look at the comment https://github.com/argoproj/argo-events/issues/305#issuecomment-590419024 . Also documentation is updated with [setup/installation guides](https://argoproj.github.io/argo-events/setup/amqp/) for every gateway/sensor and there are [tutorials](https://argoproj.github.io/argo-events/tutorials/01-introduction/) to guide you through new/existing features. I'd recommend upgrading to v0.13

**Comment by k2n** [comment]
@VaibhavPage Thx for the information, very helpful. Before closing this ticket, I'd like to know if BestEffort QoS is used by design, and if it gives the users the flexibility to choose Guaranteed or Burstable. Any insight on this?

**Comment by VaibhavPage** [comment]
You can define QoS for both gateway and sensor pod. The `template` withing [gateway ](https://github.com/argoproj/argo-events/blob/master/api/gateway.md#gatewayspec) and [sensor](https://github.com/argoproj/argo-events/blob/master/api/sensor.md#sensorspec) specification is the `pod template`. You can easily specify there which QoS you want.

**Comment by k2n** [comment]
@VaibhavPage Thx for the pointers! Close this ticket.
