### ISSUE TITLE
Blank webhook body causes json parse error

### ISSUE THREAD

**Issue by MMartyn** [argoproj/argo-events#591]
**Describe the bug**
The webhook expects there to be valid json sent and if you send a blank body it errors. 
https://github.com/argoproj/argo-events/blob/master/gateways/server/webhook/start.go#L97

**To Reproduce**
1. Pass a blank body to the webhook.

**Expected behavior**
Possibly treat a blank body as `{}`

**Additional context**
I don't have access to override the body that is being sent in this particular case.

**Comment by VaibhavPage** [comment]
Ok, we can add this.

**Comment by whynowy** [comment]
We would not expect a blank content as `{}`
