### ISSUE TITLE
SQS Multiple Gateways - One Queue using Message Group ID

### ISSUE THREAD

**Issue by phelinor** [argoproj/argo-events#592]
**Is your feature request related to a problem? Please describe.**
I can't use 1 single SQS Queue for many different Argo SQS Gateways

**Describe the solution you'd like**
Would like "Message group ID" to be added to the Argo SQS Event Source to be able to feed many Argo SQS Gateways from 1 single SQS Queue

**Describe alternatives you've considered**

**Additional context**

**Comment by whynowy** [comment]
Can you give more detail about your use case? To my understanding, SQS should not be used for multi consumers. @phelinor

**Comment by phelinor** [comment]
Sure, basically we are using SQS Argo to create workflows that are sent from our Server to SQS but the development team has the Server installed in their local machines too along with Argo and Argo Events using Docker Desktop Kubernetes Feature so we would like to use one single SQS Queue instead of having to spinup a new one for every developer that's testing changes in their local machines

**Comment by phelinor** [comment]
If support for multiple consumers is not desirable, what about support for https://github.com/localstack/localstack

**Comment by phelinor** [comment]
Any updates on this by any chance?
