### ISSUE TITLE
Image tag latest in docker hub points to a wrong release

### ISSUE THREAD

**Issue by tumido** [argoproj/argo-events#616]
**Describe the bug**
Image tag `latest` in docker hub points to a wrong release (v0.13.0)

**To Reproduce**
1. Go to any of the Argo Events images in [Docker Hub](https://hub.docker.com/)
2. Select "Tags" tab. For example here for the [`gateway-controller`](https://hub.docker.com/r/argoproj/gateway-controller/tags)
2. Compare "Digest" hash for `latest` and `v0.14.0` and `v0.13.0`
4. See that the `latest` tag hash matches `v0.13.0` instead of `v0.14.0`

The same is true for all the other Argo Events images.

**Expected behavior**
Tag `latest` refers to the latest release.

**Screenshots**
![image](https://user-images.githubusercontent.com/7453394/80193026-63355c80-8618-11ea-8dfb-38c1d559181b.png)

**Comment by VaibhavPage** [comment]
I'll update the `latest` tag over the weekend.

**Comment by VaibhavPage** [comment]
Updated, latest now points to v0.14.0
