### ISSUE TITLE
Introduce EventBus for events delivery

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#619]
**Is your feature request related to a problem? Please describe.**
Currently from Gateway to Sensor, there are 2 ways to deliver the messages: 

1.) HTTP POST; 
2.) Gateway -> NATS -> Sensor.

1.) is good for testing purpose, but it's not suitable for PROD deployment;
2.) introduces a pub-sub system in between but it exposes the detail to the user - NATS setting needs to be in both Gateway and Sensor.

**Describe the solution you'd like**

1. Introduce a new concept `EventBus` for each namespace, which represents a pub-sub like system configuration, or even an implementation;
2. All the events from Gateway are sent to `EventBus`;
3. Sensors listen to `EventBus` to read events;
4. `EventBus` implementation should be pluggable, options could be `NATS`, `Kafka`, `memory`, `k8s events`, ... recommend `NATS` for PROD deployment;
5. To simplify the implementation and make it secure, `EventBus` should be namespace isolated, which means each namespace uses its own `EventBus`;
6. A namesapce can have multiple `EventBus`, but there is a `default` one;

**Describe alternatives you've considered**

**Additional context**
Benefits:

- Naturally support pub-sub, 1 event can be subscribed by multiple sensors;
- Make it stable and reliable;
- More secure, eliminate direct HTTP calls in the lifecycle, Sensors don't need to expose a ClusterIP service.
- Make it easy to use, no `subscriber` in Gateway and `Subscription` in Sensor spec.

**Comment by whynowy** [comment]
@VaibhavPage @chaseterry

**Comment by VaibhavPage** [comment]
This is interesting. Few questions -

1) How do a gateway and sensor discover the event bus endpoint? I am assuming the gateway and sensor both discover the default eventbus (connect to NATS) out of the box and the user can override that behavior and publish/subscribe to a separate eventbus via a declaration in CR.

2) Will it change the structure of `dependencies` in the sensor CR?

**Comment by whynowy** [comment]
> This is interesting. Few questions -
> 
> 1. How do a gateway and sensor discover the event bus endpoint? I am assuming the gateway and sensor both discover the default eventbus (connect to NATS) out of the box and the user can override that behavior and publish/subscribe to a separate eventbus via a declaration in CR.

`EventBus` is a CRD object which is required for a namespace before using argo-events, this can be either created manually by the user, or with some automation such as namespace annotation. 

`Gateway` and `Sensor` need to reference to a `EventBus`, by default it references to a `EventBus` named `default` if the reference is missing. When `Gateway` sends message to `EventBus`, it sends to a subject with some naming convention.

> 2. Will it change the structure of `dependencies` in the sensor CR?

Maybe or may not, basically Sensors depend on EventSources, we can keep the same dependencies structure at this time, or enhance it only on EventSources.

> 
> Also, we can be a bit opinionated here and support NATS as the only mechanism for event bus to reduce complexity of a plugin system.

**Comment by VaibhavPage** [comment]
I think we should change the structure of the event dependency a little bit. The sensor should declare that it is interested in events from EventSource X and EventName Y instead of GatewayName X and EventName Y. To a sensor, it doesn't matter which gateway is responsible to listen to events from an external source. This will make the spec clearer. 

So it will look like,


```
  dependencies:
    - name: test-dep
      eventSourceName: webhook-event-source
      eventName: example
    - name: test-dep2
      eventSourceName: webhook-event-source
      eventName: example2
```

The gateway can publish a message to EventBus in the following format,

            `event-source-name/event-name

**Comment by whynowy** [comment]
👍

**Comment by ptemmer** [comment]
For clarity sake, are sensors and gateways already modified in 0.16 to support this?

**Comment by whynowy** [comment]
@ptemmer - it would be in releases after 0.16.
