### ISSUE TITLE
Cluster scope installation doesn't work

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#629]
**Describe the bug**
When `namespace` configuration is missing in the configmap, the controllers don't watch cluster scope but the default namesapce `argo-events`

**To Reproduce**
1. Remove `namespace` from configmap
2. create a Gateway/Sensor in namespace `default`
3. Gateway/Sensor deployment is not created.

**Comment by VaibhavPage** [comment]
Removing `namespace` from the configmap makes the controller watch objects in all namespaces not the instanceID. The instanceID is for sharding.

**Comment by whynowy** [comment]
> Removing `namespace` from the configmap makes the controller watch objects in all namespaces not the instanceID. The instanceID is for sharding.

Let me correct the content, I meant `namespace`, not `instanceID`.

**Comment by whynowy** [comment]
See https://github.com/argoproj/argo-events/blob/master/controllers/gateway/cmd/main.go#L43

@VaibhavPage

**Comment by whynowy** [comment]
@VaibhavPage - sorry, this is not an issue, I re-tested it, it worked.
