### ISSUE TITLE
Unable to access https://argoproj.github.io/setup/kafka/

### ISSUE THREAD

**Issue by opensourceonly** [argoproj/argo-events#646]
**Describe the bug**
Unable to access https://argoproj.github.io/setup/kafka/

Getting NOT FOUND
You just hit a route that doesn't exist... the sadness.

**To Reproduce**
1. Go to 'https://argoproj.github.io/setup/kafka/'
2. See error

**Expected behavior**
Actual stuff that is expected from the link ?

**Comment by whynowy** [comment]
Appreciate if you could give the steps that lead to this link from https://argoproj.github.io/. Thanks!
