### ISSUE TITLE
Mistakes in installation instructions

### ISSUE THREAD

**Issue by midcontinentcontrols** [argoproj/argo-events#647]
https://argoproj.github.io/argo-events/installation/

- gateway-controller-configmap and other namespaced resources are created in the default namespace, not argo-events, for both cluster-wide and namespace installation methods
- Manual installation CRD links have typos:
```
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/manifests/base/cdrs/gateway-crd.yaml
```
Should be:
```
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/master/manifests/base/crds/gateway-crd.yaml
```

Currently, all documented installation methods fail to give me a working installation.

**Comment by whynowy** [comment]
Thanks, it will be fixed in https://github.com/argoproj/argo-events/pull/632.

**Comment by vaporpin** [comment]
I installed argo events a few months ago and it was fine. Now all installation, cluster-wide, namespace, step by step doesn't work at all. Not sure what happened, 
Error given is "does not have minimum availability"
