### ISSUE TITLE
exec: "bin/gateway-controller": permission denied

### ISSUE THREAD

**Issue by maguowei** [argoproj/argo-events#650]
**Describe the bug**

`/bin/gateway-controller` in docker image `argoproj/gateway-controller:v0.15.0` is not executable

**To Reproduce**
1. docker run -it --rm --entrypoint sh argoproj/gateway-controller:v0.15.0
2. ls -al /bin/gateway-controller
output > -rw-r--r-- 1 root root 41499458 May  8 01:08 /bin/gateway-controller

**Expected behavior**
`/bin/gateway-controller` should be executable.
file permission may like -rwxr-xr-x

**Screenshots**
![image](https://user-images.githubusercontent.com/7894483/81382734-70d30200-9141-11ea-917a-7e0b90256a1c.png)

**Environment (please complete the following information):**
 - OS: MacOS Docker Desktop
 - Version: v0.15.0

@VaibhavPage please help

**Comment by maguowei** [comment]
`/bin/sensor-controller` in `argoproj/sensor-controller:v0.15.0` has the same problem.

**Comment by whynowy** [comment]
@VaibhavPage - Can you please check? It looks like all the images in the release have the same problem.

**Comment by VaibhavPage** [comment]
Yeah, there was a permission problem with binaries. I'll push updated images.

**Comment by whynowy** [comment]
Fixed.
