### ISSUE TITLE
Resource events Failed to list *unstructured.Unstructured: the server could not find the requested resource

### ISSUE THREAD

**Issue by stephenwolfe1** [argoproj/argo-events#652]
**Describe the bug**
Following the examples for a resource gateway setup results in the resource-events container streaming the same log error repeatedly.

**To Reproduce**
Followed the setup steps here https://argoproj.github.io/argo-events/setup/resource/

**Expected behavior**

**Screenshots**
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/38081080/81422308-a529cc80-9107-11ea-97da-dca12a839ffc.png">

**Environment (please complete the following information):**
 - OS: amazon-linux-2
- Kubernetes: v1.16.8-eks-e16311
- Version: argoproj/resource-gateway:v0.14.0

**Additional context**

**Comment by whynowy** [comment]
@stephenwolfe1 - do you still see this issue?

**Comment by lawliet89** [comment]
I got this after upgrading the Helm chart which introduced new CRDs. My "solution" was to delete the Helm release and re-install it.
