### ISSUE TITLE
http triggers error : invalid notification "A header you provided implies functionality that is not implemented" event-source=example

### ISSUE THREAD

**Issue by vaporpin** [argoproj/argo-events#654]
Hi,
I follow the example on http trigger, using minio gateway which will listen to bucket notifications and got the logs below when i do a "kubectl logs -n argo-events minio-gateway-podname main"

started listening to bucket notifications...  bucket-name=my_bucket_name event-source=example
invalid notification                          error="A header you provided implies functionality that is not implemented"

Can anyone advise what else i can do to debug or what does the error mean? Thank you.

**Comment by whynowy** [comment]
@vaporpin  - do you still have problem?
