### ISSUE TITLE
Error while sending events from gateway-client to sensor

### ISSUE THREAD

**Issue by duongnt** [argoproj/argo-events#655]
**Describe the bug**
Unable to send event from gateway-client to sensor.

Error in logs:

WARN[2020-05-11 04:39:18] failed to send the event                      error="Post http://livy-pod-sensor.argo-events:9300/: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"" event-source=livy-pod target="http://livy-pod-sensor.argo-events:9300/"
INFO[2020-05-11 04:39:18] dispatched event. although some of the dispatch operations failed, check logs for more info  event-source=livy-pod

**To Reproduce**
My set up was just a standard k8s event source, using default gateways, and a standard k8s event sensor/trigger. Everything was working for a while, and then I noticed the trigger was not running. I then noticed the sensor was not catching events, and tracing it to that error in the gateway-client logs.

**Expected behavior**
Things should keep working..

**Environment (please complete the following information):**
 - argo-events 0.15.0

**Comment by VaibhavPage** [comment]
Is there service with the name `livy-pod-sensor` in your cluster?

**Comment by duongnt** [comment]
> Is there service with the name `livy-pod-sensor` in your cluster?

Yes. This actually doesn't happen all the time, so the service is definitely there. Just that sometimes the connection is broken according to the logs.

**Comment by imakewebthings** [comment]
Seeing the same issue here with a setup extremely close to the stock tutorial webhook gateway -> workflows sensor. Also on 0.15.0. Also happens only a percentage of the time (~50% right now.) Sensor pod logs nothing, not receiving the request.

**Comment by duongnt** [comment]
I deployed nats and so far I haven't had any issues.

**Comment by terev** [comment]
On 0.15 we're seeing something similar happening with a pubsub gateway configured to send http events to the sensor. Looking at logs for the sensor it appears to restart sporadically a few times throughout the day, often within the same hour. There doesn't appear to be any log messages indicating a reason for the restart.

**Comment by VaibhavPage** [comment]
It looks like there is an issue in the underlying cloud-events-sdk dependency. I'll take a look.

**Comment by terev** [comment]
Is it related to an issue tracked in that project?

**Comment by valery-zhurbenko** [comment]
Hi!
Same things, part goes ok, part goes with error in webhook-gateway.

**Comment by brendanstennett** [comment]
Seeing the same thing following the webhook tutorial exactly running on docker-desktop Kubernetes.

**Comment by tatiesmars** [comment]
Getting the same error following the github webhook tutorial. 

Github display the response as 200 but the github gateway client report the malformed HTTP response warning. Thus not always triggering the job

**Comment by VaibhavPage** [comment]
I'll put a fix for the release scheduled this week.

**Comment by tatiesmars** [comment]
@Rotemy It got released in 1.16

**Comment by hashkanna** [comment]
I am getting this error intermittently as well. Installed Argo events using the steps mentioned here https://argoproj.github.io/argo-events/installation/

**Comment by Eji4h** [comment]
> @Rotemy It got released in 1.16

But some breaking change with my GitLab event.

**Comment by guoweis-outreach** [comment]
yeah, getting the same error here... after a while, it's gone by itself, but the behavior is inconsistent.

**Comment by whynowy** [comment]
Events delivery mechanism has been changed to use EventBus (backed by NATS Streaming) in v0.17.0, this issue should not exist any more. Can you try out the new version and feedback?

**Comment by whynowy** [comment]
I'd like to close this issue as it does not apply any more. 

If you see any issue with EventBus, please open a new issue.

**Comment by paravatha** [comment]
@whynowy, same error for file events/sendors. I am using gateway-client:v0.15.0, file-gateway:v0.15.0 images.
Can you please clarify what exactly is the fix?

**Comment by whynowy** [comment]
@paravatha - please upgrade to v0.17.0+, where we have lots of improvements with re-architecture.

**Comment by paravatha** [comment]
@whynowy 
I see v0.17 only for sensor
https://hub.docker.com/r/argoproj/sensor/tags

No v0.17 for others
https://hub.docker.com/r/argoproj/gateway-client/tags
https://hub.docker.com/r/argoproj/file-gateway/tags

**Comment by whynowy** [comment]
@paravatha - please read the doc below.

https://docs.google.com/document/d/1uPt2DyvzObEzZVbREqjW-o1gKCZ_hB8QS5Syw7_MLT8/edit#heading=h.oqurr3fme2wl
