### ISSUE TITLE
Sensor main logs polluted with opencencus errors?

### ISSUE THREAD

**Issue by duongnt** [argoproj/argo-events#656]
Seeing a lot of this:

{"level":"error","ts":1589240945.2911775,"logger":"fallback","caller":"http/transport.go:616","msg":"failed to get non-nil event from MessageToEvent","stacktrace":"github.com/argoproj/argo-events/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP\n\t/go/src/github.com/argoproj/argo-events/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go:616\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387\ngithub.com/argoproj/argo-events/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/src/github.com/argoproj/argo-events/vendor/go.opencensus.io/plugin/ochttp/server.go:92\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890"}
{"level":"error","ts":1589240960.2913158,"logger":"fallback","caller":"http/transport.go:616","msg":"failed to get non-nil event from MessageToEvent","stacktrace":"github.com/argoproj/argo-events/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP\n\t/go/src/github.com/argoproj/argo-events/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go:616\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387\ngithub.com/argoproj/argo-events/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/src/github.com/argoproj/argo-events/vendor/go.opencensus.io/plugin/ochttp/server.go:92\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890"}
{"level":"error","ts":1589240975.2912707,"logger":"fallback","caller":"http/transport.go:616","msg":"failed to get non-nil event from MessageToEvent","stacktrace":"github.com/argoproj/argo-events/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP\n\t/go/src/github.com/argoproj/argo-events/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go:616\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387\ngithub.com/argoproj/argo-events/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/src/github.com/argoproj/argo-events/vendor/go.opencensus.io/plugin/ochttp/server.go:92\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890"}

**Comment by whynowy** [comment]
Should not be an issue any more with EventBus introduced.
