### ISSUE TITLE
Set Up Minio Section at link https://argoproj.github.io/argo-events/setup/minio/ : Workflow doesn't trigger when file is uploaded into bucket

### ISSUE THREAD

**Issue by vaporpin** [argoproj/argo-events#660]
Workflow doesn't trigger when file is upload into bucket in. Logs in gateway pod below shows an error "A header you provided implies functionality that is not implemented" event-source=example". My minio is set up in default namespace. Will it matter? I did change the event source's endpoint in the yaml file to endpoint: minio-service.default:9000

INFO[2020-05-13 07:55:18] added a client for the subscriber             subscriber="http://minio-sensor.argo-events.svc:9300/"
INFO[2020-05-13 07:55:18] detected a new event-source...                event-source=minio-event-source
INFO[2020-05-13 07:55:18] state of the connection to gateway server     name=example state=READY value="{minio-service.default:9000 0xc0007cb0e0  true &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:artifacts-minio,},Key:accesskey,Optional:nil,} &SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:artifacts-minio,},Key:secretkey,Optional:nil,} [s3:ObjectCreated:Put] <nil>}"
INFO[2020-05-13 07:55:18] deleted event sources                         event-source="[]"
INFO[2020-05-13 07:55:18] new event sources                             event-source="[2410346322]"
INFO[2020-05-13 07:55:18] activating new event source...                event-source=example
INFO[2020-05-13 07:55:18] event source is valid                         event-source=example
INFO[2020-05-13 07:55:18] listening to events from gateway server...    event-source=example
INFO[2020-05-13 07:55:18] received a event source state update notification 
INFO[2020-05-13 07:55:18] initializing the node                         node-name=example
INFO[2020-05-13 07:55:18] node is running                               node-message="event source is running" node-name=example
INFO[2020-05-13 07:55:18] detected gateway update. updating gateway watchers 
INFO[2020-05-13 07:55:18] received a gateway resource update notification 
INFO[2020-05-13 07:55:18] checking if any new subscribers are added    

started processing the event source...        event-source=example
INFO[2020-05-13 07:55:18] parsing minio event source...                 event-source=example
INFO[2020-05-13 07:55:18] retrieving access and secret key...           event-source=example
INFO[2020-05-13 07:55:18] setting up a minio client...                  event-source=example
INFO[2020-05-13 07:55:18] started listening to bucket notifications...  bucket-name=my-bucket-name event-source=example
ERRO[2020-05-13 07:55:18] invalid notification                          error="A header you provided implies functionality that is not implemented" event-source=example

**Environment (please complete the following information):**
 - Google Kubernetes Engine

I did the exercise on webhook at link https://argoproj.github.io/argo-events/setup/webhook/ and it worked. Just couldn't get the minio as event example working. 

Please advise. Thanks for the help.

**Comment by vaporpin** [comment]
hi, found the error, the event source yaml file has header "events", it should be 
event:
        - s3:ObjectCreated:Put
        - s3:ObjectRemoved:Delete

**Comment by whynowy** [comment]
@vaporpin - is it resolved?

**Comment by malaniarpit** [comment]
The website is broken: https://argoproj.github.io/argo-events/setup/minio/. Event Notifications are not getting registered to minio for us as well.

**Comment by whynowy** [comment]
> The website is broken: https://argoproj.github.io/argo-events/setup/minio/. Event Notifications are not getting registered to minio for us as well.

It's moved to https://argoproj.github.io/argo-events/eventsources/setup/minio/
