### ISSUE TITLE
jsonBody not working on Kafka EventSource

### ISSUE THREAD

**Issue by descrepes** [argoproj/argo-events#661]
**Describe the bug**
When setting `jsonBody` to `true` in a Kafka EventSource, the body still base64 encoded

**To Reproduce**
1. Create a kafka eventsource
2. Create a kafka gateway
3. create a sensor with some body filters

**Expected behavior**
The body should be a raw json and not base64 encoded

**Environment (please complete the following information):**
 - Version [0.15.0]

**Additional context**
The actual code is:
https://github.com/argoproj/argo-events/blob/13b38c0d1c0ff07e404a4df50c6d3a391b495311/gateways/server/kafka/start.go#L134-L140

Should be something like this:
```
                        eventData := &events.KafkaEventData{
                                Topic:     msg.Topic,
                                Partition: int(msg.Partition),
                                Timestamp: msg.Timestamp.String(),
                        }
                        if kafkaEventSource.JSONBody {
                                eventData.Body = (*json.RawMessage)(&msg.Value)
                        } else {
                                eventData.Body = msg.Value
                        }
```

**Comment by ttnicoleau** [comment]
this bug appears again in release 1.8
