### ISSUE TITLE
Kafka EventSource timeout without TLS

### ISSUE THREAD

**Issue by descrepes** [argoproj/argo-events#662]
**Describe the bug**
On both 0.14.0 and 0.15.0, the kafka EventSource is not working without TLS.
The gateway timeout while trying to connect to brokers.

**To Reproduce**
1. Create a kafka eventsource without TLS
2. Create a kafka gateway
3. See error

**Expected behavior**
The gateway should connect to the Kafka brokers.

**Environment (please complete the following information):**
 - Version [0.14.0, 0.15.0]

**Additional context**
With the 0.13.0 everything is fine.
I removed this TLS part from the 0.15.0:
https://github.com/argoproj/argo-events/blob/13b38c0d1c0ff07e404a4df50c6d3a391b495311/gateways/server/kafka/start.go#L83-L94

and replaced it with just:
`consumer, err = sarama.NewConsumer([]string{kafkaEventSource.URL}, nil)`

And it's working again without TLS support.

**Comment by VaibhavPage** [comment]
hmm, the config TLS should have been empty if the TLS in the event source is not specified.
