### ISSUE TITLE
Can not define affinity and tolerations in the new gateway/sensor syntax

### ISSUE THREAD

**Issue by ozankabak** [argoproj/argo-events#663]
In the old gateway/sensor definition syntax, we were able to define affinities and tolerations for these pods under `spec.template.spec`. In the new syntax, the inner `spec` is removed and things like `serviceAccountName` is moved one level up to `spec.template`. However, we can not get away with simply moving everything one level up. For example, if we move affinity and toleration definitions one level up to `spec.template`, they do not work.

As a work-around, I am keeping the `spec.template.spec` structure in my setup (for now). However, this results in warnings like the one below:
```
spec.template.spec is DEPRECATED, it will be unsupported soon, please use spec.template.container  name=node-resource namespace=argo
```
Let's please ensure that all the relevant functionality supported via `spec.template.spec` works properly using the new syntax before removing `spec.template.spec`. I can help by verifying fixes in my setup.

**Comment by VaibhavPage** [comment]
We will keep on supporting the complete pod template for foreseeable future. @whynowy we need to address this in newer spec fields

**Comment by ozankabak** [comment]
Thanks for the prompt reply. I like the new syntax, but it seems it needs a little more work to support all the required functionality.

**Comment by whynowy** [comment]
@ozankabak - Could you share with us how your your use cases look like? what event sources you are using?

**Comment by ozankabak** [comment]
Sure. Currently, I am using Github and resource event sources. I am also planning to use MQTT in the future. I use resource events for reacting to internal cluster events and running appropriate workflows. I use Github (and MQTT in the future) events to interact with/ingest external data.

**Comment by ozankabak** [comment]
By the way, we have the same problem with the inline `service` field for gateways. The new syntax only allows ports to be specified, we can not use the full expressiveness of a normal service definition (like clusterIP assignments, selectors etc.). This is again a breaking change, so I am again resorting to the old way of doing things.

**Comment by whynowy** [comment]
Thanks @ozankabak. In regards to `service`, because different could provider has their own model for incoming traffic, you may use Load Balancer, or Ingress, even for LB or Ingress, different provider has different implementation (for example, you might want to you ELB, NLB when you are on AWS, or you want to use ALB by using ALB ingress-controller). In this case, we encourage you to set up you own model for incoming traffic instead of coupling it in Gateway spec. For you case, if you used to use a LB service, you can manage that service by you own.

**Comment by ozankabak** [comment]
@whynowy: I am not following. In that case, what would be the point of having the `service` field at all?

**Comment by whynowy** [comment]
Currently if you define `service` there, it will only create a `ClusterIP` service for your convenience, we will probably revisit this in the future to see if we really need to create that for you. 

If ppl want to expose the gateway deployment to public, a LB service or an Ingress is needed, if we handle all of those as before, at least we should get `ingress` included in the spec as well, but it would have no difference from those extra specs being managed by yourself, and it would increase the complexity for gateway controller, also the Gateway spec content would be increased a lot.

This is the reason why we simplified the spec. In short, currently if you want to create the Gateway for testing purpose, or it will be triggered from somewhere in the same cluster, you can add `service` in the spec, then a `ClusterIP` service will be created for you; If your Gateway service will be access from public, that you need to think about extra things such as load balancing, TLS, security group, WAF, etc, this is the same as the things you need to consider when you build a regular service running on k8s, in that case, we want you to create the LB or Ingress and manage them by yourself.

**Comment by ozankabak** [comment]
OK, that sounds reasonable. In this case, the only thing that seems missing in the inline `service` definition syntax is the `clusterIP` field. With this field, the new syntax would retain almost all of the functionality for internal convenience services ((including headless services, which would be specified by a `None` value).

**Comment by ptemmer** [comment]
What about nodeSelector property?
