### ISSUE TITLE
docker build fails: Forbidden path outside the build context

### ISSUE THREAD

**Issue by rossigee** [argoproj/argo-events#677]
**Describe the bug**
Docker image fails to build from a fresh master clone.

**To Reproduce**
1. `git clone https://github.com/argoproj/argo-events`
2. `cd argo-events`
3. `docker build .`

```
...
 ---> 18c2efeaaa99
Step 5/6 : COPY ../. .
COPY failed: Forbidden path outside the build context: ../. ()
```

**Expected behavior**
A simple, successful build without requiring external assets would be nice :)

**Comment by whynowy** [comment]
I don't think this Dockerfile is used for any binary image build, probably it was used for old CI? @VaibhavPage

**Comment by VaibhavPage** [comment]
Yeah, this is an old Dockerfile and should not be used for build. I'll remove it in next PR.
