### ISSUE TITLE
url_test hangs when behind proxy

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#70]
**Describe the bug**
Running `make test` hangs on the store package and specifically on the url_test.go `TestURLReader` test. 

**To Reproduce**
1. run `make test`

**Expected behavior**
The test should pass and the test should not be dependent on an internet connection or the outside world.

We should use the `httptest` package to run a localhost server while running this test.

**Comment by shrinandj** [comment]
I'll take a look. Another option would be to mock the call to `client.Get`. Will check if there's a way to do that.
