### ISSUE TITLE
SASL authentication to Kafka

### ISSUE THREAD

**Issue by openrory** [argoproj/argo-events#703]
**Is your feature request related to a problem? Please describe.**
I may be doing something wrong, but I can't seem to find out how to make a SASL connection to a Kafka Event Source. 

**Describe the solution you'd like**
It would be nice to have SASL authentication to a Kafka Event Source and Event Trigger, besides a TLS connection. In particular, I am using SASL_SSL and Plain text as SASL mechanism.

**Describe alternatives you've considered**
I am not a TLS expert, so I am not aware of a TLS-type solution to authenticate via SASL.

**Additional context**
Not applicable.

**Comment by VaibhavPage** [comment]
I'll add this feature in next release.

**Comment by openrory** [comment]
Fantastic, thanks for the quick reply! Let me know if I can be of any help, say, during testing.

**Comment by ddlees** [comment]
@VaibhavPage Looks like this may have fallen off your radar.

My team uses a hosted Kafka service for our production deployments and we have no means of changing the authentication strategy. Can you provide an update for when we can expect Kafka SASL_SSL/SASL_PLAINTEXT auth to be supported? Thank you!

**Comment by joshuajorel** [comment]
I can take a look at filing a PR for this since we also need SASL Authentication.

**Comment by surajrajan-maf** [comment]
any luck with SASL auth for kafka source?

**Comment by joshuajorel** [comment]
@surajrajan-maf will try to file it this week

**Comment by joshuajorel** [comment]
Updates, had a two week hiatus unfortunately. Got Kafka working on my local development machine. Will file the PR on the weekend.
