### ISSUE TITLE
GCP PubSub Using Existing Topics/Subscriptions

### ISSUE THREAD

**Issue by victorthevong** [argoproj/argo-events#725]
**Is your feature request related to a problem? Please describe.**
Hello, we would like to see argo events gcp pubsub pipeline be configurable to use preexisting topics and subscriptions so the event source does not have to handle the creation of both.

**Describe the solution you'd like**
Realistically you should be able to add other fields to indicate if the given topic is already created and given that you are given credentials either through file or gke workload identity be able to link correctly (If you need the service account to have specified permissions for reading and writing that could also be done). 

The subscription portion can be included within the Event source creation as well given that they currently happen sequentially, or you can have it be apart of the sensor portion. Although having changes to code are probably easier where the event source creation of topic and subscription is handled.

**Describe alternatives you've considered**
Well we tried thinking of potential ways to work this out but given that currently if the event source fails to create a topic it also fails to create a subscription. So even if we had a preexisting topic it isn't possible to link the sensor to the subscription (not to my knowledge at least)

**Comment by pbonito** [comment]
Hello,  the impossibility to reuse existing subscriptions is a significant limitation since it forces to use a service account with PubSub.editor role instead of PubSub.subscriber, violating minimum privilege principle.
Are there any plans to introduce this enhancement on next releases? Is there any other workaround to use Argo events with PubSub having   PubSub.subscriber role?

**Comment by apurvchandra** [comment]
We too would like this being fixed please.

**Comment by whynowy** [comment]
Anybody wants to try out the RC images for the new feature?  Please refer to #778 for the change detail.

```
        - name: EVENTSOURCE_IMAGE
          value: gcr.io/whynowy/eventsource:1.623
        image: gcr.io/whynowy/eventsource-controller:1.623
```

**Comment by apurvchandra** [comment]
Will try to test and update.

**Comment by apurvchandra** [comment]
@VaibhavPage  when this will be released and date.

**Comment by VaibhavPage** [comment]
We will release v0.17.1 on 4th Aug.

**Comment by apurvchandra** [comment]
@whynowy @VaibhavPage , This worked as suggested, had a bit of tough time figuring out the eventname which is being defined in EventSource manifest and referenced in dependencies section of Sensor. 

I hope the documentation will be clear on this referencing .

**Comment by whynowy** [comment]
Thanks @apurvchandra !
