### ISSUE TITLE
The `JoinChannel` api call is fully deprecated for new Slack applications

### ISSUE THREAD

**Issue by spkane** [argoproj/argo-events#726]
**Describe the bug**
Slack has deprecated the channels.join api call and suggests to use conversations.join instead. API calls now return with `method_deprecated` for `JoinChannel` when you are using a Slack app created after June 10th (or so).

Slack API links:
https://api.slack.com/methods/channels.join
https://api.slack.com/methods/conversations.join

Code:
https://github.com/argoproj/argo-events/blob/693e2109d33d152175cb38dc63198b9517a2032d/sensors/triggers/slack/slack.go#L115

**To Reproduce**
1) Create a new slack app
2) Try to use it with argo event Slack Triggers. You will get an error when argo events tries to send a message to Slack.

**Expected behavior**
1) argo-events should be able to send a message using both older and newer Slack Apps.

**Environment (please complete the following information):**
 - OS: Linux (Kubernetes)

**Additional context**

`JoinConversation` is already written in the Slack package: https://github.com/slack-go/slack/blob/c664c83937182df61c6532cff2569ad50ec6b117/conversation.go#L536

JoinCoversation requires a channel id instead of channel name. This is different then the current call which expects a name. For backwards compatibility it would make sense to still expect a name and then lookup the ID and pass it to JoinConversation.

**Note**: `github.com/slack-go/slack` is the new community fork of `github.com/nlopes/slack` and is most likely what should be used going forward.

**Comment by spkane** [comment]
cc/ @lucassha

**Comment by spkane** [comment]
At the bare minimum, this code change fixes things:

```
sensors/triggers/slack/slack.go
114:	_, _, _, err = api.JoinConversation(channel)
```

**Comment by shimmerjs** [comment]
Did you need to change the log level to get the error?  I am seeing my Slack trigger fail silently on v0.16.0 but it is definitely getting the event from the gateway

**Comment by spkane** [comment]
@shimmerjs I don't think so, but it couldn't hurt. I am pretty sure that we at least got a warning that the call was deprecated. However, if your Slack app is new then this is almost certainly your issue. We are running a fork at the moment to work around it while we are testing.

**Comment by whynowy** [comment]
@spkane - Would you like to help do a testing with the change? I can give you RC images.

**Comment by spkane** [comment]
@whynowy Yes. I'd be happy to give it a test.
