### ISSUE TITLE
webhook multiple http registrations

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#73]
**Describe the bug**
An error is encountered in the webhook signal when you have a webhook with a certain path, delete it, and then re-create it with the same path. (assuming both signal streams connect to the same webhook signal pod and the pod doesn't die between requests)

**To Reproduce**
1. k create -f examples/webhook-sensor.yaml
2. k delete sensor webhook-example
3. k create -f examples/webhook-sensor.yaml

**Expected behavior**
One should be able to delete and re-create sensors without having to modify and/or change the spec.

**Additional context**
This is related to how multiplexers & servers work. We were initially creating a separate server with a new `ServeMux` on every `Listen()`, however we cannot do this since we cannot start 2 servers listening on the same port (and now the port is fixed at signal startup).

**Comment by VaibhavPage** [comment]
addressed in #92 . A webhook gateway can be configured with multiple endpoint with different http methods. Deleting and recreating sensor has no effect on gateway as they are completely decoupled from each other.
