### ISSUE TITLE
Eliminate the code dependency on argo workflow

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#733]
**Is your feature request related to a problem? Please describe.**
argo-events currently has 2 dependencies on argo-workflow:
1. `argo` binary in sensor Dockerfile
2. `github.com/argoproj/argo` import in source code, this is mainly used in https://github.com/argoproj/argo-events/blob/master/sensors/triggers/argo-workflow/argo-workflow.go.

Every time when argo-workflow releases new features, both of these 2 places need to be upgraded.

Considering CLI won't have changes frequently, frequency of upgrading CLI version could unfollow `argo` release frequency. But the code dependency sometimes makes big differences. For example, if there's a new field in `workflow` spec, if we don't upgrade, the new field will not be recognized by argo-events, thus the submitted workflow will not be the same as user provides.

**Describe the solution you'd like**
Eliminate the code dependency on `argo-workflow`.

Don't convert the workflow spec provided by the user to a `workflow` object.

**Describe alternatives you've considered**

**Additional context**

**Comment by tmshn** [comment]
Let me just clarify: AFAIK, the current implementation offers two options to kick argo workflows from sensors

1. Using `argoWorkflow` in TriggerTemplate: (this is what described in this issue) Render a workflow yaml and exec `argo` cli using `os/exec`
2. Using `k8s` in TriggerTemplate: Create any k8s resource from an "unstructured" object using `k8s.io/client-go/dynamic`

Hence, for those who want to be free from the version skew problem, the latter option should work (while it lacks some features like `generateName`), right?

**Comment by tumido** [comment]
Just throwing an idea in here:

Argo has a [REST API](https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json) which supports all that submit/resubmit/retry... requests. That means it can be used instead of bundling `argo` CLI binary and also argo codebase into here. Both can be eliminated.

**Comment by whynowy** [comment]
> Just throwing an idea in here:
> 
> Argo has a [REST API](https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json) which supports all that submit/resubmit/retry... requests. That means it can be used instead of bundling `argo` CLI binary and also argo codebase into here. Both can be eliminated.

REST API is another option, but it need to give argo-server URL.
