### ISSUE TITLE
The "metrics" field is dropped by the sensor when spawning a new workflow

### ISSUE THREAD

**Issue by benhackett4** [argoproj/argo-events#738]
Argo supports a `metrics` field on workflow objects. (For [example](https://github.com/argoproj/argo/blob/7581025ffac0da6a4c9b125dac3173d0c84aef4f/examples/custom-metrics.yaml#L10-L19)). When I create a sensor object that contains a `metrics` field in the workflow template object, it appears fine when I do `kubectl get sensor webhook -o yaml -n argo-events`. However, when an event occurs and a workflow is actually created, it is somehow missing the `metrics` field.

### Installing argo
```
$ tree
.
├── kustomization.yaml
└── overlays
    └── workflow-controller-configmap.yaml

1 directory, 2 files
```

```
$ cat kustomization.yaml 
bases:
  - https://github.com/argoproj/argo/manifests/cluster-install

patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml
```

```
$ cat overlays/workflow-controller-configmap.yaml 
apiVersion: v1
data:
  metricsConfig: |
    disableLegacy: true
    enabled: true
    path: /metrics
    port: 9090
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
```

`kustomize build . | kubectl apply -f -`

### Installing argo-events
`kubectl create ns argo-events`

```
$ ls
kustomization.yaml

$ cat kustomization.yaml 
bases:
  - https://github.com/argoproj/argo-events/manifests/cluster-install
``` 

`kustomize build . | kubectl apply -f -`

### Installing A Basic Webhook
I just followed this [link](https://argoproj.github.io/argo-events/quick_start/), except I added a tiny `metrics` section to the sensor:
```
$ curl https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/webhook.yaml > supplied-sensor.yaml

$ diff supplied-sensor.yaml my-sensor.yaml 
30a31,39
>                 metrics:
>                   prometheus:
>                     - name: duration  # Metric name (will be prepended with "argo_workflows_")
>                       labels:
>                         - key: workflow_type
>                           value: "webhook-hello"
>                       help: "Duration of argo workflow"
>                       gauge:
>                         value: "{{workflow.duration}}"

```

### Then After Triggering a Workflow
`kubectl get workflow $WORKFLOW_NAME -o yaml` # <- No "metrics" field :(

**Comment by whynowy** [comment]
Thanks for reporting this, it should be related to https://github.com/argoproj/argo-events/issues/733.

**Comment by benhackett4** [comment]
@whynowy Gotcha, thanks :)

**Comment by terev** [comment]
@whynowy would it be related even if the sensor doesn't use the argo-workflow trigger type? the webhook sensor example uses the k8s trigger type

**Comment by terev** [comment]
I think this is a slightly different issue than #733 . I'm new to kubernetes extension development so there may be some incorrect details. But i think what's happening is the k8s trigger type is being used to create a workflow object. Because a local registry of types is used for decoding the artifact's unstructured content, the type scheme is version locked to the pkg in go.sum (which is quite behind [v2.5.2](https://github.com/argoproj/argo-events/blob/master/go.mod#L16)) .

**Comment by terev** [comment]
I think it's possible to utilize the discovery api plus the dynamic client to eliminate these baked in dependencies.

**Comment by terev** [comment]
https://github.com/lawrencegripper/terraform-provider-kubernetes-yaml/blob/master/kubernetes/resource_kubernetes_yaml.go#L236 this terraform provider has a nice example of how to do something like this without relying on the codec factory

**Comment by whynowy** [comment]
@terev - Could you verify if you still have the issue with v0.17.0?

**Comment by terev** [comment]
@whynowy tysm i'll report back once we give this a try

**Comment by whynowy** [comment]
This should have been fixed in the latest version, please reopen or create a new issue if not.
