### ISSUE TITLE
Swagger documentation appears to be incorrect / out of sync across releases

### ISSUE THREAD

**Issue by shimmerjs** [argoproj/argo-events#744]
**Describe the bug**

Try to build out any examples using the documented API under `api/openapi-spec/swagger.json`.

`0.16.0` tag does not have EventSource, although EventSource definitely existed for release 0.16.0: https://raw.githubusercontent.com/argoproj/argo-events/v0.16.0/api/openapi-spec/swagger.json

After #701 was merged, EventSource was added, but Gateway was removed: https://raw.githubusercontent.com/argoproj/argo-events/145fd9a940833c6e5b398994305d85847215d957/api/openapi-spec/swagger.json

Now, on master, as of #735, it appears that Gateway was correctly removed... however, that does not help anyone that wants to install the latest official release, 0.16.0.  In fact, it doesn't look like there is an installation path for any version of argo events that isn't associated with an api spec that is broken in some way...

There should be some commit between `0.16.0` and #735 which had a spec doc that included both `v1alpha1.EventSource` & `v1alpha1.Gateeway`, but there doesn't appear to be one.

**To Reproduce**

**Expected behavior**
API spec allows for defining all resources from the examples...

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**

**Comment by VaibhavPage** [comment]
Fixed in v0.17.0

**Comment by VaibhavPage** [comment]
Closing the issue. Let us know if you still face any issues with swagger.
