### ISSUE TITLE
I followed the tutorials/01-introduction/ and pod was not created

### ISSUE THREAD

**Issue by 2044smile** [argoproj/argo-events#751]
**Describe the bug**
I followed the tutorial but no workflow pod was created in the namespace argo.

**To Reproduce**
1. Go to https://argoproj.github.io/argo-events/installation/
2. create namespace argo-events
```
k create ns argo-events
```
3. Install argo-events 
```
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
```
3. Go to https://argoproj.github.io/argo-events/tutorials/01-introduction/
```
# create the webhook event source
kubectl -n argo-events apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/event-sources/webhook.yaml

# Create the webhook gateway.
kubectl -n argo-events apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/gateways/webhook.yaml

# Create the webhook sensor.
kubectl -n argo-events apply -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/sensors/webhook.yaml

# gateway pod port-forward
kubectl -n argo-events port-forward webhook-gateway-24rd6-6c69d486b9-chx2t 12000:12000

curl -d '{"message":"this is my first webhook"}' -H "Content-Type: application/json" -X POST http://localhost:12000/example
```

**Expected behavior**
A workflow was created in the argo list, but no workflow pod was created in the argo namespace.

**Screenshots**
#### - request
![image](https://user-images.githubusercontent.com/47213853/87737610-5fc80080-c816-11ea-83ed-4189555c288e.png)
#### - request recevied
![image](https://user-images.githubusercontent.com/47213853/87737662-8ab25480-c816-11ea-9cae-946c80c1815b.png)
#### - gateway logg
![image](https://user-images.githubusercontent.com/47213853/87737685-9ef65180-c816-11ea-907b-212b4038de7f.png)
#### - sensor log
![image](https://user-images.githubusercontent.com/47213853/87737817-ef6daf00-c816-11ea-8da0-2c6bf634f1bd.png)
#### - argo list
![image](https://user-images.githubusercontent.com/47213853/87737887-188e3f80-c817-11ea-9151-f82810157d85.png)
#### - argo get po (was not created wf pod)
![image](https://user-images.githubusercontent.com/47213853/87737914-25ab2e80-c817-11ea-8d94-b4ced9bc2e28.png)

**Environment (please complete the following information):**
 - OS: macOS
 - minikube
   - Version 1.11.0
 - kubectl version
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

I will wait for your answer

**Comment by whynowy** [comment]
Please share your `argo` was installed in cluster scope or namespace scope.

**Comment by 2044smile** [comment]
This issue was related to the service account of Argo
