### ISSUE TITLE
Installation guide has many broken URLs, preventing complete install

### ISSUE THREAD

**Issue by mtchllbrrn** [argoproj/argo-events#775]
The [installation guide's](https://argoproj.github.io/argo-events/installation/) step-by-step instructions include broken URLs for each of the CRD install steps and a few of the controller install steps (Steps 5, 6, 7, 8, 9, and 11 under "Step-by-Step Installation" header).

 ```
$ kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/base/sensor-controller/sensor-controller-configmap.yaml
error: unable to read URL "https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/base/sensor-controller/sensor-controller-configmap.yaml", server reported 404 Not Found, status code=404
```

I am a new user hoping to install argo-events for the first time, but it is not clear to me how to proceed with these errors in the documentation.

EDIT: The Installation Guide URL posted above was presenting a "Step-by-Step Installation" section with the 12 numbered steps referenced in the original issue, but now the URL doesn't present this section.  I suppose it was a bit of old documentation that has since been removed?

**Comment by VaibhavPage** [comment]
@mtchllbrrn step-by-step guidelines are deprecated. please use https://argoproj.github.io/argo-events/installation/#using-kubectl

**Comment by terev** [comment]
@VaibhavPage that's a great doc, had no idea this exists. this would be a great link to add to the v0.17.0 release notes

**Comment by VaibhavPage** [comment]
Closing the issue. We will track this issue in #776 .
