### ISSUE TITLE
Eventsource pod fails

### ISSUE THREAD

**Issue by digibank-rons** [argoproj/argo-events#802]
After upgrading to Argo-events v0.17 from v0.15 I get and error in the Eventsource pod - {"error":"failed to load auth.yaml. err: Config File \"auth\" Not Found in \"[/etc/eventbus/auth]\"","level":"error","msg":"failed to start eve
ntsource server","time":"2020-08-02 21:11:03"}

***Reproduce
Deploy a Eventsource in v0.17 

**Environment (please complete the following information):**
EKS cluster
Kube 1.16
ArgoEvents v0.17

**Comment by whynowy** [comment]
@digibank-rons - Can you share your eventbus spec?

**Comment by digibank-rons** [comment]
@whynowy Hey Derek, here it is, I used the example, appreciate your help -

apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: none
#      containerTemplate:
#        resources:
#          requests:
#            cpu: "10m"
#      metricsContainerTemplate:
#        resources:
#          requests:
#            cpu: "10m"
#      antiAffinity: false
#      persistence:
#        storageClassName: standard
#        accessMode: ReadWriteOnce
#        volumeSize: 10Gi

**Comment by whynowy** [comment]
@digibank-rons - There's a bug with EventBus `AuthStrategyNone`, it's been fixed in https://github.com/argoproj/argo-events/pull/798.

Please use `token` for now.

**Comment by digibank-rons** [comment]
@whynowy - it worked, Thank you so much for the quick help.
