### ISSUE TITLE
Sensor-controller throws errors about wrong config map version

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo-events#81]
**Describe the bug**
I keep seeing the sensor-controller spewing log messages about old config map version even though there were no changes made to the config-map.

**To Reproduce**
1. Run the sensor-controller.
2. The sensor-controller pod logs the following messages:
```
ERROR: logging before flag.Parse: W0806 16:24:00.173164       1 reflector.go:341] github.com/argoproj/argo-events/controller/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 608242 (608445)
time="2018-08-06T16:24:01Z" level=info msg="detected ConfigMap update. updating the controller config."
ERROR: logging before flag.Parse: W0806 16:36:04.188869       1 reflector.go:341] github.com/argoproj/argo-events/controller/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 609334 (609828)
time="2018-08-06T16:36:05Z" level=info msg="detected ConfigMap update. updating the controller config."
ERROR: logging before flag.Parse: W0806 16:45:17.198521       1 reflector.go:341] github.com/argoproj/argo-events/controller/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 610721 (610887)
time="2018-08-06T16:45:18Z" level=info msg="detected ConfigMap update. updating the controller config."
ERROR: logging before flag.Parse: W0806 16:54:28.208333       1 reflector.go:341] github.com/argoproj/argo-events/controller/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 611778 (611949)
time="2018-08-06T16:54:29Z" level=info msg="detected ConfigMap update. updating the controller config."
ERROR: logging before flag.Parse: W0806 17:06:17.222437       1 reflector.go:341] github.com/argoproj/argo-events/controller/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 612832 (613300)
time="2018-08-06T17:06:18Z" level=info msg="detected ConfigMap update. updating the controller config."
ERROR: logging before flag.Parse: W0806 17:14:14.231619       1 reflector.go:341] github.com/argoproj/argo-events/controller/config.go:62: watch of *v1.ConfigMap ended with: too old resource version: 614188 (614209)
time="2018-08-06T17:14:15Z" level=info msg="detected ConfigMap update. updating the controller config."
```
**Expected behavior**
There should be no such errors in the logs

**Comment by magaldima** [comment]
I see these errors as well on a Kubernetes 1.9 cluster. What version is your cluster?

**Comment by magaldima** [comment]
Others have encountered this issue long before: https://github.com/kubernetes/kubernetes/issues/22024. I'm not sure if this means the same in this version of Kubernetes/client-go.

Looks like it comes about from `etcd <--> apiserver` and then `apiserver <--> client`.

**Comment by magaldima** [comment]
Looks like this may be due to "slow moving resources" from https://github.com/kubernetes/kubernetes/issues/55230:

> getting a "version too old" error and having to start over listing and watching again is normal for watches of slow-moving resources. that's an expected usage pattern

not sure much we can do on this for now besides ignoring these statements, but let's stay up-to-date on any developments here.

**Comment by magaldima** [comment]
@VaibhavPage can we revisit this? Do you think this was addressed in k/k?

**Comment by VaibhavPage** [comment]
closing this issue as there is nothing we can do here.
