### ISSUE TITLE
eventsources should not throw HTTP 500 errors when a payload does not include all required information. (slack)

### ISSUE THREAD

**Issue by spkane** [argoproj/argo-events#811]
**Describe the bug**
The code at this line throws a hard error which generates a 500 when the secrets verifier is missing in the header. It should really throw a more specific HTTP error that can be used to detect this situation. This is especially useful for simple health checks that might need to ensure the route is up without requiring complex payloads to get past the auth, or slack signature check in this case. 

https://github.com/argoproj/argo-events/blob/ded50d62ac6a2d9e21c94863994d8c6e74d2d067/eventsources/sources/slack/start.go#L247

**To Reproduce**

```
curl -I https://127.0.0.1:12000/slack-interact
HTTP/1.1 500 Internal Server Error
Date: Tue, 04 Aug 2020 20:02:56 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 47
Connection: **keep-alive**
```

**Expected behavior**

Return something like a 401 instead, since this signals that we were able to talk to the server, but were not authorized to get a response.

```
curl -I https://127.0.0.1:12000/slack-interact
HTTP/1.1 401 Unauthorized
Date: Tue, 04 Aug 2020 20:02:56 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 47
Connection: **keep-alive**
```

**Environment (please complete the following information):**
 - Argo Events: [v0.17.0] - with gcr.io/whynowy/eventsource-controller:1.618 (and for sensro-controller and sensor)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by spkane** [comment]
At an initial glance through this, it feels like the code could use an easy way to pass up a specific HTTP error here:

https://github.com/argoproj/argo-events/blob/ded50d62ac6a2d9e21c94863994d8c6e74d2d067/eventsources/sources/slack/start.go#L116

**Comment by debankur1** [comment]
we can add another function like
common.SendUnauthorizedErrorResponse(writer,err.Error()) and based on the error type from 
func NewSecretsVerifier(header http.Header, secret string) (sv SecretsVerifier, err error)
 can be switched between function calls like common.SendInternalErrorResponse(writer, err.Error()) or common.SendUnauthorizedErrorResponse(writer,err.Error())

**Comment by whynowy** [comment]
Does this resolve your problem?

**Comment by spkane** [comment]
@whynowy The description does indeed look like it would fix the problem, if that is implemented.

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/pull/823

**Comment by spkane** [comment]
@whynowy One thought regarding closing this ticket. The health check endpoint in pull/823 should completely solve our issue, and I will test it very soon, however I'd still argue that this slack code should not be returning a 5xx HTTP error since the actually underlying problem is  an authentication/verification issue. It might be worth keeping this around to track that fix/improvement, but I'll leave that up to your discretion.

**Comment by whynowy** [comment]
@spkane - That makes sense, will update it.
