### ISSUE TITLE
Rate Limit Event Creation

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-events#812]
**Is your feature request related to a problem? Please describe.**
With very active queue systems in our case kafka we can get quite a bit of messages at a time. With no way to rate limit the creation of sensors (in our case argo workflows sensors) we can easily overload the k8s api. We would like to limit the number of events that get fired and run at the same time via a limit at the argo events level. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@zachaller - Is #829 to address this?

**Comment by zachaller** [comment]
Yes it is, was not sure if it's something that could be implemented at a higher level or more globally but we needed something now because we have very busy kafka topics that can easily overload our k8s api creating thousands of pods per second but it is a bursty load that we can easily spread out with rate limiting

**Comment by whynowy** [comment]
> Yes it is, was not sure if it's something that could be implemented at a higher level or more globally but we needed something now because we have very busy kafka topics that can easily overload our k8s api creating thousands of pods per second but it is a bursty load that we can easily spread out with rate limiting

Generally, I don't think we should implement a rate limiter from sensor part, as that is not argo-events' responsibility to do that, but the downstream should be more reliable. But I think your implementation on the specific event source part could be a workaround. @VaibhavPage

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/pull/829
