### ISSUE TITLE
Notify Events

### ISSUE THREAD

**Issue by 2020testuser** [argoproj/argo-events#813]
This is not a bug actually. I want to invoke (trigger) a non-aws lambda serverless function (using the function url) when I put a file in ibm s3 bucket.
Could anyone please let me know whether the above is possible using Argo-Events? 
Thanks in advance!

**Comment by VaibhavPage** [comment]
You can use `http` trigger. Take a look at https://argoproj.github.io/argo-events/triggers/http-trigger/#openfaas

**Comment by 2020testuser** [comment]
@VaibhavPage - Thanks! I checked http trigger. For my requirement, when I PUT an object in non-aws and non-minio s3 , I want to perform http trigger. Could you please let me know whether that is possible? That is not clear. Thanks in advance!

**Comment by akulkarnihawk1995** [comment]
> @VaibhavPage - Thanks! I checked http trigger. For my requirement, when I PUT an object in non-aws and non-minio s3 , I want to perform http trigger. Could you please let me know whether that is possible? That is not clear. Thanks in advance!

Hey, were you able to resolve this issue ?
