### ISSUE TITLE
Optional simple authentication for webhook related eventsources

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#821]
**Is your feature request related to a problem? Please describe.**
EventSources like `webhook`, `slack` do not have any auth strategy to protect them from unauthorized accessing.

**Describe the solution you'd like**
Add `secretKeySelector` in `webhook` CRD, when it is in place, use the secret content to authenticate the request.

The http request sent to the endpoint needs to have `Authorization: Bearer xxxxxxxxxxxxxx` in place and that is used for authentication.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
The `Authorization` header could be added by the client, or an intermediary.
