### ISSUE TITLE
SNS messages should validate the message signature

### ISSUE THREAD

**Issue by JonathanSerafini** [argoproj/argo-events#831]
**Is your feature request related to a problem? Please describe.**
SNS endpoint subscriptions must expose a public facing HTTP server ( unless I missed something ) and therefore make it possible for untrusted sources to post messages to the event bus as long as the message comply with basic message format. 

**Describe the solution you'd like**
The SNS source should verify the signature of the message to ensure that a) the message was sent via an approved TopicARN and b) the message was correctly signed by AWS. 

**Describe alternatives you've considered**
Workaround so far involves using Basic Auth via the Ingress to protect the endpoint. Though this ends up difficult to automate / orchestrate in a manner that doesn't expose secrets in Git. ( i.e. can't simply use ExternalSecrets ). 

**Additional context**
Example of SNS signature verification : https://github.com/aws/aws-sdk-go/issues/567

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@JonathanSerafini - There's a [simple authentication approach](https://github.com/argoproj/argo-events/blob/master/docs/webhook-authentication.md) available, not sure if that is doable for SNS to add a customized header easily, maybe through a Lambda? But I would love to see the signature verification approach in place.

**Comment by JonathanSerafini** [comment]
Yeah for now i'm opting for SNS > SQS > Events, seemed like an overall simpler solution.
Thanks for the link though, I might end up using that for other usecase

**Comment by whynowy** [comment]
> Yeah for now i'm opting for SNS > SQS > Events, seemed like an overall simpler solution.
> Thanks for the link though, I might end up using that for other usecase

Yup, that's a good one, more resilient and avoid exposing an endpoint.

**Comment by RiyaJohn** [comment]
@whynowy I would like to work on this issue, from my initial understanding I think we should add a verification step here https://github.com/argoproj/argo-events/blob/master/eventsources/sources/awssns/start.go#L114.  Tried something from ref. links https://github.com/RiyaJohn/argo-events/commit/035f2318ee30b2110d30e25c6b55f4815f8322e8 can you let me know if I am in the right direction

**Comment by whynowy** [comment]
@RiyaJohn - I'm very glad to hear that, thank you! I myself never tried that, after checking docs from AWS and the [link](https://github.com/aws/aws-sdk-go/issues/567) above, it looks like you are in the right direction, but please put the `verify` function in start.go please. Looking forward to seeing you PR.

**Comment by RiyaJohn** [comment]
@whynowy Raised PR, please take a look at it
