### ISSUE TITLE
Official ARM docker images 

### ISSUE THREAD

**Issue by dgiebert** [argoproj/argo-events#836]
# Summary

As in the main project it would be great if there are mulit-arch images for this piece of the argo project.

# Motivation

Currently building a Raspberry Pi Cluster with a working argo installation, and want to extend it with event driven workflows.

# Proposed solution

Rework the Makefile in sync with argo: https://github.com/argoproj/argo/pull/2491
Rework the Github Workflow in sync with argo: https://github.com/argoproj/argo/pull/3744

If this is desired I could take care and create a PR for it ?

**Comment by whynowy** [comment]
@dgiebert - sure, welcome for the contribution!

**Comment by flavio** [comment]
I was looking for ARM64 support and I found this issue and its PR. It's great to see it has been merged recently :partying_face: 

Is the fix going to be included inside of the next release of argo-events? Currently `v1.0.0-rc3` is the latest release, its tagging happened 7 days before the PR got merged, hence there are no ARM64 container images available yet.
Are they going to be available with `v1.0.0-rc4` or with the final `v1.0.0`? :pray:

**Comment by whynowy** [comment]
@flavio - We just released v1.0.0, unfortunately `arm64` is not there - I tried to do it, but failed, there are still some problems with the new experimental `docker buildx` feature. I hope we can get it addressed in next release.

**Comment by flavio** [comment]
@whynowy there's no reason to feel sorry :)

Is there anything that I could do to help, are these issues tracked somewhere?

**Comment by dgiebert** [comment]
Found the issue and will create a PR soon.

For clean repos `rm dist/*` does not work as there are no files in the dist folder, will therefore force it to ignore this error
