### ISSUE TITLE
File Eventsource in v0.17.0

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo-events#852]
# Summary

Base from this instruction: https://argoproj.github.io/argo-events/setup/file/. I should be able to do an exec -it on the container called file-events on the file event source pod. Only the main container is created and I can't exec to it. Am i missing something here?

![image](https://user-images.githubusercontent.com/47080916/91637188-416e3b00-ea39-11ea-880d-d74f48b92af1.png)

I also tried to do an exec on the main container using the kubectl cli but I'm getting the an error that /bin/bash does not exist. There's no file-events container created as said in the instructions.

# Motivation

I want to be able to make the file setup work. I was able to make File setup work with v0.15.0

**Comment by whynowy** [comment]
EventSource POD is now based on `scratch`, which does not allow you to ssh to it. The doc needs to be updated. To try that out, you can mount a configmap to the EventSource POD, or use a PVC, and then update them from external of the POD.

**Comment by lueenavarro** [comment]
Thanks that worked, one more thing that I needed to do was to set polling to true. My PVC is a s3fs bucket, i guess that's why it won't working without polling.

**Comment by dhaldergit** [comment]
> Thanks that worked, one more thing that I needed to do was to set polling to true. My PVC is a s3fs bucket, i guess that's why it won't work without polling.
@lueenavarro , Can you please share me the event source yaml specification. I am also facing the same issue.
