### ISSUE TITLE
NATS EventBus ExactOnce triggering

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#853]
**Is your feature request related to a problem? Please describe.**
NATS Streaming guarantees `AtLeastOnce` delivery, which means it is possible one message is delivered more than once. Need to have something in place to make sure `ExactOnce` delivery.

**Describe the solution you'd like**
Each NATS streaming client is independent from others, a simple in-memory cache is good to make sure `ExactOnce`.

**Describe alternatives you've considered**
Cache all the acked message IDs/Seqs of last amount of time (i.e. 5 mins) in memory, drop (or ack again) if duplicate message is found.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by VaibhavPage** [comment]
Lets make the timeout configurable.
