### ISSUE TITLE
If subscribe to event bus fails the sensor ends up in a state without a subscription

### ISSUE THREAD

**Issue by terev** [argoproj/argo-events#860]
**Describe the bug**
If the sensor reconnects to the nats server it needs to recreate the subject subscription. If the connection succeeds but re-subscribe does not, the sensor ends up in a state without an active subscription. This causes the sensor to be in a useless state where it's sitting with an open connection to a nats server but not receiving any messages.

Edit:
This bad state can occur if subscribing fails during startup as well.

**Expected behavior**
The sensor should continue attempting to create the subscription, probably at the cadence of this ticker https://github.com/argoproj/argo-events/blob/master/sensors/listener.go#L167 is fine.

**Screenshots**
Example logs of this event occurring: 

```json
{"level":"info","ts":1599069602.989456,"logger":"argo-events.sensor","caller":"sensors/listener.go:175","msg":"reconnected to NATS streaming server.","sensorName":"*************","clientID":"client-3409727250"}
{"level":"info","ts":1599069602.9895031,"logger":"argo-events.sensor","caller":"driver/nats.go:165","msg":"closing subscription...","sensorName":"*************","clientID":"client-3409727250"}
{"level":"info","ts":1599069602.9895215,"logger":"argo-events.sensor","caller":"driver/nats.go:167","msg":"subscription on subject eventbus-argo-events closed","sensorName":"*************","clientID":"client-3409727250"}
{"level":"info","ts":1599069604.9898312,"logger":"argo-events.sensor","caller":"sensors/listener.go:181","msg":"started to re-subscribe events for triggers [*************] with client client-3409727250","sensorName":"*************"}
{"level":"error","ts":1599069606.9958572,"logger":"argo-events.sensor","caller":"driver/nats.go:153","msg":"failed to subscribe to subject eventbus-argo-events","sensorName":"*************","clientID":"client-3409727250","stacktrace":"github.com/argoproj/argo-events/eventbus/driver.(*natsStreaming).SubscribeEventSources\n\t/home/runner/work/argo-events/argo-events/eventbus/driver/nats.go:153\ngithub.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.5\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:182"}
{"level":"error","ts":1599069607.0044267,"logger":"argo-events.sensor","caller":"sensors/listener.go:184","msg":"failed to re-subscribe to eventbus","sensorName":"*************","clientID":"client-3409727250","error":"stan: subscribe request timeout","stacktrace":"github.com/argoproj/argo-events/sensors.(*SensorContext).ListenEvents.func1.5\n\t/home/runner/work/argo-events/argo-events/sensors/listener.go:184"}
```

**Environment (please complete the following information):**
 - Kubernetes: 1.15
 - Argo: 2.9.5
 - Argo Events: 1.0.0-rc1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
This is an interesting finding, something needs to be there to `save` the subscription.

**Comment by shmargum** [comment]
i think i have experienced a similar issue (maybe the same) when performing rolling updates to my nodes, i think its because the event bus needs to load first? gonna try adding some priorities to the eventbus pods maybe

**Comment by whynowy** [comment]
@shmargum - please also share your case you can can catch it. My understanding is what @terev reported is really an edge case - reconnection is good but subscribing fails. I know there was some connection retry issue in v0.17.0, but v1.0.0 is much better, though re-subscription protection is not there yet.

**Comment by terev** [comment]
Just noticed this issue can occur during sensor startup as well. I can most likely work on a fix for this issue tomorrow if no one else gets to it.

**Comment by whynowy** [comment]
> Just noticed this issue can occur during sensor startup as well. I can most likely work on a fix for this issue tomorrow if no one else gets to it.

Thanks, please!
