### ISSUE TITLE
Image tags in 1.0.0 manifests have not yet been bumped

### ISSUE THREAD

**Issue by terev** [argoproj/argo-events#864]
**Describe the bug**
Image tags in 1.0.0 manifests have not yet been bumped. They're stuck at 0.17.0 atm.

**Expected behavior**
Installing 1.0.0 should install 1.0.0 image versions.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by VaibhavPage** [comment]
I'll bump them as part of my PR for changelog.

**Comment by whynowy** [comment]
@terev - check the latest one - https://raw.githubusercontent.com/argoproj/argo-events/v1.0.0/manifests/install.yaml

**Comment by terev** [comment]
I use kustomize so this file https://www.github.com/argoproj/argo-events/tree/master/manifests%2Fbase%2Fkustomization.yaml is overriding tags

**Comment by whynowy** [comment]
We will update the master one to `latest`

**Comment by terev** [comment]
I think a version tag would be better so that my deployment doesn't get upgraded randomly when the next upgrade comes out. This is the case with the nature of mutating an existing tag

**Comment by whynowy** [comment]
Why do you build it based on master? Curious about how you are building your environment, appreciate if you can share it.

**Comment by terev** [comment]
Our kustomize file looks like:
```yaml
namespace: argo-events

bases:
  - github.com/argoproj/argo-events/manifests/cluster-install?ref=v1.0.0-rc1

resources:
  - event-bus-native.yaml
```
so we get whatever tag is default in that reference. we don't reference master we have a version pinned.

**Comment by whynowy** [comment]
This looks good, you always get the manifests in that tag, then what is the problem with `master` branch on `latest`?

**Comment by terev** [comment]
So you're saying tagged commits will reference manifests with the respective image tag instead of latest? And manifests on master will point at images tagged with latest?

**Comment by whynowy** [comment]
Correct.

**Comment by terev** [comment]
@whynowy ok cool i misunderstood, that sounds perfect 👍

**Comment by whynowy** [comment]
👍

**Comment by terev** [comment]
Ty!
