### ISSUE TITLE
Apply eventbus CR labels to the underlying resources.

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#866]
**Is your feature request related to a problem? Please describe.**
Pass on the labels from the `native` event bus custom resource to the actual resources created by the controller.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/pull/876
