### ISSUE TITLE
multi-arch image build issues

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#870]
**Describe the bug**

There are several issues with current multi-arch image build process:

1. Github action is not reliable when there are multiple workflows need to be triggered. Currently there are 2 actions when a tag is dropped, the `docker-image` workflow is not guaranteed to start every time - I tried to drop `v1.0.0` tag 3 times, it only ran once, check the actions history.

2. The docker image build is **TOO** slow. There are 5 binaries need to build for each arch, however for each binary, each arch, it builds all the 5 binaries, it makes the total build time at least 5 times longer. This issue can be addressed by separating the code build stage to 5.

3. This one the most deadly. `docker buildx` and pushing to docker hub works for all the images built from `scratch`, but it is not friendly to `sensor-image`, because it's based on `alpine` and contains argo binary which makes it larger than others. The issue is the same as what is described [here](https://github.com/docker/buildx/issues/367). I tried maybe more than 20 times, only succeeded once.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.18.6]
 - Argo: [e.g. v2.9.4]
 - Argo Events: [e.g. v1.0.0]

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dgiebert** [comment]
1. I am not to familiar with Github Actions, seems a bit odd that it does not trigger it correctly.

2. Usually this is done by using the docker cache, can you send me a link to an action where it took longer ?

3. Might be worth a try to load to get the image and then use docker push instead.

**Comment by whynowy** [comment]
> 1. I am not to familiar with Github Actions, seems a bit odd that it does not trigger it correctly.
> 2. Usually this is done by using the docker cache, can you send me a link to an action where it took longer ?
>    Basically it should build it once and then use the cache to copy it into different images.
> 3. Might be worth a try to load to get the image and then use docker push instead.

I tried to run it on my laptop, you can do the same.
