### ISSUE TITLE
Github event source issue

### ISSUE THREAD

**Issue by johnae** [argoproj/argo-events#871]
**Describe the bug**
I've been unable to use the github event source using argo events 1.0. The issue is that the event itself doesn't seem to get dispatched from the the event source. More specifically, this is where things go wrong somehow:

https://github.com/argoproj/argo-events/blob/700bfbd0bfcd4a0aafcc670aaa5553d9e0b19923/eventsources/sources/github/start.go#L120

The reason I believe that to be the case is that I see this in the log:

```
{"level":"info","ts":1599500795.9731917,"logger":"argo-events.eventsource","caller":"github/start.go:85","msg":"received a request, processing it...","eventSourceName":"github","eventSourceType":"github","eventName":"xxxxx","eventSourceName":"github","eventName":"xxxxx","endpoint":"/push","port":"12000","http-method":"post"}
{"level":"info","ts":1599500795.9732895,"logger":"argo-events.eventsource","caller":"github/start.go:119","msg":"dispatching event on route's data channel","eventSourceName":"github","eventSourceType":"github","eventName":"xxxxx","eventSourceName":"github","eventName":"xxxxx","endpoint":"/push","port":"12000","http-method":"post"}
```
And then nothing after that... but I would expect to see a line saying "request successfully processed". What also happens is that the http request times out since there is no response.

**Expected behavior**
I would expect the event to reach the sensor.

**Screenshots**

**Environment (please complete the following information):**
 - Kubernetes: v1.18.8
 - Argo Events: v1.0.0

**Additional context**
I've tried using regular webhook event sources which seem to not have this problem.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@VaibhavPage - Could you look into this? I only have a k3d testing cluster on my laptop, not able to set up an environment for Github event source.

**Comment by whynowy** [comment]
@johnae is it public github or a private one?

**Comment by whynowy** [comment]
Close it as no update.
