### ISSUE TITLE
Migrate project to Go 1.15

### ISSUE THREAD

**Issue by kmai** [argoproj/argo-events#881]
**Is your feature request related to a problem? Please describe.**
It's really difficult to contribute as the project uses Go 1.11 which has been deprecated (at least, [CONTRIBUTING.md](CONTRIBUTING.md) says so). 

**Describe the solution you'd like**
We should bump Go to 1.15 so that we work with a supported version, and have an up-to-date guide on how to contribute

**Describe alternatives you've considered**
Sticking to 1.11 will get worst and worst with time, but it's an option

**Additional context**
Setting a new env is painful, specially if you're new to the project and want to submit a small fix.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
I think the problem here is just making the doc up-to-date.

**Comment by kmai** [comment]
Most likely, yeah. Go 1.11 is not longer supported anyway
