### ISSUE TITLE
Webhook and sensor log to stderr

### ISSUE THREAD

**Issue by l15k4** [argoproj/argo-events#884]
**Describe the bug**
Webhook and sensor log to stderr which polutes stackdriver with errors.

**Screenshots**
![Screenshot from 2020-09-17 08-09-43](https://user-images.githubusercontent.com/518855/93426957-45191300-f8bd-11ea-90f8-0e7442bb592a.png)

**Environment (please complete the following information):**
 - Kubernetes: [e.g. v1.16]
 - Argo: [e.g. v2.10]
 - Argo Events: [e.g. v1.0.0]

**Reason**
This is probably related to logrus package. Its default output stream is stderr.

**Solution**
Good precaution could be using `severity` instead of `level` in the json object, it would at least make this common problem disappear on stackdriver.

**Comment by whynowy** [comment]
It should addressed by making zap log configurable with a configmap.

**Comment by l15k4** [comment]
The Argo workflow sidecar container `wait` also logs everything to stderr ... it is really hard to setup monitoring for anything running on Argo right now.

**Comment by whynowy** [comment]
Curious about how you concluded it logs to stderr? I thought it was just the keyword `level`, however it seems not. Can you explain more?

**Comment by l15k4** [comment]
We are using stackdriver where you can see what goes to stdout and stderr

**Comment by whynowy** [comment]
I see. This is an easy fix. By default zap log use stderr as default output, we can change it to stdout. Question about the keyword `level`, is it reserved in stackdriver? or what is the problem?

**Comment by l15k4** [comment]
I meant, if the keyword was `severity` instead of `level`, then stackdriver would use it to determine the `severity` ... ie. even if it was put on `stderr` and there was `severity=info` then stackdriver would classify it as `info` ... otherwise stackdriver decides by type of output `stderr => ERROR` and `stdout => INFO`

**Comment by whynowy** [comment]
I see. Then updating info output to stdout should resolve the issue.

**Comment by l15k4** [comment]
Correct, I'm from the JVM world where it is very strict and one usually finds only problems on stderr ... but I've noticed that there are errors on stdout very casually in the golang world :-)
