### ISSUE TITLE
Add Support for Bitbucket Server Webhooks

### ISSUE THREAD

**Issue by fabb** [argoproj/argo-events#891]
**Is your feature request related to a problem? Please describe.**
Github and Gitlab are already supported as trigger sources by Argo Events, it would be nice if Bitbucket Server would be supported too. Actions like PR creations or pushes should be able to trigger PR builds via Argo Events and Workflows.

**Describe the solution you'd like**
Add Bitbucket Server as an officially supported event source.
https://argoproj.github.io/argo-events/concepts/event_source/

**Describe alternatives you've considered**
General Webhooks could be used maybe.

**Additional context**
Here is the Bitbucket Webhook documentation: https://support.atlassian.com/bitbucket-cloud/docs/event-payloads/

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by fabb** [comment]
Related: https://github.com/argoproj/argo-cd/pull/1808

**Comment by VaibhavPage** [comment]
fyi #917

**Comment by abdennour** [comment]
any update? Ideally, the support includes a full example using argo event, sensor, bitbucket repo,,.. so on

**Comment by MnifR** [comment]
Update?

**Comment by dorroddorrod** [comment]
Any updates ?

**Comment by alexec** [comment]
The core Argo team does not use Bitbucket, so it is hard for us to test well.

I don't think this is hard, you can look at the Argo CD example to see how it is done. Would anyone like to submit a PR?

**Comment by svmaris** [comment]
I'm working on it

**Comment by svmaris** [comment]
To be clear, I'm talking about *Bitbucket Server* (the self-hosted version), not Bitbucket Cloud (Atlassians SaaS offering). There seems to be some confusion as the original request by @fabb is mentioning both. Bitbucket Cloud is a different product with a different API.

**Comment by jackivanov** [comment]
@svmaris Have you had a chance to PR your solution d37f5126b7a6abc00cdc38422bc7527ae60c20a0?

**Comment by aslafy-z** [comment]
@jackivanov here's the related PR https://github.com/argoproj/argo-events/pull/1223

**Comment by jackivanov** [comment]
Does this implementation also include notification for Bitbucket Server regarding builds statuses?

**Comment by weaselchops** [comment]
Hi, how do I validate the Bitbucket server webhook?
It doesn't seem to validate the "secret" and still triggers the workflow.
The secret will be in the  _X-Hub-Signature_ header. https://confluence.atlassian.com/bitbucketserver/manage-webhooks-938025878.html#Managewebhooks-webhooksecrets

Using this as a template: https://github.com/argoproj/argo-events/blob/master/examples/event-sources/bitbucketserver.yaml
It has no issue creating the webhook on the BB server, with the correct secret.

Any ideas?

**Comment by tooptoop4** [comment]
@weaselchops are u saying the secret auth is not being enforced?

**Comment by weaselchops** [comment]
> @weaselchops are u saying the secret auth is not being enforced?

It seems not...
The worklow is still triggered via a straight curl, no auth headers.
I ended up adding an IP  whitelist to the ingress for the bitbucket server.

**Comment by tooptoop4** [comment]
@weaselchops i wonder if something like https://github.com/go-playground/webhooks/blob/v5.17.0/bitbucket-server/bitbucketserver.go#L129-L141 is needed
