### ISSUE TITLE
Support for multiple Kafka broker hosts and partitions

### ISSUE THREAD

**Issue by venksel** [argoproj/argo-events#892]
**Is your feature request related to a problem? Please describe.**
We are using Kafka/MSK as our event source and want to specify multiple host broker URLs for redundancy-- I understand Kafka broker URL is an array, however, it does not work if we pass multiple URLs as illustrated below:
http://prntscr.com/umrt71
Additionally, we also would like to specify more than one partition for a given Kafka topic, however, again we see this behavior whereby it does not take multiple partitions as a array value in YAML

**Describe the solution you'd like**
Enable support for multiple broker URLs and partitions in the YAML config

**Describe alternatives you've considered**
We don't have any alternative solution at the moment.

**Additional context**
http://prntscr.com/umrt71

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Multiple partitions can be achieved by using multiple event sources, and define multiple dependencies and [trigger conditions](https://github.com/argoproj/argo-events/blob/master/docs/trigger-conditions.md) in the sensor object.

**Comment by venksel** [comment]
Thanks Derek, will get it a shot. However, we still need to be able to
specify more than one Broker URLs in the YAML config as we are planning to
deploy Argo Events to a production env.

**Comment by jiteshgupta1995** [comment]
@whynowy is there a way to use one event source for multiple partitions? As I understand, if I have to deploy multiple applications and if each uses multiple partitions then there will be a lot of event source K8's pods. Which I would definitely like to avoid.

**Comment by whynowy** [comment]
Yes, you can define multiple events in one eventsouce object, the rest thing in sensor is same.

**Comment by jiteshgupta1995** [comment]
> Yes, you can define multiple events in one eventsouce object, the rest thing in sensor is same.

Derek, I mean one Kafka source with multiple partitions in a single event source.

**Comment by whynowy** [comment]
Yes, that's what I said, one eventsouce object, with different eventName(map key).

**Comment by whynowy** [comment]
Like 'example' and 'example-tls' in


examples/event-sources/kafka.yaml

**Comment by jiteshgupta1995** [comment]
> Like 'example' and 'example-tls' in
> 
> examples/event-sources/kafka.yaml

I see it now. Thanks, Derek.
