### ISSUE TITLE
FMEA Testing

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-events#899]
Perform FMEA testing similar to Argo Workflows:

https://github.com/argoproj/argo/issues/3751

Expect to need to make changes as a result.

**Comment by alexec** [comment]
@whynowy as a Q2 deliverable - we need to think about how to progress this. Should I set-up a meeting?

**Comment by whynowy** [comment]
Understand the behaviour under the following disruptions:

## Environment Disruptions

| Disruption | Behavior | Recovery |
|-|-|-|  
| Kubernetes API network issues. | Errors printed in controller logs; EventBus runs well; Errors printed in EventSource Pod when it's `resource` type, it works well for other types; Errors printed in Sensor Pod when it's a `workflow` or `k8s` type trigger, it runs well for the other types of triggers | Full recovery |
| Controller Pod deleted | A new controller Pod is created | Full recovery |
| EventSource Pod deleted | New EventSource Pod created | Full recovery |
| Sensor Pod deleted | New Sensor Pod created | Full recovery |
| Kubernetes node deleted mid execution | New Pods created | Full recovery  | 
| Node unavailable | Wait until it is | Full recovery |
| Not enough resources to schedule pods.  | Wait until it is  | Full recovery |
| Extremely high number of concurrent Events. | The behavior varies for different EventSource | |

# User Disruptions

| Disruption | Behavior | Recovery |
|-|-|-|  
| EventSource object deleted | No new events | Full recovery |
| Sensor object deleted | No action is triggered, when the Sensor object is recreated, it automatically picks up the missing actions | Full recovery |
| EventBus object deleted and recreated | Errors printed in EventSource and Sensor Pods | Full recovery |
| EventBus object updated with different `auth` strategy | | |
| EventBus object updated with different spec other than `auth` | | |
| Malformed EventSource spec | | |
| Malformed Sensor spec | | |
| Malformed EventBus spec | | |

**Comment by alexec** [comment]
Looks good so far. Can you set-up a meeting in the next, say 2 weeks, with me and @VaibhavPage ?

**Comment by alexec** [comment]
Please can you to list more disruptions:

* What happens to a message from different event sources (especially calendar) when the event source pod is offline?
* What happens to a message from the event sources when the event bus is offline?
* What happens to a message from a trigger to an external system when we cannot connect to that system?

Start with just the top 2 or 3?

**Comment by alexec** [comment]
https://www.verygoodsecurity.com/blog/posts/kubernetes-multi-az-deployments-using-pod-anti-affinity

**Comment by whynowy** [comment]
Close this as all the related issues were addressed.
