### ISSUE TITLE
Signal Stream type amqp does not work

### ISSUE THREAD

**Issue by jewel77** [argoproj/argo-events#90]
**Describe the bug**
After running amqp-sensor.yaml, the sensor amqp-example is in Error phase with the message "the signal 'amqp' does not exist with the signal universe. please choose one from: [calendar resource nats webhook]"

**To Reproduce**
1. Following Quick Start Guide to set up Argo Events and Argo,
2. kubectl apply -f examples/amqp-sensor.yaml
3. kubectl describe sensor.argoproj.io/amqp-example
4. See "Phase: Error" and "Message:       the signal 'amqp' does not exist with the signal universe. please choose one from: [calendar resource nats webhook]"

**Expected behavior**
Signal Guide says that amqp type is supported, and I see amqp is under signals/stream/builtin, but why the sensor with signal type amqp does not work.

**Comment by magaldima** [comment]
This is a caveat of the current architecture. The `quickstart` guide has a note on step 3:
> Note: In order to have a useful cluster for Argo Events, you will need to separately deploy the various signal services that you wish to support.

Ideally, built-in signals should not rely on additional components. This issue is currently being addressed in #92 .

**Comment by VaibhavPage** [comment]
#92 is now merged
