### ISSUE TITLE
Argo EventBus runAsUser configuration

### ISSUE THREAD

**Issue by mailtoraja18** [argoproj/argo-events#903]
**Describe the bug**
The event bus controller runs as user configured by me (999) . But the eventbus resource generated fails for below. Is there a way to configure the runasuser (pod securitycontext)  ?

apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      # Optional, defaults to 3. If it is < 3, set it to 3, that is the minimal requirement.
      replicas: 3
      # Optional, authen strategy, "none" or "token", defaults to "none"
      auth: token

Events:
  Type     Reason     Age              From                                    Message
  ----     ------     ----             ----                                    -------
  Normal   Scheduled  5s               default-scheduler                       Successfully assigned argo-events/eventbus-default-stan-0 to ip-100-72-10-188.ec2.internal
  Normal   Pulled     4s (x2 over 4s)  kubelet, ip-100-72-10-188.ec2.internal  Container image "nats-streaming:0.17.0@sha256:be42a6dcfd820c1605b5f0ad5f99997eb1df73fca192fbde8a163a0bc5c62131" already present on machine
  Warning  Failed     4s (x2 over 4s)  kubelet, ip-100-72-10-188.ec2.internal  **Error: container has runAsNonRoot and image will run as root**
  Normal   Pulled     4s (x2 over 4s)  kubelet, ip-100-72-10-188.ec2.internal  Container image "synadia/prometheus-nats-exporter:0.6.2@sha256:e6a6cfe30f3cbae8bad1e8dd6f6c68f4401e9b563aeb2df73769f1b4dad39a0f" already present on machine
  Warning  Failed     4s (x2 over 4s)  kubelet, ip-100-72-10-188.ec2.internal  **Error: container has runAsNonRoot and image will run as root**

**Comment by jinnjwu** [comment]
any guideline how to config it ?

**Comment by Markieta** [comment]
Depending on the 

> any guideline how to config it ?

https://argoproj.github.io/argo-events/APIs/#argoproj.io/v1alpha1.EventBus

Seems like you can set pod-level `securityContext` on NATSBus ([NativeStrategy](https://argoproj.github.io/argo-events/APIs/#argoproj.io/v1alpha1.NativeStrategy)) and [JetStreamBus](https://argoproj.github.io/argo-events/APIs/#argoproj.io/v1alpha1.JetStreamBus).

In their [ContainerTemplate](https://argoproj.github.io/argo-events/APIs/#argoproj.io/v1alpha1.ContainerTemplate) you can set container-level `securityContext`.
