### ISSUE TITLE
Calendar sensor with  Schedule:    @every 30s triggers only once 

### ISSUE THREAD

**Issue by DmitryBe** [argoproj/argo-events#91]
**Describe the bug**
Calendar sensor with  Schedule:    @every 30s triggers only once 

**To Reproduce**
create sensor with following config:

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: inline-example
  namespace: playground
  labels:
    sensors.argoproj.io/controller-instanceid: axis
spec:
  signals:
    - name: time
      calendar:
        schedule: "@every 30s"
  triggers:
    - name: inline-workflow-trigger
      resource:
        namespace: playground
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: job-hello-world-
              spec:
                entrypoint: whalesay
                templates:
                  -
                    container:
                      args:
                        - "hello world"
                      command:
                        - cowsay
                      image: "docker/whalesay:latest"
                    name: whalesay

specifying `schedule: "@every 30s"` i expect it to repeat every 30 seconds;
sensor triggers once and transitions to `Phase:             Complete`

**Comment by VaibhavPage** [comment]
Working on fixing the bug.
