### ISSUE TITLE
OAuth Slack Token Logged In Clear 

### ISSUE THREAD

**Issue by christophercutajar** [argoproj/argo-events#944]
**Describe the bug**
The OAuth base64 Slack token used by the Slack trigger is logged in the clear. 

**To Reproduce**
1. Follow the [steps](https://argoproj.github.io/argo-events/triggers/slack-trigger/) to create a Slack App and a Slack trigger.
2. Fire Slack trigger
3. Check the slack webhook sensor logs.

```
sensor-qrlrb-58d497d595-q9dmh main 2020-11-09T10:11:50.147597554Z slack-go/slack2020/11/09 10:11:50 chat.go:217: Sending request: channel=random&text=webhook+triggered%21&token=xoxb-xxxx-xxx-xxx
```

**Expected behavior**
OAuth Slack token not logged in the clear in the log files.

**Screenshots**
Not Applicable.

**Environment (please complete the following information):**
 - Kubernetes: 1.15.12-gke.20
 - Argo: v2.11.6
 - Argo Events: v1.0.0

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
This seems to be an issue of [slack-go/slack](https://github.com/slack-go/slack), could you check if there's a way to disable it, or raise an issue in `slack-go/slack` repo?

**Comment by christophercutajar** [comment]
I'll check the code how this is used in Argo Events and if this an issue with `slack-go/slack`, I'll move ahead and raise the issue with them.

**Comment by whynowy** [comment]
Thanks @christophercutajar !

**Comment by christophercutajar** [comment]
@whynowy

**Comment by christophercutajar** [comment]
This line of log is only logged `if api.Debug() is true` in `chat.go`. From Argo this can be avoided if `slack.OptionDebug(true)` is changed to `slack.OptionDebug(false) in https://github.com/argoproj/argo-events/blob/8d3904a03ca867a595aeac671d81f70884944c0b/sensors/triggers/slack/slack.go#L107

**Comment by whynowy** [comment]
> Looking this in more detail, this line of log is only logged `if api.Debug() is true` in `chat.go`. From Argo this can be avoided if `slack.OptionDebug(true)` is changed to `slack.OptionDebug(false)` in https://github.com/argoproj/argo-events/blob/8d3904a03ca867a595aeac671d81f70884944c0b/sensors/triggers/slack/slack.go#L107

Thanks! A PR to fix it?

**Comment by christophercutajar** [comment]
Yeah @whynowy, will work on it and perform some testing to make sure that setting it to `false` will actually solve the issue.

**Comment by christophercutajar** [comment]
Thanks @whynowy for taking this and apologies for not solving this earlier.
