### ISSUE TITLE
Can the event bus be deployed clusterwide

### ISSUE THREAD

**Issue by lukaslentner** [argoproj/argo-events#945]
Hi,

I have managed to deploy the 3 argo-events controllers clusterwide and now I have eventbus, sensor, eventsource in my project-namespace.

Is it possible to also centralize the eventbus and not having it per namespace? How?

Thankx
Lukas

**Comment by whynowy** [comment]
We don't have support for cluster wide EventBus, but if you have a NATS streaming service managed by yourself, you can use `exotic` NATS EventBus, see https://github.com/argoproj/argo-events/blob/master/docs/eventbus.md#exotic.

**Comment by lukaslentner** [comment]
OK. Thankx
