### ISSUE TITLE
New Custom Gateways

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#96]
Add gateways for Slack, AWS(SNS & SQS notifications), Trello, Docker, Twitter, GCP Pub/SUb. Specs to follow. 

Closes #45, #21, #5

**Comment by VaibhavPage** [comment]
Addressed in PR #100

**Comment by VaibhavPage** [comment]
#100

**Comment by magaldima** [comment]
I'm closing this for now as most of these are done.. in the future if there is a need to add a new gateway (core and/or community) then individual issues can be raised.
