### ISSUE TITLE
Support headers for Kafka trigger

### ISSUE THREAD

**Issue by khaledkbadr** [argoproj/argo-events#968]
**Is your feature request related to a problem? Please describe.**
 Kafka trigger basically is a message. It would be good to have the ability to define the headers for that Kafka message. Users can easily parameterize the headers on-the-fly as well. When using `CloudEvents` it sets the event type, subject...etc in Kafka headers, not the body.

**Comment by elventear** [comment]
Taking a stab at this issue in https://github.com/argoproj/argo-events/pull/3365
