### ISSUE TITLE
argo-events calendar gateway/trigger/workflow from documentation not working.

### ISSUE THREAD

**Issue by ttelfer** [argoproj/argo-events#97]
**Describe the bug**
Followed quick start guide:

https://github.com/argoproj/argo-events/blob/master/docs/quickstart.md

-Running basic hello world workflow works.

Then followed the guide for calendar gateway/sensor:

https://github.com/argoproj/argo-events/blob/master/docs/tutorial.md#calendar

There are no workflows in `argo list` after many minutes of waiting.

**Expected behavior**
Expected workflows to run. `argo list`shows nothing.

**Environment (please complete the following information):**
 - Azure AKS 
 - Kubernetes 1.10.8

Any help would be greatly appreciated. Also let me know if I can provide any additional information.

**Comment by ttelfer** [comment]
@VaibhavPage Thanks for responding. How would I check that?

I also just tried rerunning the kubectl commands:

`kubectl create --namespace=argo-events -f ...`

Still nothing.

**Comment by VaibhavPage** [comment]
Also did you switch namespace to `argo-events` after performing `kubectl create namespace argo-events` and before creating sensor and gateway controllers?

**Comment by ttelfer** [comment]
@VaibhavPage forgive me I'm fairly new to argo and kubernetes. I don't remember switching namespaces. From what I read in the kubectl documentation using `kubectl create --namespace` creates it in the given namespace. Is that correct?

Also, what command would I run to get logs from the two controllers you mentioned?

**Comment by VaibhavPage** [comment]
it looks like sensor and gateway controller are created in `default` namespace. You can first start deploying them in `argo-events` by executing following commands

```
kubectl create -n argo-events -f hack/k8s/manifests/sensor-controller-configmap.yaml
kubectl create -n argo-events -f hack/k8s/manifests/sensor-controller-deployment.yaml
kubectl create -n argo-events -f hack/k8s/manifests/gateway-controller-configmap.yaml
kubectl create -n argo-events -f hack/k8s/manifests/gateway-controller-deployment.yaml
```

Once these configmaps and deployments are created, can you post output of:
```
kubectl -n argo-events get deployements
kubectl -n argo-events get configmaps
```

**Tip**: there is nice utility called `kubectx` https://github.com/ahmetb/kubectx which let you switch your kubectl context and namespace easily

As you have already created gateway, gateway configmap and sensor in `argo-events` namespace, gateway and sensor controllers should pick these up.

**Comment by ttelfer** [comment]
That did it! Thanks for your help. It seems like the documentation may need to be updated.

Also, thank you for the utility.

**Comment by VaibhavPage** [comment]
I'll add note on switching namespace in next PR.
