### ISSUE TITLE
Resource Event Source - return old object in event data

### ISSUE THREAD

**Issue by scottweitzner** [argoproj/argo-events#982]
## Problem Description
@samlouiscohen and I noticed that when a sensor is activated for a resource event source only the object body (the current state of the object) is passed in. The event object also has the old object stored, but this is not passed to the `ResourceEventData` object.

See [here](https://github.com/argoproj/argo-events/blob/2d1b328e0ce812a21f482272b707aba638b68fb9/eventsources/sources/resource/start.go#L132)

### Proposal 1
Pass the old object into the `ResourceEventData` object as seen in PR #981 
### Proposal 2
Add a boolean field to the [ResourceEventSource](https://github.com/argoproj/argo-events/blob/ab4f16db4476f1e73b65e58e5d31818a44986f2e/pkg/apis/eventsource/v1alpha1/types.go#L247) struct that indicates whether or not you want the entire event object passed back. This would default to false to not break functionality.

---

cc/ @VaibhavPage @whynowy

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by scottweitzner** [comment]
linked to #891

**Comment by VaibhavPage** [comment]
This makes sense
