### ISSUE TITLE
Auto catch-up missing events when Resource type of EventSource is offline 

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#985]
**Is your feature request related to a problem? Please describe.**
For `Resource` type of EventSource, a field named `afterStart` is needed to watch k8s resources especially for k8s `Event`, otherwise it will catch duplicate events. However, with this field set, the missing events during the POD offline will also not be able to be detected.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Can we prioritize a fix to this because it is popular and we are exposed?

**Comment by whynowy** [comment]
Addressed by making the event source HA.
