### ISSUE TITLE
imagePullPolicy support for EventSource and Sensor images

### ISSUE THREAD

**Issue by haakonw-ksat** [argoproj/argo-events#987]
**Is your feature request related to a problem? Please describe.**
Due to dockerhubs download rate limit I have started to have problems running all my Argo Events **sensors** and **eventsources**. As far as I have seen form the documentation, there is no way to set the `imagePullPolicy` used by the different controllers.

**Describe the solution you'd like**
I would like to be able to set the `imagePullPolicy` in the same manner one is allowed to set the **eventsource** and **sensor** images, through environment variables.

**Describe alternatives you've considered**
A possible workaround is to download the image and place it in a private registry, as you are allowed to specify the image you want to use. Another way is to completely ignore the issue and instead re-organize the application(s) structure to minimize usage of multiple **sensors**/**eventsources**.

**Additional context**
I am running a deployer application that is setting up multiple, semi-isolated, applications that handle separate message streams. Each of these applications have their own eventsource and sensor. During testing I got an error because of hitting the rate limit.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@haakonw-ksat - It's already supported by specifying `spec.template.container.imagePullPolicy` for both EventSource and Sensor.

**Comment by haakonw-ksat** [comment]
I see, thank you @whynowy. This solved my issue.
