### ISSUE TITLE
Kafka trigger produces wrong timestamp

### ISSUE THREAD

**Issue by mrkwtz** [argoproj/argo-events#990]
**Describe the bug**
When an event is pushed to kafka the associated timestamp is always "-1". 

**To Reproduce**
Just connect any eventSource with a kafka trigger and consume the message via kafka-console-consumer. Your output is going to look like this

`CreateTime:-1	{"message":"test"}`

**Expected behavior**
A valid timestamp should be send to kafka.

**Environment (please complete the following information):**
 - Kubernetes: v1.17.12
 - Argo Events: v1.1.0

**Additional context**
I guess this is the same problem: https://stackoverflow.com/questions/52704889/invalid-timestamp-when-writing-a-kafka-producer-with-sarama

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
Did you set the kafka version like this: https://github.com/argoproj/argo-events/blob/master/examples/event-sources/kafka.yaml#L34

**Comment by mrkwtz** [comment]
This happens when I use the Kafka trigger, not as an event source.

**Comment by whynowy** [comment]
@mrkwtz  - I see, thanks! A optional `version` field should also be provided in the spec, does that sound good?

**Comment by whynowy** [comment]
And we might default the version to 1.0.0, which is same as EventSource.

**Comment by mrkwtz** [comment]
> @mrkwtz - I see, thanks! A optional `version` field should also be provided in the spec, does that sound good?

Thanks, that would be awesome! :)
