### ISSUE TITLE
InvocationType for AWS Lambda trigger

### ISSUE THREAD

**Issue by mrkwtz** [argoproj/argo-events#994]
**Is your feature request related to a problem? Please describe.**
I want to make use of AWS Lambdas [DeadLetterQueue feature](https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#dlq) for errors while processing async Lambda invocations. But right now it's [not possible](https://github.com/argoproj/argo-events/blob/master/sensors/triggers/aws-lambda/aws-lambda.go#L108-L110) to do a async invocation while [it could be](https://github.com/aws/aws-sdk-go/blob/v1.30.7/service/lambda/api.go#L9455).

**Describe the solution you'd like**
I'd like to have a InvocationType parameter in the Lambda trigger. 

**Describe alternatives you've considered**
For this case it's all about error handling. When I execute a Lambda function and it fails I want to be able to act on it. It would be awesome if argo-events itself has this feature, but for now I don't see a way to handle failed triggers within argo-events.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Is this the case of adding an additional invoke input? Would you like to submit a PR?

**Comment by VaibhavPage** [comment]
@mrkwtz can you explain your use-case when you say "acting on failed lambda"?

**Comment by mrkwtz** [comment]
@VaibhavPage, sure. When you configure a DeadLetterQueue (DLQ) in a Lambda function, failed invocations go straight to this queue from where another process could pick them up and report them or try the same event again but maybe with a more resilient and failure tolerant second function. Unfortunately DLQs are only considered when you do an asynchronous invocation of a Lambda function. So the Lambda trigger has to be extended to support the additional parameter.
