### ISSUE TITLE
Upgrade go-client to v1.19

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-events#999]
See https://github.com/argoproj/argo/issues/4785
We need this for Argo Workflows v3.0
We also need v1.2 to be released for https://github.com/argoproj/argo/issues/888

**Comment by alexec** [comment]
@nikenano I think we will want to have the same versions in both Argo Events and Argo Workflows.

**Comment by whynowy** [comment]
I would do 1.19.6 in events.
